<?php

declare(strict_types=1);

namespace Api\Controllers;

use Api\Constants\Message;
use Api\Constants\Role;
use Api\Email\Sender;
use Api\Email\SMTP;
use Api\Models\Auth;
use Exception;
use Phalcon\Http\Request\FileInterface;
use Phalcon\Mvc\Controller;
use Phalcon\Mvc\ModelInterface;
use Throwable;

class BaseController extends Controller {
    /**
     * Image MIME types accepted for photo uploads, mapped to the extension written to disk.
     * The extension is always derived from the detected type, never from the client's file name.
     */
    protected const array PHOTO_MIME_EXTENSIONS = [
        'image/jpeg' => 'jpg',
        'image/png'  => 'png',
        'image/gif'  => 'gif',
        'image/webp' => 'webp',
    ];

    /**
     * Dropped into every upload directory so nothing stored there can ever be executed by the web server.
     */
    protected const string UPLOAD_DIR_HTACCESS = <<<HTACCESS
# Generated by the API: this directory only serves static images.
<IfModule mod_php.c>
    php_flag engine off
</IfModule>
RemoveHandler .php .phtml .php3 .php4 .php5 .php7 .php8 .phps .phar .pl .py .cgi .sh
RemoveType .php .phtml .php3 .php4 .php5 .php7 .php8 .phps .phar .pl .py .cgi .sh
<FilesMatch "\\.(php\\d?|phtml|phps|phar|pl|py|cgi|sh|htaccess)$">
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_core.c>
        Order allow,deny
        Deny from all
    </IfModule>
</FilesMatch>
HTACCESS;

    /**
     * Get the parsed request body from the DI container
     */
    protected function getRequestBody(): array {
        try {
            if ($this->getDI()->has('request_body')) {
                return $this->getDI()->getRaw('request_body') ?? [];
            }
        } catch (Exception $e) {
            $message = $e->getMessage() . ' ' . $e->getTraceAsString() . ' ' . $e->getFile() . ' ' . $e->getLine();
            error_log('Exception: ' . $message);
        }
        return [];
    }

    /**
     * Get the authenticated user data from the DI container
     */
    protected function getAuthUser(): ?array {
        try {
            if ($this->getDI()->has('decodedToken')) {
                return $this->getDI()->getRaw('decodedToken') ?? [];
            }
        } catch (Exception $e) {
            $message = $e->getMessage() . ' ' . $e->getTraceAsString() . ' ' . $e->getFile() . ' ' . $e->getLine();
            error_log('Exception: ' . $message);
        }
        return [];
    }

    /**
     * Whether the request carries a verified session (set by the auth middleware)
     */
    protected function isAuthenticated(): bool {
        $authUser = $this->getAuthUser();
        return isset($authUser['id']) && (int)$authUser['id'] > 0;
    }

    /**
     * Get the current user ID from the authenticated token (-1 when unauthenticated)
     */
    protected function getCurrentUserId(): int {
        $authUser = $this->getAuthUser();
        return isset($authUser['id']) ? (int)$authUser['id'] : -1;
    }

    /**
     * Get the current user role from the authenticated token.
     * Returns -1 when unauthenticated; callers must use isAdmin()/isManagerOrHigher(),
     * never compare this value numerically.
     */
    protected function getCurrentUserRole(): int {
        $authUser = $this->getAuthUser();
        return isset($authUser['role']) ? (int)$authUser['role'] : -1;
    }

    /**
     * Check if the current user has admin role
     */
    protected function isAdmin(): bool {
        return $this->getCurrentUserRole() === Role::ADMINISTRATOR;
    }

    /**
     * Check if the current user is a manager or an administrator
     */
    protected function isManagerOrHigher(): bool {
        return in_array($this->getCurrentUserRole(), [Role::ADMINISTRATOR, Role::MANAGER], true);
    }

    /**
     * Create a standardized success response
     */
    protected function respondWithSuccess(array|string $data, int $statusCode = 200, array|string $message = Message::NA): array {
        $response = [
            'status' => 'success',
            'code' => $statusCode,
            'data' => $data,
        ];

        // Only add the 'message' key if $message is not the string 'na'
        if ($message !== Message::NA) $response['message'] = $message;

        return $response;
    }

    /**
     * Create a standardized error response
     */
    protected function respondWithError(array|string $message, int $statusCode = 400): array {
        return [
            'status' => 'error',
            'code' => $statusCode,
            'message' => $message
        ];
    }

    /**
     * First validation message of a model that failed to save, for error responses
     */
    protected function getFirstErrorMessage(ModelInterface $model): string {
        $messages = $model->getMessages();
        if (count($messages) > 0) {
            return (string)$messages[0]->getMessage();
        }
        return 'An unknown error occurred';
    }

    /**
     * Log an unexpected exception with full detail and return a generic error response.
     * Exception text never reaches the client: it can contain SQL, file paths or credentials.
     */
    protected function handleException(Throwable $e, int $statusCode = 500, string $publicMessage = 'An unexpected error occurred'): array {
        error_log(sprintf(
            '%s: %s in %s:%d%s%s',
            static::class,
            $e->getMessage(),
            $e->getFile(),
            $e->getLine(),
            PHP_EOL,
            $e->getTraceAsString()
        ));
        return $this->respondWithError($publicMessage, $statusCode);
    }

    /**
     * Get an Auth model for the current authenticated user
     */
    protected function getCurrentAuthUser(): ?Auth {
        $userId = $this->getCurrentUserId();
        if ($userId < 0) {
            return null;
        }

        return $this->getAuthUserById($userId);
    }

    /**
     * Get an Auth model by user ID
     */
    protected function getAuthUserById(int $userId): ?Auth {
        return Auth::findFirstById($userId);
    }

    /**
     * Begin a database transaction
     */
    protected function beginTransaction(): void {
        $this->db->begin();
    }

    /**
     * Commit a database transaction
     */
    protected function commitTransaction(): void {
        $this->db->commit();
    }

    /**
     * Rollback a database transaction
     */
    protected function rollbackTransaction(): void {
        if ($this->db->isUnderTransaction()) {
            $this->db->rollback();
        }
    }

    /**
     * Execute an operation within a transaction
     *
     * @param callable $operation The function to execute within the transaction
     * @return mixed The result of the operation
     */
    protected function withTransaction(callable $operation) {
        try {
            // Make sure $this->db is available
            if (!isset($this->db) || !$this->db) {
                // Try to get the db service from the DI container
                $this->db = $this->getDI()->get('db');

                // If still not available, throw a meaningful exception
                if (!$this->db) {
                    throw new Exception("Database service not available");
                }
            }

            $this->beginTransaction();
            $result = $operation();

            // The operation reported a business error: nothing it wrote may persist
            // (e.g. register(): auth row saved but user row failed).
            if (is_array($result) && ($result['status'] ?? null) === 'error') {
                $this->rollbackTransaction();
                return $result;
            }

            $this->commitTransaction();
            return $result;
        } catch (Exception $e) {
            $message = $e->getMessage() . ' ' . $e->getTraceAsString() . ' ' . $e->getFile() . ' ' . $e->getLine();
            error_log('Exception: ' . $message);
            if ($this->db && $this->db->isUnderTransaction()) {
                $this->rollbackTransaction();
            }
            throw $e;
        }
    }

    protected function processEmail(string $to, string $subject, string $body, bool $isHtml = false): ?array {
        $mail = null;
        try {
            $mail = new Sender(true);
            $mail->isSMTP();
            $mail->Host =  getenv('EMAIL_HOSTPATH') ?: '127.0.0.1';
            $mail->Port = getenv('EMAIL_SERVPORT') ?: 25;
            $mail->SMTPAuth = filter_var(getenv('EMAIL_SMTPAUTH') ?: 'false', FILTER_VALIDATE_BOOLEAN); // env values are strings ("true"/"false")
            $mail->Username = getenv('EMAIL_USERNAME') ?: '';
            $mail->Password = getenv('EMAIL_PASSWORD') ?: '';
            // EMAIL_SMTPSECURE: "ssl" (default, implicit TLS on 465), "tls" (STARTTLS) or "" (none, local dev)
            $smtpSecure = getenv('EMAIL_SMTPSECURE');
            $mail->SMTPSecure = $smtpSecure === false ? Sender::ENCRYPTION_SMTPS : $smtpSecure;
            $mail->SMTPDebug = SMTP::DEBUG_OFF;

            $mail->setFrom(getenv('EMAIL_REP_ADDR') ?: 'failsafe@maxmilahomecare.com', getenv('EMAIL_REP_NAME') ?: 'Maxmila Homecare Failsafe System');
            $mail->addAddress($to);

            $mail->isHTML($isHtml);
            $mail->Subject = $subject;
            $mail->Body = $body;
            if($isHtml) $mail->AltBody = strip_tags($body);

            return $mail->send();
        } catch (Exception $e) {
            error_log("BaseController->processEmail(): Exception: " . $e->getMessage() . " Sender:" . ($mail->ErrorInfo ?? 'n/a'));
            return null;
        }
    }

    /**
     * Validate and store an uploaded photo.
     *
     * Security properties:
     *  - the image type is detected from the file content (getimagesize + finfo), never from the
     *    client-supplied Content-Type or file name;
     *  - the on-disk extension is forced from the detected type, so a ".php" can never land in the dir;
     *  - the directory carries a .htaccess that disables script execution.
     * Callers delete the previous photo with deleteStoredPhoto() once the new path is saved.
     *
     * @param FileInterface $photo     Uploaded file (first entry of $request->getUploadedFiles())
     * @param string        $uploadDir Directory relative to the web root, e.g. User::PATH_PHOTO_FILE
     * @param string        $baseName  File name without extension, e.g. "12-jane-doe"
     * @return array|string ['path' => '/user/photo/12-jane-doe.jpg', 'filename' => '12-jane-doe.jpg'] or an error message
     */
    protected function storeUploadedPhoto(FileInterface $photo, string $uploadDir, string $baseName): array|string {
        $tempPath = $photo->getTempName();
        if (!$tempPath || !is_uploaded_file($tempPath)) {
            return Message::UPLOAD_FAILED;
        }

        $mime = $this->detectImageMime($tempPath);
        if ($mime === null) {
            return Message::UPLOAD_INVALID_TYPE;
        }
        $extension = self::PHOTO_MIME_EXTENSIONS[$mime];

        $safeBase = strtolower(preg_replace('/[^a-z0-9\-]/i', '', $baseName) ?? '');
        $filename = ($safeBase !== '' ? $safeBase : 'photo') . '.' . $extension;

        $relativeDir = trim($uploadDir, '/');
        $absoluteDir = BASE_PATH . '/' . $relativeDir;
        if (!is_dir($absoluteDir) && !mkdir($absoluteDir, 0755, true) && !is_dir($absoluteDir)) {
            error_log("storeUploadedPhoto: cannot create directory $absoluteDir");
            return Message::UPLOAD_FAILED;
        }
        $this->protectUploadDir($absoluteDir);

        $absolutePath = $absoluteDir . '/' . $filename;

        // Preferred path: re-encode through Imagick (resizes, strips metadata and any embedded payload).
        // Fallback: the file already passed content-type detection and gets a forced image extension
        // inside a directory where execution is disabled.
        if (!$this->processAndResizeImage($tempPath, $absolutePath)) {
            if (!$photo->moveTo($absolutePath)) {
                return Message::UPLOAD_PHOTO_FAILED;
            }
        }

        return ['path' => '/' . $relativeDir . '/' . $filename, 'filename' => $filename];
    }

    /**
     * Delete a previously stored photo, but only if it really lives inside the given upload directory
     * and is neither the default photo nor the path that is currently in use.
     */
    protected function deleteStoredPhoto(?string $publicPath, string $uploadDir, string $defaultPhoto = '', string $keepPath = ''): void {
        if ($publicPath === null || $publicPath === '' || $publicPath === $defaultPhoto || $publicPath === $keepPath) {
            return;
        }
        $dir = realpath(BASE_PATH . '/' . trim($uploadDir, '/'));
        $file = realpath(BASE_PATH . '/' . ltrim($publicPath, '/'));
        if ($dir === false || $file === false || !is_file($file)) {
            return;
        }
        if (!str_starts_with($file, $dir . DIRECTORY_SEPARATOR)) {
            error_log("deleteStoredPhoto: refused to delete $file outside $dir");
            return;
        }
        @unlink($file);
    }

    /**
     * Detect the image MIME type from file content. Returns null unless both getimagesize() and
     * finfo agree on one of the accepted types.
     */
    private function detectImageMime(string $path): ?string {
        $info = @getimagesize($path);
        if ($info === false || empty($info['mime'])) {
            return null;
        }
        $mime = strtolower((string)$info['mime']);

        if (function_exists('finfo_open')) {
            $finfo = finfo_open(FILEINFO_MIME_TYPE);
            if ($finfo) {
                $detected = finfo_file($finfo, $path);
                finfo_close($finfo);
                if ($detected === false || strtolower($detected) !== $mime) {
                    return null;
                }
            }
        }

        return array_key_exists($mime, self::PHOTO_MIME_EXTENSIONS) ? $mime : null;
    }

    /**
     * Make sure an upload directory cannot execute scripts, even if the deploy missed the .htaccess.
     */
    private function protectUploadDir(string $absoluteDir): void {
        $htaccess = $absoluteDir . '/.htaccess';
        if (is_file($htaccess)) {
            return;
        }
        if (@file_put_contents($htaccess, self::UPLOAD_DIR_HTACCESS . PHP_EOL) === false) {
            error_log("protectUploadDir: could not write $htaccess");
        }
    }

    /**
     * Process and resize image using ImageMagick
     *
     * @param string $sourcePath Path to original image
     * @param string $destinationPath Path where processed image will be saved
     * @param int $width Desired width (default: 360)
     * @param int $height Desired height (default: 360)
     * @return bool True if processing successful
     */
    protected function processAndResizeImage(string $sourcePath, string $destinationPath, int $width = 360, int $height = 360): bool {
        try {
            // Check if ImageMagick extension is installed
            if (!extension_loaded('imagick')) {
                error_log('ImageMagick extension not installed');
                return false;
            }

            // Create a new Imagick object
            $image = new \Imagick($sourcePath);

            // Set the image to the specified dimensions with proper aspect ratio
            $originalWidth = $image->getImageWidth();
            $originalHeight = $image->getImageHeight();

            // Calculate the scale factor
            $scaleWidth = $width / $originalWidth;
            $scaleHeight = $height / $originalHeight;
            $scale = max($scaleWidth, $scaleHeight);

            // Calculate new dimensions and convert to integers
            $newWidth = (int)round($originalWidth * $scale);
            $newHeight = (int)round($originalHeight * $scale);

            // Resize the image with integer values
            $image->resizeImage($newWidth, $newHeight, \Imagick::FILTER_LANCZOS, 1);

            // Crop to exact dimensions from center with integer values
            $cropX = (int)(($newWidth - $width) / 2);
            $cropY = (int)(($newHeight - $height) / 2);
            $image->cropImage($width, $height, $cropX, $cropY);

            // Set image quality (90% for good quality with reasonable file size)
            $image->setImageCompressionQuality(90);

            // Strip EXIF data for privacy
            $image->stripImage();

            // Save the processed image
            $image->writeImage($destinationPath);

            // Clear the image from memory
            $image->clear();
            $image->destroy();

            return true;
        } catch (\ImagickException $e) {
            error_log('ImageMagick processing error: ' . $e->getMessage());
            return false;
        }
    }
}
