
###
# @name Create Account
POST {{maxmila.baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "edmundo_ch@hotmail.com",
  "password": "edmundo2025"
}

###
# @name Login
POST {{maxmila.baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "{{maxmila.username}}",
  "password": "{{maxmila.password}}"
}

###
# @name Activate Account by the System
PUT {{maxmila.baseUrl}}/auth/activate/account
Content-Type: application/json
Authorization: {{maxmila.token}}

{
  "id": 1
}

###
# @name Renew Token
PUT {{maxmila.baseUrl}}/auth/renew/token
Content-Type: application/json
Authorization: {{maxmila.token}}


###
# @name Change Role
PUT {{maxmila.baseUrl}}/auth/change/role
Content-Type: application/json
Authorization: {{maxmila.token}}

{
  "id": 1,
  "role": 1
}

###
# @name Change Password from system
PUT {{maxmila.baseUrl}}/auth/change/password
Content-Type: application/json

{
  "username": "toddsalpen@gmail.com",
  "password": "ToddSalpen6589"
}