###
# group: Backup Recovery
# @name Add Bulk Accounts
POST {{maxmila.baseUrl}}/bulk/auths
Content-Type: application/json

[
  {
    "username": "trinketronix@gmail.com",
    "password": "TrinketronixLLC6589",
    "role": 0,
    "status": 1
  },
  {
    "username": "edmundo.chavez@gmail.com",
    "password": "EdmundoChavez6589",
    "role": 0,
    "status": 1
  },
  {
    "username": "toddsalpen@gmail.com",
    "password": "ToddSalpen6589",
    "role": 1,
    "status": 1
  },
  {
    "username": "olyachopik@gmail.com",
    "password": "OlhaChopyk2601",
    "role": 2,
    "status": 1
  },
  {
    "username": "andrei.buzatu@gmail.com",
    "password": "AndreiBuzatu7596",
    "role": 2,
    "status": 1
  },
  {
    "username": "zhikuiling@yahoo.com",
    "password": "ZhiKuiLing5455",
    "role": 2,
    "status": 1
  },
  {
    "username": "Yuyao1205@yahoo.com",
    "password": "YuYao1786",
    "role": 2,
    "status": 1
  },
  {
    "username": "huiipersonal@gmail.com",
    "password": "YuemingYang1825",
    "role": 2,
    "status": 1
  },
  {
    "username": "khaitmaria8@gmail.com",
    "password": "MariyaSheuchyk7874",
    "role": 2,
    "status": 1
  },
  {
    "username": "ramishka8184@gmail.com",
    "password": "RamiliaSultanova6675",
    "role": 2,
    "status": 1
  },
  {
    "username": "shuoyang@yahoo.com",
    "password": "ShuoYang8096",
    "role": 2,
    "status": 1
  },
  {
    "username": "jlutes2017@yahoo.com",
    "password": "ElenaLutes4606",
    "role": 2,
    "status": 1
  },
  {
    "username": "zahwa120@icloud.com",
    "password": "ZahwaShehadeh0442",
    "role": 2,
    "status": 1
  },
  {
    "username": "beet917@gmail.com",
    "password": "XinLin3259",
    "role": 2,
    "status": 1
  },
  {
    "username": "lianchangqiao@gmail.com",
    "password": "LianchangQiao8241",
    "role": 2,
    "status": 1
  },
  {
    "username": "sshao21@yahoo.com",
    "password": "EdwardWang3655",
    "role": 2,
    "status": 1
  },
  {
    "username": "karimovanoza@icloud.com",
    "password": "SarvinozKarimova0075",
    "role": 2,
    "status": 1
  },
  {
    "username": "sshao321@yahoo.com",
    "password": "SophieShao0428",
    "role": 2,
    "status": 1
  },
  {
    "username": "lanawithballet@gmail.com",
    "password": "SvetlanaKowalczyk5038",
    "role": 1,
    "status": 1
  },
  {
    "username": "42963418@qq.com",
    "password": "LiquChen8109",
    "role": 2,
    "status": 1
  },
  {
    "username": "ricardoestes@comcast.net",
    "password": "RicardoEstes0985",
    "role": 2,
    "status": 1
  },
  {
    "username": "mariyavarshavska9@gmail.com",
    "password": "MariyaVarshavska7229",
    "role": 2,
    "status": 1
  },
  {
    "username": "yxwenster@gmail.com",
    "password": "YuelinLi6792",
    "role": 2,
    "status": 1
  },
  {
    "username": "henrynina48083@hotmial.com",
    "password": "HongjunZhao4229",
    "role": 2,
    "status": 1
  },
  {
    "username": "jieminggao@yahoo.com",
    "password": "QingGao2406",
    "role": 2,
    "status": 1
  },
  {
    "username": "gyezersky82@gmail.com",
    "password": "GeoffreyYezersky6834",
    "role": 2,
    "status": 1
  },
  {
    "username": "evan.p.chang@gmail.com",
    "password": "EvanChang9708",
    "role": 2,
    "status": 1
  },
  {
    "username": "lili4945@gmail.com",
    "password": "LiLi8729",
    "role": 2,
    "status": 1
  },
  {
    "username": "angielin99@yahoo.com",
    "password": "AngieLin2730",
    "role": 2,
    "status": 1
  },
  {
    "username": "yl19802004@gmail.com",
    "password": "YangyangLi9401",
    "role": 2,
    "status": 1
  },
  {
    "username": "lyezersky7@gmail.com",
    "password": "LarisaYezersky5144",
    "role": 2,
    "status": 1
  },
  {
    "username": "jinpanw@gmail.com",
    "password": "JinPan0208",
    "role": 2,
    "status": 1
  },
  {
    "username": "aimeedaisyy@gmail.com",
    "password": "AimeeLaLonde6024",
    "role": 2,
    "status": 1
  },
  {
    "username": "yongchentian@gmail.com",
    "password": "YuTian8717",
    "role": 2,
    "status": 1
  },
  {
    "username": "tampim2@gmail.com",
    "password": "GalinaLyashenko3906",
    "role": 2,
    "status": 1
  },
  {
    "username": "yulikowalczyk@gmail.com",
    "password": "YuliannaKowalczyk4358",
    "role": 2,
    "status": 1
  },
  {
    "username": "abirfadlallah6@gmail.com",
    "password": "AbirFadlallah3811",
    "role": 2,
    "status": 1
  },
  {
    "username": "annechenzhu1965@gmail.com",
    "password": "AnnaZhu0168",
    "role": 2,
    "status": 1
  },
  {
    "username": "ngmike33@gmail.com",
    "password": "MichaelNg0652",
    "role": 2,
    "status": 1
  },
  {
    "username": "ammakki9@gmail.com",
    "password": "AmalMakki7626",
    "role": 2,
    "status": 1
  },
  {
    "username": "grannykathy08@gmail.com",
    "password": "KathrynRogers3935",
    "role": 2,
    "status": 1
  },
  {
    "username": "olga.baruk@gmail.com",
    "password": "OlgaBaruk9380",
    "role": 2,
    "status": 1
  },
  {
    "username": "ahine2019@icloud.com",
    "password": "CharlotteAdjei4805",
    "role": 2,
    "status": 1
  },
  {
    "username": "sandravanderbilt6@gmail.com",
    "password": "SandraVanderbilt0412",
    "role": 2,
    "status": 1
  },
  {
    "username": "annaxue0925@gmail.com",
    "password": "AnnaXue1263",
    "role": 2,
    "status": 1
  },
  {
    "username": "dbdumitrescu@outlook.com",
    "password": "DevoraDumitrescu2881",
    "role": 2,
    "status": 1
  },
  {
    "username": "maxzhitkov@gmail.com",
    "password": "MaksimZhitkov3131",
    "role": 2,
    "status": 1
  },
  {
    "username": "makenzyherman711@gmail.com",
    "password": "MakenzyHerman4607",
    "role": 2,
    "status": 1
  },
  {
    "username": "PamVavoom1@gmail.com",
    "password": "JamesBlunden7596",
    "role": 2,
    "status": 1
  },
  {
    "username": "lqi78865@gmail.com",
    "password": "LiqunQiu5955",
    "role": 2,
    "status": 1
  },
  {
    "username": "conniepospeshil@yahoo.com",
    "password": "ConniePospeshil7524",
    "role": 2,
    "status": 1
  },
  {
    "username": "langeyue@gmail.com",
    "password": "LanGe1842",
    "role": 2,
    "status": 1
  },
  {
    "username": "annaligc1973@gmail.com",
    "password": "AnnaLi2932",
    "role": 2,
    "status": 1
  },
  {
    "username": "Lina.khanafer@live.com",
    "password": "LinaChehadeh6583",
    "role": 2,
    "status": 1
  },
  {
    "username": "hchen33@gmail.com",
    "password": "HuaChen2641",
    "role": 2,
    "status": 1
  },
  {
    "username": "zhlillian@yahoo.com",
    "password": "LingZhong4436",
    "role": 2,
    "status": 1
  },
  {
    "username": "xing.xy@gmail.com",
    "password": "XianyingXing9617",
    "role": 2,
    "status": 1
  },
  {
    "username": "msblackelk@yahoo.com",
    "password": "LeahBlackElk7618",
    "role": 2,
    "status": 1
  },
  {
    "username": "lidongdi1962@gmail.com",
    "password": "DongdiLi5708",
    "role": 2,
    "status": 1
  },
  {
    "username": "mxue2014@gmail.com",
    "password": "MeiXue2844",
    "role": 2,
    "status": 1
  },
  {
    "username": "hanleiwang.hlw@gmail.com",
    "password": "HanleiWang4066",
    "role": 2,
    "status": 1
  },
  {
    "username": "williamsw19631963@gmail.com",
    "password": "WillieWilliams8446",
    "role": 2,
    "status": 1
  },
  {
    "username": "weizhao101@hotmail.com",
    "password": "WeiZhao7101",
    "role": 2,
    "status": 1
  },
  {
    "username": "weix0014@hotmail.com",
    "password": "QiangWei6708",
    "role": 2,
    "status": 1
  },
  {
    "username": "hzhang996@gmail.com",
    "password": "HongZhang7150",
    "role": 2,
    "status": 1
  },
  {
    "username": "irizarryjose433@gmail.com",
    "password": "joseIrizarry7220",
    "role": 2,
    "status": 1
  },
  {
    "username": "princessalize2010@gmail.com",
    "password": "JuselineSainz1831",
    "role": 2,
    "status": 1
  },
  {
    "username": "459634669@qq.com",
    "password": "YongmeiLiang8409",
    "role": 2,
    "status": 1
  },
  {
    "username": "taksunchung66@gmail.com",
    "password": "TakSunChung1262",
    "role": 2,
    "status": 1
  },
  {
    "username": "zjj48071@gmail.com",
    "password": "JuanJuanzhu7846",
    "role": 2,
    "status": 1
  },
  {
    "username": "gergana@umich.edu",
    "password": "GerganaKodjebacheva7882",
    "role": 2,
    "status": 1
  },
  {
    "username": "xchen168138@gmail.com",
    "password": "XiaoXiaChen3383",
    "role": 2,
    "status": 1
  },
  {
    "username": "liupingliang83@gmail.com",
    "password": "LupingLiang5547",
    "role": 2,
    "status": 1
  },
  {
    "username": "david800803@gmail.com",
    "password": "ZhiweiYan3067",
    "role": 2,
    "status": 1
  },
  {
    "username": "1906442418@qq.com",
    "password": "YuanquChen5717",
    "role": 2,
    "status": 1
  },
  {
    "username": "irina.vasiuk@gmail.com",
    "password": "IrynaVasiuk9369",
    "role": 2,
    "status": 1
  },
  {
    "username": "rawanlakis@icloud.com",
    "password": "MonaAwada4413",
    "role": 2,
    "status": 1
  },
  {
    "username": "kemanli2014@gmail.com",
    "password": "KemanLi6932",
    "role": 2,
    "status": 1
  },
  {
    "username": "innaukr@gmail.com",
    "password": "InnaTikan1130",
    "role": 2,
    "status": 1
  },
  {
    "username": "vladimiswitas305@gmail.com",
    "password": "SvitlanaNakonechna3421",
    "role": 2,
    "status": 1
  },
  {
    "username": "yaqun17@gmail.com",
    "password": "YaqunZhu8063",
    "role": 2,
    "status": 1
  },
  {
    "username": "bolykalla@ukr.net",
    "password": "AllaBoliukh3215",
    "role": 2,
    "status": 1
  },
  {
    "username": "hectorsalpen@gmail.com",
    "password": "HectorSalinas6589",
    "role": 2,
    "status": 1
  },
  {
    "username": "xzhang7@wccnet.edu",
    "password": "XiaZhang2398",
    "role": 2,
    "status": 1
  },
  {
    "username": "rj107521186@gmail.com",
    "password": "JunRuan7248",
    "role": 2,
    "status": 1
  },
  {
    "username": "yangqingbo5@gmail.com",
    "password": "QingboYang5177",
    "role": 2,
    "status": 1
  },
  {
    "username": "191023092@qq.com",
    "password": "HongHu2891",
    "role": 2,
    "status": 1
  },
  {
    "username": "jcchen0518@gmail.com",
    "password": "JiangchenChen3215",
    "role": 2,
    "status": 1
  }
]

###
# group: Backup Recovery
# @name Update Bulk Users
PUT {{maxmila.baseUrl}}/bulk/users
Content-Type: application/json

[
  {
    "id":1,
    "firstname":"Trinketronix",
    "lastname":"LLC",
    "birthdate":"2022-08-04",
    "phone":"248-679-2601",
    "email":"trinketronix@gmail.com",
    "email2":"robotcitolab@gmail.com",
    "languages":"English, Spanish, Italian, Portugese, Mayan, Nahuatl",
    "address":{
      "type":"Apartment",
      "address":"7677 Maple Dr",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":2,
    "firstname":"Edmundo",
    "lastname":"Chavez",
    "birthdate":"1976-12-12",
    "email":"edmundo.chavez@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"204 Alfonso Caso",
      "city":"Tampico",
      "county":"Madero",
      "state":"TS",
      "zipcode":"89109",
      "country":"Mexico"
    }
  },
  {
    "id":3,
    "firstname":"Todd",
    "lastname":"Salpen",
    "birthdate":"1976-12-16",
    "phone":"248-679-2601",
    "email":"toddsalpen@gmail.com",
    "email2":"hectorsalpen@gmail.com",
    "languages":"English, Spanish, Italian, Portugese, Mayan, Nahuatl",
    "address":{
      "type":"Apartment",
      "address":"7677 Maple Dr",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":4,
    "firstname":"Olha",
    "lastname":"Chopyk",
    "code":"GLO-1059",
    "birthdate":"1989-10-11",
    "ssn":"001-67-2601",
    "phone":"313-804-2691",
    "email":"olyachopik@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"31278 Shorecrest Dr Apt.23207",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48377",
      "country":"United States"
    }
  },
  {
    "id":5,
    "firstname":"Andrei",
    "lastname":"Buzatu",
    "code":"GLO-1007",
    "birthdate":"1984-12-07",
    "ssn":"003-26-7596",
    "phone":"734-358-8860",
    "email":"andrei.buzatu@gmail.com",
    "languages":"English, Spanish, Romanian",
    "address":{
      "type":"Apartment",
      "address":"29348 Decuindre Rd #103",
      "city":"Warren",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48092",
      "country":"United States"
    }
  },
  {
    "id":6,
    "firstname":"Zhi-Kui",
    "lastname":"Ling",
    "code":"GLO-1012",
    "birthdate":"1961-10-18",
    "ssn":"016-62-5455",
    "phone":"248-974-5933",
    "email":"zhikuiling@yahoo.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"45211 Bartlett Drive",
      "city":"Novi",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48377",
      "country":"United States"
    }
  },
  {
    "id":7,
    "firstname":"Yu",
    "lastname":"Yao",
    "code":"GLO-1038",
    "birthdate":"1977-11-02",
    "ssn":"021-99-1786",
    "phone":"734-276-0011",
    "email":"Yuyao1205@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1058 Greenhills Dr.",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":8,
    "firstname":"Yueming",
    "lastname":"Yang",
    "code":"GLO-1029",
    "birthdate":"1963-11-19",
    "ssn":"087-86-1825",
    "phone":"734-502-1598",
    "email":"huiipersonal@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"35594 Dove Trail",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":9,
    "firstname":"Mariya",
    "lastname":"Sheuchyk",
    "code":"GLO-1071",
    "birthdate":"1987-01-18",
    "ssn":"099-81-7874",
    "phone":"810-493-1183",
    "email":"khaitmaria8@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"3725 Delaware Ave",
      "city":"Flint",
      "county":"Genesee",
      "state":"MI",
      "zipcode":"48506",
      "country":"United States"
    }
  },
  {
    "id":10,
    "firstname":"Ramilia",
    "lastname":"Sultanova",
    "code":"GLO-1013",
    "birthdate":"1981-10-19",
    "ssn":"156-73-6675",
    "phone":"903-505-4523",
    "email":"ramishka8184@gmail.com",
    "languages":"English, Spanish, Russian, Uzbek, Kyrgyz",
    "address":{
      "type":"Apartment",
      "address":"31155 Portside Dr. Apt.#7207",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48377",
      "country":"United States"
    }
  },
  {
    "id":11,
    "firstname":"Shuo",
    "lastname":"Yang",
    "code":"GLO-1003",
    "birthdate":"1960-06-07",
    "ssn":"215-29-8096",
    "phone":"248-880-7585",
    "email":"shuoyang@yahoo.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"33790 Norfolk",
      "city":"Livonia",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48152",
      "country":"United States"
    }
  },
  {
    "id":12,
    "firstname":"Elena",
    "lastname":"Lutes",
    "birthdate":"1979-02-06",
    "ssn":"277-15-4606",
    "phone":"513-289-7450",
    "email":"jlutes2017@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":13,
    "firstname":"Zahwa",
    "lastname":"Shehadeh",
    "birthdate":"1972-12-24",
    "ssn":"282-90-0442",
    "phone":"313-960-0048",
    "email":"zahwa120@icloud.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":14,
    "firstname":"Xin",
    "lastname":"Lin",
    "birthdate":"1984-01-28",
    "ssn":"283-08-3259",
    "phone":"248-525-9695",
    "email":"beet917@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":15,
    "firstname":"Lianchang",
    "lastname":"Qiao",
    "code":"GLO-1039",
    "birthdate":"1954-09-04",
    "ssn":"284-65-8241",
    "phone":"734-800-9504",
    "email":"lianchangqiao@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2864 Elmwood Avenue",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48104",
      "country":"United States"
    }
  },
  {
    "id":16,
    "firstname":"Edward",
    "lastname":"Wang",
    "code":"GLO-1056",
    "birthdate":"1965-07-14",
    "ssn":"287-90-3655",
    "phone":"248-202-7771",
    "email":"sshao21@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"256 Shore Brook Ln",
      "city":"Walled Lake",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48390",
      "country":"United States"
    }
  },
  {
    "id":17,
    "firstname":"Sarvinoz",
    "lastname":"Karimova",
    "code":"GLO-1040",
    "birthdate":"1995-06-05",
    "ssn":"290-83-0075",
    "phone":"248-513-5858",
    "email":"karimovanoza@icloud.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"24712 Independence Dr. Apt. 2302",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48335",
      "country":"United States"
    }
  },
  {
    "id":18,
    "firstname":"Sophie",
    "lastname":"Shao",
    "code":"GLO-1041",
    "birthdate":"1967-06-22",
    "ssn":"301-90-0428",
    "phone":"248-494-2636",
    "email":"sshao321@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"356 Shore Brook Ln",
      "city":"Walled Lake",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48390",
      "country":"United States"
    }
  },
  {
    "id":19,
    "firstname":"Svetlana",
    "lastname":"Kowalczyk",
    "code":"GLO-1001",
    "birthdate":"1968-10-22",
    "ssn":"309-15-5038",
    "phone":"734-560-1630",
    "email":"lanawithballet@gmail.com",
    "languages":"English, Spanish, Russian",
    "address":{
      "type":"Apartment",
      "address":"34500 Grandon Street",
      "city":"Livonia",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48150",
      "country":"United States"
    }
  },
  {
    "id":20,
    "firstname":"Liqu",
    "lastname":"Chen",
    "code":"GLO-1010",
    "birthdate":"1962-07-02",
    "ssn":"315-97-8109",
    "phone":"734-680-6688",
    "email":"42963418@qq.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"2448 Nixon Rd",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":21,
    "firstname":"Ricardo",
    "lastname":"Estes",
    "birthdate":"1968-01-20",
    "ssn":"330-56-0985",
    "phone":"734-545-3052",
    "email":"ricardoestes@comcast.net",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":22,
    "firstname":"Mariya",
    "lastname":"Varshavska",
    "code":"GLO-1034",
    "birthdate":"1969-10-11",
    "ssn":"348-59-7229",
    "phone":"734-730-2751",
    "email":"mariyavarshavska9@gmail.com",
    "email2":"algard1977@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2246 Yemans St",
      "city":"Hamtramck",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48212",
      "country":"United States"
    }
  },
  {
    "id":23,
    "firstname":"Yuelin",
    "lastname":"Li",
    "code":"GLO-1031",
    "birthdate":"1953-11-22",
    "ssn":"357-15-6792",
    "phone":"248-251-9350",
    "email":"yxwenster@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1578 Caliper Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48084",
      "country":"United States"
    }
  },
  {
    "id":24,
    "firstname":"Hongjun",
    "lastname":"Zhao",
    "code":"GLO-1015",
    "birthdate":"1976-09-18",
    "ssn":"360-96-4229",
    "phone":"248-925-9398",
    "email":"henrynina48083@hotmial.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"286 Miracle Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48084",
      "country":"United States"
    }
  },
  {
    "id":25,
    "firstname":"Qing",
    "lastname":"Gao",
    "code":"GLO-1050",
    "birthdate":"1964-06-19",
    "ssn":"362-23-2406",
    "phone":"248-403-1465",
    "email":"jieminggao@yahoo.com",
    "languages":"English, Spanish, Chinese",
    "address":{
      "type":"Apartment",
      "address":"20939 Meadowlark St",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country":"United States"
    }
  },
  {
    "id":26,
    "firstname":"Geoffrey",
    "lastname":"Yezersky",
    "code":"GLO-1073",
    "birthdate":"1999-10-07",
    "ssn":"363-25-6834",
    "phone":"248-553-5429",
    "email":"gyezersky82@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"35987 Charter Crest Road",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48335",
      "country":"United States"
    }
  },
  {
    "id":27,
    "firstname":"Evan",
    "lastname":"Chang",
    "code":"GLO-1008",
    "birthdate":"2001-05-03",
    "ssn":"364-27-9708",
    "phone":"810-893-1778",
    "email":"evan.p.chang@gmail.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"3807 Woodmonte Dr ",
      "city":"Rochester",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48306",
      "country":"United States"
    }
  },
  {
    "id":28,
    "firstname":"Li",
    "lastname":"Li",
    "code":"GLO-1055",
    "birthdate":"1971-05-13",
    "ssn":"366-29-8729",
    "phone":"248-795-0385",
    "email":"lili4945@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"4945 Moonglow Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48098",
      "country":"United States"
    }
  },
  {
    "id":29,
    "firstname":"Angie",
    "lastname":"Lin",
    "code":"GLO-1044",
    "birthdate":"1977-12-04",
    "ssn":"366-33-2730",
    "phone":"248-342-8039",
    "email":"angielin99@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"117 Manor Way",
      "city":"Rochester",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48309",
      "country":"United States"
    }
  },
  {
    "id":30,
    "firstname":"Yangyang",
    "lastname":"Li",
    "birthdate":"1980-02-14",
    "ssn":"366-33-9401",
    "phone":"248-881-0209",
    "email":"yl19802004@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":31,
    "firstname":"Larisa",
    "lastname":"Yezersky",
    "code":"GLO-1018",
    "birthdate":"1971-08-24",
    "ssn":"367-19-5144",
    "phone":"248-660-3570",
    "email":"lyezersky7@gmail.com",
    "languages":"English, Spanish, Russian",
    "address":{
      "type":"Apartment",
      "address":"35987 Charter Crest Farmington",
      "city":"Farmington Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48335",
      "country":"United States"
    }
  },
  {
    "id":32,
    "firstname":"Jin",
    "lastname":"Pan",
    "code":"GLO-1019",
    "birthdate":"1962-08-24",
    "ssn":"367-25-0208",
    "phone":"734-673-4276",
    "email":"jinpanw@gmail.com",
    "languages":"English, Spanish, Chinese",
    "address":{
      "type":"Apartment",
      "address":"48125 Gladstone Rd",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48188",
      "country":"United States"
    }
  },
  {
    "id":33,
    "firstname":"Aimee",
    "lastname":"LaLonde",
    "code":"GLO-1014",
    "birthdate":"1971-10-12",
    "ssn":"367-74-6024",
    "phone":"734-556-7335",
    "email":"aimeedaisyy@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1376 Northwood",
      "city":"Inkster",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48141",
      "country":"United States"
    }
  },
  {
    "id":34,
    "firstname":"Yu",
    "lastname":"Tian",
    "code":"GLO-1026",
    "birthdate":"1970-04-28",
    "ssn":"370-19-8717",
    "phone":"248-759-1633",
    "email":"yongchentian@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"44000 Settlers Creek",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48375",
      "country":"United States"
    }
  },
  {
    "id":35,
    "firstname":"Galina",
    "lastname":"Lyashenko",
    "code":"GLO-1024",
    "birthdate":"1962-02-22",
    "ssn":"371-25-3906",
    "phone":"586-303-5866",
    "email":"tampim2@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"17719 Roseville Blvd",
      "city":"Roseville",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48066",
      "country":"United States"
    }
  },
  {
    "id":36,
    "firstname":"Yulianna",
    "lastname":"Kowalczyk",
    "code":"GLO-1051",
    "birthdate":"2006-06-12",
    "ssn":"371-33-4358",
    "phone":"734-620-9384",
    "email":"yulikowalczyk@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"34500 Grandon Street",
      "city":"Livonia",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48150",
      "country":"United States"
    }
  },
  {
    "id":37,
    "firstname":"Abir",
    "lastname":"Fadlallah",
    "code":"GLO-1021",
    "birthdate":"1972-03-06",
    "ssn":"371-96-3811",
    "phone":"313-729-4444",
    "email":"abirfadlallah6@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"27105 Terrel Street",
      "city":"Dearborn Heights",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48127",
      "country":"United States"
    }
  },
  {
    "id":38,
    "firstname":"Anna",
    "lastname":"Zhu",
    "code":"GLO-1028",
    "birthdate":"1965-11-07",
    "ssn":"372-06-0168",
    "phone":"734-882-5444",
    "email":"annechenzhu1965@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"42063 Trent Drive",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48188",
      "country":"United States"
    }
  },
  {
    "id":39,
    "firstname":"Michael",
    "middlename":"G",
    "lastname":"Ng",
    "code":"GLO-1017",
    "birthdate":"1980-09-29",
    "ssn":"372-88-0652",
    "phone":"248-854-6210",
    "email":"ngmike33@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"4712 Marian Ave",
      "city":"Warren",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48092",
      "country":"United States"
    }
  },
  {
    "id":40,
    "firstname":"Amal",
    "middlename":"F",
    "lastname":"Makki",
    "code":"GLO-1020",
    "birthdate":"1961-08-10",
    "ssn":"372-94-7626",
    "phone":"248-396-3801",
    "email":"ammakki9@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"21260 Woodland Glen Dr Apt 202",
      "city":"Northville",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48167",
      "country":"United States"
    }
  },
  {
    "id":41,
    "firstname":"Kathryn",
    "lastname":"Rogers",
    "birthdate":"1954-08-20",
    "ssn":"373-66-3935",
    "phone":"248-987-4640",
    "email":"grannykathy08@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":42,
    "firstname":"Olga",
    "lastname":"Baruk",
    "code":"GLO-1005",
    "birthdate":"1970-08-09",
    "ssn":"375-21-9380",
    "phone":"734-788-5714",
    "email":"olga.baruk@gmail.com",
    "languages":"English, Spanish, Russian",
    "address":{
      "type":"Apartment",
      "address":"41899 Warren Rd",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48187",
      "country":"United States"
    }
  },
  {
    "id":43,
    "firstname":"Charlotte",
    "lastname":"Adjei",
    "code":"GLO-1004",
    "birthdate":"1967-08-13",
    "ssn":"376-25-4805",
    "phone":"313-221-3434",
    "email":"ahine2019@icloud.com",
    "languages":"English, Spanish, Ghana",
    "address":{
      "type":"Apartment",
      "address":"7261 Wilderness Park Drive #201",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":44,
    "firstname":"Sandra",
    "lastname":"Vanderbilt",
    "birthdate":"1961-02-13",
    "ssn":"376-66-0412",
    "phone":"734-680-0342",
    "email":"sandravanderbilt6@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":45,
    "firstname":"Anna",
    "lastname":"Xue",
    "birthdate":"1963-09-25",
    "ssn":"377-29-1263",
    "phone":"248-613-1398",
    "email":"annaxue0925@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":46,
    "firstname":"Devora",
    "lastname":"Dumitrescu",
    "code":"GLO-1035",
    "birthdate":"1957-12-06",
    "ssn":"378-86-2881",
    "phone":"313-909-2665",
    "email":"dbdumitrescu@outlook.com",
    "email2":"vdumitrescu@outlook.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"10387 Overhill Dr",
      "city":"Brighton",
      "county":"Livingston",
      "state":"MI",
      "zipcode":"48114",
      "country":"United States"
    }
  },
  {
    "id":47,
    "firstname":"Maksim",
    "lastname":"Zhitkov",
    "code":"GLO-1037",
    "birthdate":"1970-12-27",
    "ssn":"381-15-3131",
    "phone":"248-935-7195",
    "email":"maxzhitkov@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"7119 Oakridge Ct",
      "city":"Clarkston",
      "county":"Clare",
      "state":"MI",
      "zipcode":"48346",
      "country":"United States"
    }
  },
  {
    "id":48,
    "firstname":"Makenzy",
    "lastname":"Herman",
    "code":"GLO-1065",
    "birthdate":"1999-05-10",
    "ssn":"381-23-4607",
    "phone":"248-495-9732",
    "email":"makenzyherman711@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"23360 Crossley Ave",
      "city":"Hazel Park",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48030",
      "country":"United States"
    }
  },
  {
    "id":49,
    "firstname":"James",
    "lastname":"Blunden",
    "code":"GLO-1006",
    "birthdate":"1927-01-01",
    "ssn":"381-26-7596",
    "phone":"248-390-0124",
    "email":"PamVavoom1@gmail.com",
    "email2":"jimblunden@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"552 E Annabelle Ave  ",
      "city":"Hazel Park",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48030",
      "country":"United States"
    }
  },
  {
    "id":50,
    "firstname":"Liqun",
    "lastname":"Qiu",
    "code":"GLO-1030",
    "birthdate":"1961-11-24",
    "ssn":"382-19-5955",
    "phone":"248-635-0887",
    "email":"lqi78865@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1015 Larchwood dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48083",
      "country":"United States"
    }
  },
  {
    "id":51,
    "firstname":"Connie",
    "lastname":"Pospeshil",
    "code":"GLO-1016",
    "birthdate":"1971-04-16",
    "ssn":"382-80-7524",
    "phone":"248-767-3061",
    "email":"conniepospeshil@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"21685 Chase Drive",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48375",
      "country":"United States"
    }
  },
  {
    "id":52,
    "firstname":"Lan",
    "lastname":"Ge",
    "birthdate":"1962-10-08",
    "ssn":"384-33-1842",
    "phone":"734-740-3906",
    "email":"langeyue@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":53,
    "firstname":"Anna",
    "lastname":"Li",
    "birthdate":"1973-03-14",
    "ssn":"385-13-2932",
    "phone":"734-679-3184",
    "email":"annaligc1973@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":54,
    "firstname":"Lina",
    "lastname":"Chehadeh",
    "code":"GLO-1009",
    "birthdate":"1975-01-27",
    "ssn":"385-15-6583",
    "phone":"313-717-1845",
    "email":"Lina.khanafer@live.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"6169 Inkster Rd",
      "city":"Garden City",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48135",
      "country":"United States"
    }
  },
  {
    "id":55,
    "firstname":"Hua",
    "lastname":"Chen",
    "code":"GLO-1052",
    "birthdate":"1970-09-26",
    "ssn":"385-21-2641",
    "phone":"734-637-3447",
    "email":"hchen33@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"46861 Wareham",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48187",
      "country":"United States"
    }
  },
  {
    "id":56,
    "firstname":"Ling",
    "lastname":"Zhong",
    "birthdate":"1955-11-09",
    "ssn":"386-08-4436",
    "phone":"248-320-1436",
    "email":"zhlillian@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":57,
    "firstname":"Xianying",
    "lastname":"Xing",
    "code":"GLO-1049",
    "birthdate":"1972-02-26",
    "ssn":"386-31-9617",
    "phone":"734-846-0807",
    "email":"xing.xy@gmail.com",
    "languages":"English, Spanish, Chinese",
    "address":{
      "type":"Apartment",
      "address":"1556 N Maple Rd",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48103",
      "country":"United States"
    }
  },
  {
    "id":58,
    "firstname":"Leah",
    "lastname":"Black-Elk",
    "code":"GLO-1068",
    "birthdate":"1981-05-16",
    "ssn":"386-88-7618",
    "phone":"248-954-5227",
    "email":"msblackelk@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"5310 Wakefield Rd",
      "city":"Grand Blanc",
      "county":"Genesee",
      "state":"MI",
      "zipcode":"48439",
      "country":"United States"
    }
  },
  {
    "id":59,
    "firstname":"Dongdi",
    "lastname":"Li",
    "code":"GLO-1043",
    "birthdate":"1962-11-04",
    "ssn":"397-65-5708",
    "phone":"734-664-5669",
    "email":"lidongdi1962@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1921 Savannah Ln",
      "city":"Ypsilanti",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48198",
      "country":"United States"
    }
  },
  {
    "id":60,
    "firstname":"Mei",
    "lastname":"Xue",
    "code":"GLO-1023",
    "birthdate":"1968-02-19",
    "ssn":"401-45-2844",
    "phone":"248-767-8774",
    "email":"mxue2014@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"44489 Stone Rd",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48375",
      "country":"United States"
    }
  },
  {
    "id":61,
    "firstname":"Hanlei",
    "lastname":"Wang",
    "code":"GLO-1063",
    "birthdate":"2001-02-16",
    "ssn":"403-65-4066",
    "phone":"513-734-8551",
    "email":"hanleiwang.hlw@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"31690 Cowan Rd",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":62,
    "firstname":"Willie",
    "lastname":"Williams",
    "code":"GLO-1025",
    "birthdate":"1963-02-09",
    "ssn":"432-29-8446",
    "phone":"810-588-0517",
    "email":"williamsw19631963@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2125 Glencoe Hills Dr. Apt.#11",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48108",
      "country":"United States"
    }
  },
  {
    "id":63,
    "firstname":"Wei",
    "lastname":"Zhao",
    "code":"GLO-1033",
    "birthdate":"1971-05-07",
    "ssn":"470-35-7101",
    "phone":"248-345-4919",
    "email":"weizhao101@hotmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"44863 Revere Drive",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48377",
      "country":"United States"
    }
  },
  {
    "id":64,
    "firstname":"Qiang",
    "lastname":"Wei",
    "code":"GLO-1045",
    "birthdate":"1968-05-19",
    "ssn":"531-35-6708",
    "phone":"248-345-4019",
    "email":"weix0014@hotmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"26551 Glenwood Dr",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48374",
      "country":"United States"
    }
  },
  {
    "id":65,
    "firstname":"Hong",
    "lastname":"Zhang",
    "code":"GLO-1047",
    "birthdate":"1959-07-14",
    "ssn":"578-11-7150",
    "phone":"248-606-9696",
    "email":"hzhang996@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1819 Lexington Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48084",
      "country":"United States"
    }
  },
  {
    "id":66,
    "firstname":"jose",
    "lastname":"Irizarry",
    "code":"GLO-1046",
    "birthdate":"1998-08-10",
    "ssn":"583-47-7220",
    "phone":"313-888-1139",
    "email":"irizarryjose433@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"15351 Pembroke Avenue",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48235",
      "country":"United States"
    }
  },
  {
    "id":67,
    "firstname":"Juseline",
    "lastname":"Sainz",
    "code":"GLO-1032",
    "birthdate":"1979-10-04",
    "ssn":"583-85-1831",
    "phone":"313-800-2049",
    "email":"princessalize2010@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"15351 Pembroke Avenue",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48235",
      "country":"United States"
    }
  },
  {
    "id":68,
    "firstname":"Yongmei",
    "lastname":"Liang",
    "code":"GLO-1058",
    "birthdate":"1971-04-08",
    "ssn":"598-39-8409",
    "phone":"248-825-0652",
    "email":"459634669@qq.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"3019 Longview Ave",
      "city":"Rochester",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48307",
      "country":"United States"
    }
  },
  {
    "id":69,
    "firstname":"Tak Sun",
    "lastname":"Chung",
    "code":"GLO-1011",
    "birthdate":"1964-09-30",
    "ssn":"602-30-1262",
    "phone":"248-376-9223",
    "phone2":"248-250-1942",
    "email":"taksunchung66@gmail.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"66 Stalwart Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48098",
      "country":"United States"
    }
  },
  {
    "id":70,
    "firstname":"JuanJuan",
    "lastname":"zhu",
    "code":"GLO-1042",
    "birthdate":"1960-01-02",
    "ssn":"613-35-7846",
    "email":"zjj48071@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"26640 Couzens Avenu",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country":"United States"
    }
  },
  {
    "id":71,
    "firstname":"Gergana",
    "lastname":"Kodjebacheva",
    "birthdate":"1969-07-06",
    "ssn":"618-06-7882",
    "phone":"626-375-9205",
    "email":"gergana@umich.edu",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":72,
    "firstname":"Xiao Xia",
    "lastname":"Chen",
    "code":"GLO-1066",
    "birthdate":"1984-06-22",
    "ssn":"641-54-3383",
    "phone":"586-663-6620",
    "email":"xchen168138@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"39816 Dorian Dr",
      "city":"Sterling Heights",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48310",
      "country":"United States"
    }
  },
  {
    "id":73,
    "firstname":"Luping",
    "lastname":"Liang",
    "birthdate":"1962-11-06",
    "ssn":"655-79-5547",
    "phone":"248-804-3227",
    "email":"liupingliang83@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":74,
    "firstname":"Zhiwei",
    "lastname":"Yan",
    "code":"GLO-1064",
    "birthdate":"1980-08-03",
    "ssn":"683-53-3067",
    "phone":"734-678-7008",
    "email":"david800803@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"31610 Eagle Ct",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":75,
    "firstname":"Yuanqu",
    "lastname":"Chen",
    "code":"GLO-1054",
    "birthdate":"1964-01-10",
    "ssn":"696-45-5717",
    "phone":"734-666-8088",
    "email":"1906442418@qq.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2448 Nixon Rd",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":76,
    "firstname":"Iryna",
    "lastname":"Vasiuk",
    "code":"GLO-1061",
    "birthdate":"1980-10-05",
    "ssn":"718-63-9369",
    "phone":"248-949-6006",
    "email":"irina.vasiuk@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"11729 Spicer Dr",
      "city":"Plymouth",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48170",
      "country":"United States"
    }
  },
  {
    "id":77,
    "firstname":"Mona",
    "lastname":"Awada",
    "code":"GLO-1069",
    "birthdate":"1966-08-15",
    "ssn":"729-16-4413",
    "phone":"313-717-2484",
    "email":"rawanlakis@icloud.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"25839 Midway sreet",
      "city":"Dearborn Heights",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48127",
      "country":"United States"
    }
  },
  {
    "id":78,
    "firstname":"Keman",
    "lastname":"Li",
    "code":"GLO-1074",
    "birthdate":"1977-12-04",
    "ssn":"739-03-6932",
    "phone":"734-447-6049",
    "email":"kemanli2014@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"387 Robyn",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48187",
      "country":"United States"
    }
  },
  {
    "id":79,
    "firstname":"Inna",
    "lastname":"Tikan",
    "code":"GLO-1036",
    "birthdate":"1970-09-30",
    "ssn":"741-43-1130",
    "phone":"248-425-3970",
    "email":"innaukr@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"4294 15 mile road",
      "city":"Sterling Heights",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48310",
      "country":"United States"
    }
  },
  {
    "id":80,
    "firstname":"Svitlana",
    "lastname":"Nakonechna",
    "code":"GLO-1053",
    "birthdate":"1991-04-13",
    "ssn":"748-22-3421",
    "phone":"248-678-2299",
    "email":"vladimiswitas305@gmail.com",
    "languages":"English, Spanish, Russian",
    "address":{
      "type":"Apartment",
      "address":"30070 W. 12 Mile Rd #128",
      "city":"Farmington Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48334",
      "country":"United States"
    }
  },
  {
    "id":81,
    "firstname":"Yaqun",
    "lastname":"Zhu",
    "code":"GLO-1022",
    "birthdate":"1960-09-17",
    "ssn":"762-18-8063",
    "phone":"313-478-2566",
    "email":"yaqun17@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"255 S Vernon St",
      "city":"Dearborn",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48124",
      "country":"United States"
    }
  },
  {
    "id":82,
    "firstname":"Alla",
    "lastname":"Boliukh",
    "code":"GLO-1067",
    "birthdate":"1980-04-19",
    "ssn":"791-43-3215",
    "phone":"517-302-7053",
    "email":"bolykalla@ukr.net",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"11092 N Beck Rd",
      "city":"Plymouth",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48170",
      "country":"United States"
    }
  },
  {
    "id":83,
    "firstname":"Hector",
    "lastname":"Salinas",
    "code":"GLO-1048",
    "birthdate":"1976-12-16",
    "ssn":"791-83-6589",
    "phone":"248-679-2601",
    "email":"hectorsalpen@gmail.com",
    "languages":"English, Spanish, Italian, Portugese, Mayan, Nahuatl",
    "address":{
      "type":"Apartment",
      "address":"7677 Maple Dr",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":84,
    "firstname":"Xia",
    "lastname":"Zhang",
    "code":"GLO-1062",
    "birthdate":"1965-07-16",
    "ssn":"817-14-2398",
    "phone":"734-546-4566",
    "email":"xzhang7@wccnet.edu",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2747 Barklay Way",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":85,
    "firstname":"Jun",
    "lastname":"Ruan",
    "code":"GLO-1057",
    "birthdate":"1976-01-21",
    "ssn":"842-28-7248",
    "phone":"586-344-4259",
    "email":"rj107521186@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"29252 Tessmer Ct",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country":"United States"
    }
  },
  {
    "id":86,
    "firstname":"Qingbo",
    "lastname":"Yang",
    "code":"GLO-1027",
    "birthdate":"1966-02-11",
    "ssn":"856-45-5177",
    "phone":"313-806-3612",
    "email":"yangqingbo5@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"255 S Vernon",
      "city":"Dearborn",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48124",
      "country":"United States"
    }
  },
  {
    "id":87,
    "firstname":"Hong",
    "lastname":"Hu",
    "code":"GLO-1070",
    "birthdate":"1967-05-19",
    "ssn":"878-33-2891",
    "phone":"734-800-6188",
    "email":"191023092@qq.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2660 S Knightsbridge Cir",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":88,
    "firstname":"Jiangchen",
    "lastname":"Chen",
    "code":"GLO-1060",
    "birthdate":"1970-05-18",
    "ssn":"897-02-3215",
    "phone":"734-666-8382",
    "email":"jcchen0518@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2448 Nixon Rd",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  }
]

###
# group: Backup Recovery
# @name Add Bulk Patients
POST {{maxmila.baseUrl}}/bulk/patients
Content-Type: application/json

[
  {
    "patient":"0001982402",
    "admission":"GLO-900102",
    "firstname":"Charles",
    "middlename":"Leonard",
    "lastname":"Jackson",
    "phone":"734-846-0490",
    "address":{
      "type":"Home",
      "address":"2970 Easy St",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48104",
      "country": "United States",
      "latitude":42.2455487,
      "longitude":-83.70863593
    }
  },
  {
    "patient":"0003428549",
    "admission":"GLO-900085",
    "firstname":"Yanan",
    "middlename":null,
    "lastname":"Guo",
    "phone":"734-662-8047",
    "address":{
      "type":"Home",
      "address":"2305 Sandalwood Cir Apt 300C",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30687246,
      "longitude":-83.70959265
    }
  },
  {
    "patient":"0006627841",
    "admission":"GLO-900003",
    "firstname":"Moussa",
    "middlename":"Mohamad Al",
    "lastname":"Khanafer",
    "phone":"313-736-8888",
    "address":{
      "type":"Home",
      "address":"27359 Terrell St",
      "city":"Dearborn Heights",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48127",
      "country": "United States",
      "latitude":42.32850971,
      "longitude":-83.31036677
    }
  },
  {
    "patient":"0008276084",
    "admission":"GLO-900088",
    "firstname":"Fengxiu",
    "middlename":null,
    "lastname":"Huo",
    "phone":"248-320-1436",
    "address":{
      "type":"Home",
      "address":"32900 Grand Riv Apt 219",
      "city":"Farmington Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country": "United States",
      "latitude":42.46433472,
      "longitude":-83.37127143
    }
  },
  {
    "patient":"0008276093",
    "admission":"GLO-900089",
    "firstname":"Dazhang",
    "middlename":null,
    "lastname":"Zhong",
    "phone":"248-320-1436",
    "address":{
      "type":"Home",
      "address":"32900 Grand Riv Apt 219",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country": "United States",
      "latitude":42.46429536,
      "longitude":-83.37130981
    }
  },
  {
    "patient":"0009524024",
    "admission":"GLO-900020",
    "firstname":"Julie",
    "middlename":"Lynn",
    "lastname":"Rakowski",
    "phone":"313-879-8457",
    "address":{
      "type":"Home",
      "address":"20746 Mary St",
      "city":"Taylor",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48180",
      "country": "United States",
      "latitude":42.24369639,
      "longitude":-83.23908354
    }
  },
  {
    "patient":"0009561331",
    "admission":"GLO-900017",
    "firstname":"Manhua",
    "middlename":null,
    "lastname":"Huang",
    "phone":"248-225-3933",
    "address":{
      "type":"Home",
      "address":"5267 Church Hill Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48085",
      "country": "United States",
      "latitude":42.59662703,
      "longitude":-83.1241171
    }
  },
  {
    "patient":"0012441264",
    "admission":"GLO-900075",
    "firstname":"Yurong",
    "middlename":null,
    "lastname":"Zhao",
    "phone":"248-449-8687",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 420",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34229606,
      "longitude":-83.39545321
    }
  },
  {
    "patient":"0013498083",
    "admission":"GLO-900065",
    "firstname":"Renwu",
    "middlename":null,
    "lastname":"Yang",
    "phone":"734-994-3347",
    "address":{
      "type":"Home",
      "address":"32900 Grand River Ave Apt 423",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country": "United States",
      "latitude":42.4641298,
      "longitude":-83.37131484
    }
  },
  {
    "patient":"0013641447",
    "admission":"GLO-900057",
    "firstname":"Shan",
    "middlename":"He",
    "lastname":"Yuan",
    "phone":"248-974-5933",
    "address":{
      "type":"Home",
      "address":"32900 Grand River Ave Apt 525",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country": "United States",
      "latitude":42.46408145,
      "longitude":-83.37140611
    }
  },
  {
    "patient":"0013730046",
    "admission":"GLO-900082",
    "firstname":"Mariuca",
    "middlename":null,
    "lastname":"Neagu",
    "phone":"734-358-8860",
    "address":{
      "type":"Home",
      "address":"36500 Marquette St Apt 404",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.31754573,
      "longitude":-83.40044544
    }
  },
  {
    "patient":"0015315299",
    "admission":"GLO-900066",
    "firstname":"Mahdie",
    "middlename":"Farouk",
    "lastname":"Ibrahim",
    "phone":"734-512-6322",
    "address":{
      "type":"No Home",
      "address":"23600 Gibraltar Rd",
      "city":"Flat Rock",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48134",
      "country": "United States",
      "latitude":42.09548504,
      "longitude":-83.26138612
    }
  },
  {
    "patient":"0017635082",
    "admission":"GLO-900054",
    "firstname":"Qiu",
    "middlename":"Yun",
    "lastname":"Jiang",
    "phone":"248-836-8859",
    "address":{
      "type":"Home",
      "address":"2301 Sandalwood Cir Apt 305A",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30676635,
      "longitude":-83.70863807
    }
  },
  {
    "patient":"0018134663",
    "admission":"GLO-900030",
    "firstname":"Lingxian",
    "middlename":null,
    "lastname":"Xu",
    "phone":"734-466-9025",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 604",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34228336,
      "longitude":-83.39597904
    }
  },
  {
    "patient":"0022452691",
    "admission":"GLO-900086",
    "firstname":"Yi Jing",
    "middlename":null,
    "lastname":"Li",
    "phone":"734-272-1767",
    "address":{
      "type":"Home",
      "address":"2901 Northbrook Pl Apt 501",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48103",
      "country": "United States",
      "latitude":42.24533543,
      "longitude":-83.75515698
    }
  },
  {
    "patient":"0022966147",
    "admission":"GLO-900106",
    "firstname":"Gita",
    "middlename":"Naumovna",
    "lastname":"Leykina",
    "phone":"734-327-3787",
    "address":{
      "type":"Home",
      "address":"2901 Northbrook Pl Apt 623",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48103",
      "country": "United States",
      "latitude":42.24534219,
      "longitude":-83.75498361
    }
  },
  {
    "patient":"0024228746",
    "admission":"GLO-900081",
    "firstname":"Pingjuan",
    "middlename":null,
    "lastname":"Yang",
    "phone":"248-767-8774",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 810",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34232131,
      "longitude":-83.39582057
    }
  },
  {
    "patient":"0024228755",
    "admission":"GLO-900005",
    "firstname":"Zhiming",
    "middlename":null,
    "lastname":"Gu",
    "phone":"248-767-8774",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 810",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34230545,
      "longitude":-83.39546652
    }
  },
  {
    "patient":"0024875435",
    "admission":"GLO-900022",
    "firstname":"In John",
    "middlename":null,
    "lastname":"Park",
    "phone":"248-719-8161",
    "address":{
      "type":"Home",
      "address":"3712 Williams St Apt 116",
      "city":"Wayne",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48184",
      "country": "United States",
      "latitude":42.28133891,
      "longitude":-83.39300164
    }
  },
  {
    "patient":"0026713010",
    "admission":"GLO-900049",
    "firstname":"Julia",
    "middlename":"Margaret",
    "lastname":"Gardner",
    "phone":"734-620-4384",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 1120",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34238262,
      "longitude":-83.39544322
    }
  },
  {
    "patient":"0026713039",
    "admission":"GLO-900026",
    "firstname":"Alisa",
    "middlename":null,
    "lastname":"Gardner",
    "phone":"734-730-2751",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 501",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34227376,
      "longitude":-83.39582325
    }
  },
  {
    "patient":"0026994515",
    "admission":"GLO-900041",
    "firstname":"Wing",
    "middlename":"Yin",
    "lastname":"Wong",
    "phone":"248-767-3061",
    "address":{
      "type":"Home",
      "address":"29427 Orangelawn St",
      "city":"Livonia",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48150",
      "country": "United States",
      "latitude":42.36498924,
      "longitude":-83.33341043
    }
  },
  {
    "patient":"0027932320",
    "admission":"GLO-900052",
    "firstname":"Jingming",
    "middlename":null,
    "lastname":"Fan",
    "phone":"248-703-8549",
    "address":{
      "type":"Home",
      "address":"500 E Irving Ave Apt 420",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country": "United States",
      "latitude":42.52222118,
      "longitude":-83.1026089
    }
  },
  {
    "patient":"0028382379",
    "admission":"GLO-900025",
    "firstname":"Zhong Rong",
    "middlename":null,
    "lastname":"Huang",
    "phone":"248-379-0075",
    "address":{
      "type":"Home",
      "address":"6129 Smithfield Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48085",
      "country": "United States",
      "latitude":42.6093641,
      "longitude":-83.10964263
    }
  },
  {
    "patient":"0028382388",
    "admission":"GLO-900071",
    "firstname":"Qiu Ying",
    "middlename":null,
    "lastname":"Mei",
    "phone":"248-379-0075",
    "address":{
      "type":"Home",
      "address":"6129 Smithfield Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48085",
      "country": "United States",
      "latitude":42.60924543,
      "longitude":-83.10959544
    }
  },
  {
    "patient":"0028711781",
    "admission":"GLO-900077",
    "firstname":"Li",
    "middlename":null,
    "lastname":"Jiang",
    "phone":"248-719-1656",
    "address":{
      "type":"Home",
      "address":"32900 Grand River Avenue Apt 305",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country": "United States",
      "latitude":42.46413682,
      "longitude":-83.37129291
    }
  },
  {
    "patient":"0029722832",
    "admission":"GLO-900063",
    "firstname":"Youbao",
    "middlename":null,
    "lastname":"Fu",
    "phone":"248-797-4579",
    "address":{
      "type":"Home",
      "address":"930 John R Rd Apt 21006",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48083",
      "country": "United States",
      "latitude":42.54471795,
      "longitude":-83.104481
    }
  },
  {
    "patient":"0029722841",
    "admission":"GLO-900073",
    "firstname":"Qianru",
    "middlename":null,
    "lastname":"Ye",
    "phone":"248-797-4579",
    "address":{
      "type":"Home",
      "address":"930 John R Rd Apt 21006",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48083",
      "country": "United States",
      "latitude":42.54473286,
      "longitude":-83.10445537
    }
  },
  {
    "patient":"0030899581",
    "admission":"GLO-900046",
    "firstname":"Lynn",
    "middlename":"M",
    "lastname":"Landry",
    "phone":"810-428-5348",
    "address":{
      "type":"Home",
      "address":"606 S Williams St Apt 501",
      "city":"Royal Oak",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48067",
      "country": "United States",
      "latitude":42.48518931,
      "longitude":-83.14322048
    }
  },
  {
    "patient":"0031114057",
    "admission":"GLO-900028",
    "firstname":"Huili",
    "middlename":null,
    "lastname":"Ren",
    "phone":"734-245-2103",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 218",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34234475,
      "longitude":-83.39573032
    }
  },
  {
    "patient":"0031951519",
    "admission":"GLO-900099",
    "firstname":"Huiying",
    "middlename":null,
    "lastname":"Xi",
    "phone":"734-358-5423",
    "address":{
      "type":"Home",
      "address":"2305 Sandalwood Cir Apt 316C",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30686453,
      "longitude":-83.70934588
    }
  },
  {
    "patient":"0032324335",
    "admission":"GLO-900069",
    "firstname":"Lyudmila",
    "middlename":null,
    "lastname":"Dyatlova",
    "phone":"248-595-7003",
    "address":{
      "type":"Home",
      "address":"15106 W 10 Mile Rd Apt 297",
      "city":"Oak Park",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48237",
      "country": "United States",
      "latitude":42.47527772,
      "longitude":-83.1952076
    }
  },
  {
    "patient":"0032454241",
    "admission":"GLO-900009",
    "firstname":"Zhonghui",
    "middlename":null,
    "lastname":"Zhou",
    "phone":"248-345-4919",
    "address":{
      "type":"Home",
      "address":"2901 Northbrook Pl Apt 625",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48103",
      "country": "United States",
      "latitude":42.24551903,
      "longitude":-83.75499911
    }
  },
  {
    "patient":"0032727311",
    "admission":"GLO-900101",
    "firstname":"Xiuying",
    "middlename":null,
    "lastname":"Chen",
    "phone":"248-229-8739",
    "address":{
      "type":"Home",
      "address":"2307 Sandalwood Cir Apt 204D",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30665892,
      "longitude":-83.70873785
    }
  },
  {
    "patient":"0034362381",
    "admission":"GLO-900001",
    "firstname":"Jianlin",
    "middlename":null,
    "lastname":"Zhou",
    "phone":"734-276-0011",
    "address":{
      "type":"Home",
      "address":"2305 Sandalwood Cir Apt 306C",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30661477,
      "longitude":-83.70938344
    }
  },
  {
    "patient":"0034455524",
    "admission":"GLO-900068",
    "firstname":"Huizhi",
    "middlename":null,
    "lastname":"He",
    "phone":"734-846-2617",
    "address":{
      "type":"Home",
      "address":"2305 Sandalwood Cir Apt 200C",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30673431,
      "longitude":-83.70949413
    }
  },
  {
    "patient":"0035470328",
    "admission":"GLO-900034",
    "firstname":"Thomas",
    "middlename":"Wade",
    "lastname":"Humphrey",
    "phone":"231-855-3313",
    "address":{
      "type":"Home",
      "address":"22228 N Brandon",
      "city":"Farmington Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country": "United States",
      "latitude":42.45538854,
      "longitude":-83.32310553
    }
  },
  {
    "patient":"0036297227",
    "admission":"GLO-900104",
    "firstname":"Fengliao",
    "middlename":null,
    "lastname":"Chen",
    "phone":"734-206-1808",
    "address":{
      "type":"Home",
      "address":"2301 Sandalwood Cir Apt 209A",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30652635,
      "longitude":-83.70839398
    }
  },
  {
    "patient":"0038743733",
    "admission":"GLO-900021",
    "firstname":"Guoguang",
    "middlename":null,
    "lastname":"Hu",
    "phone":"810-602-8254",
    "address":{
      "type":"No Home",
      "address":"17555 N Laurel Park Dr Apt 407",
      "city":"Livonia",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48152",
      "country": "United States",
      "latitude":42.41356731,
      "longitude":-83.42063268
    }
  },
  {
    "patient":"0039806499",
    "admission":"GLO-900016",
    "firstname":"Yongchen",
    "middlename":null,
    "lastname":"Tian",
    "phone":"248-755-3921",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 1108",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34222349,
      "longitude":-83.39588843
    }
  },
  {
    "patient":"0040056435",
    "admission":"GLO-900097",
    "firstname":"Shengjiao",
    "middlename":null,
    "lastname":"Ruan",
    "phone":"586-218-3241",
    "address":{
      "type":"Home",
      "address":"930 John R Rd Apt 2220",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48083",
      "country": "United States",
      "latitude":42.54452776,
      "longitude":-83.10457219
    }
  },
  {
    "patient":"0040834128",
    "admission":"GLO-900072",
    "firstname":"Lijuan",
    "middlename":null,
    "lastname":"Wang",
    "phone":"248-579-0717",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34200799,
      "longitude":-83.3953357
    }
  },
  {
    "patient":"0041488909",
    "admission":"GLO-900047",
    "firstname":"Jianrong",
    "middlename":null,
    "lastname":"Kuang",
    "phone":"248-376-9223",
    "address":{
      "type":"Home",
      "address":"518 W Fairmount Ave",
      "city":"Pontiac",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48340",
      "country": "United States",
      "latitude":42.66891618,
      "longitude":-83.31697237
    }
  },
  {
    "patient":"0042053362",
    "admission":"GLO-900019",
    "firstname":"Tommy",
    "middlename":"Koon-Lim",
    "lastname":"Ng",
    "phone":"248-238-6674",
    "address":{
      "type":"Home",
      "address":"31101 Edward Ave Apt 710",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country": "United States",
      "latitude":42.5094323,
      "longitude":-83.10095993
    }
  },
  {
    "patient":"0045862434",
    "admission":"GLO-900096",
    "firstname":"Tsipora",
    "middlename":null,
    "lastname":"Gormezano",
    "phone":"347-579-4854",
    "address":{
      "type":"Home",
      "address":"15106 W 10 Mile Rd Apt 288",
      "city":"Oak Park",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48237",
      "country": "United States",
      "latitude":42.47528564,
      "longitude":-83.19521833
    }
  },
  {
    "patient":"0046803993",
    "admission":"GLO-900004",
    "firstname":"John",
    "middlename":"Thomas",
    "lastname":"Kuchinski",
    "phone":"517-944-5039",
    "address":{
      "type":"No Home",
      "address":"2651 International Dr Apt 1403A",
      "city":"Ypsilanti",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48197",
      "country": "United States",
      "latitude":42.25264685,
      "longitude":-83.6548007
    }
  },
  {
    "patient":"0062394541",
    "admission":"GLO-900002",
    "firstname":"Mustapha",
    "middlename":"Mohammed",
    "lastname":"Fadlallah",
    "phone":"313-729-4444",
    "address":{
      "type":"Home",
      "address":"5810 N Charlesworth St",
      "city":"Dearborn Heights",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48127",
      "country": "United States",
      "latitude":42.32872644,
      "longitude":-83.30343953
    }
  },
  {
    "patient":"0069270484",
    "admission":"GLO-900080",
    "firstname":"Nayfe",
    "middlename":"Mustapha",
    "lastname":"Fadlallah",
    "phone":"313-729-4444",
    "address":{
      "type":"Home",
      "address":"5810 N Charlesworth St",
      "city":"Dearborn Heights",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48127",
      "country": "United States",
      "latitude":42.32872644,
      "longitude":-83.30343953
    }
  },
  {
    "patient":"0073964445",
    "admission":"GLO-900062",
    "firstname":"Mark",
    "middlename":"A",
    "lastname":"Rakowski",
    "phone":"313-879-8457",
    "address":{
      "type":"Home",
      "address":"20746 Mary St",
      "city":"Taylor",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48180",
      "country": "United States",
      "latitude":42.2437192,
      "longitude":-83.23915998
    }
  },
  {
    "patient":"0075656179",
    "admission":"GLO-900053",
    "firstname":"Houda",
    "middlename":"Fadel",
    "lastname":"Khalil",
    "phone":"313-945-1961",
    "address":{
      "type":"Home",
      "address":"7019 Kingsley St",
      "city":"Dearborn",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48126",
      "country": "United States",
      "latitude":42.34307317,
      "longitude":-83.16105555
    }
  },
  {
    "patient":"0077388667",
    "admission":"GLO-900064",
    "firstname":"Lidia",
    "middlename":null,
    "lastname":"Bercea",
    "phone":"313-909-2665",
    "address":{
      "type":"Home",
      "address":"45722 Prairiegrass Ct Apt 3",
      "city":"Van Buren Twp",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48111",
      "country": "United States",
      "latitude":42.2329559,
      "longitude":-83.49029919
    }
  },
  {
    "patient":"0086531388",
    "admission":"GLO-900008",
    "firstname":"Natasha",
    "middlename":"Helen",
    "lastname":"Franke",
    "phone":"734-483-0397",
    "address":{
      "type":"Home",
      "address":"107 Perrin St",
      "city":"Ypsilanti",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48197",
      "country": "United States",
      "latitude":42.24276548,
      "longitude":-83.62070896
    }
  },
  {
    "patient":"0086628771",
    "admission":"GLO-900023",
    "firstname":"Intisar",
    "middlename":"M",
    "lastname":"Khanafer",
    "phone":"313-736-8888",
    "address":{
      "type":"Home",
      "address":"27359 Terrell St",
      "city":"Dearborn Heights",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48127",
      "country": "United States",
      "latitude":42.32852248,
      "longitude":-83.31036572
    }
  },
  {
    "patient":"0086669602",
    "admission":"GLO-900006",
    "firstname":"Doroteya",
    "middlename":null,
    "lastname":"Tiraspolsky",
    "phone":"248-968-3653",
    "address":{
      "type":"Home",
      "address":"15106 W 10 Mile Rd Apt 382",
      "city":"Oak Park",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48237",
      "country": "United States",
      "latitude":42.4750783,
      "longitude":-83.19511546
    }
  },
  {
    "patient":"0086834125",
    "admission":"GLO-900112",
    "firstname":"Fatima",
    "middlename":null,
    "lastname":"Hamad",
    "phone":"313-415-9229",
    "address":{
      "type":"Home",
      "address":"6966 N Beech Daly Rd",
      "city":"Dearborn Heights",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48127",
      "country": "United States",
      "latitude":42.33924458,
      "longitude":-83.29231658
    }
  },
  {
    "patient":"0088084131",
    "admission":"GLO-900076",
    "firstname":"Weiwen",
    "middlename":null,
    "lastname":"Ding",
    "phone":"248-588-4977",
    "address":{
      "type":"Home",
      "address":"930 John R Rd Apt 2806",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48083",
      "country": "United States",
      "latitude":42.54440897,
      "longitude":-83.10462581
    }
  },
  {
    "patient":"0088981545",
    "admission":"GLO-900051",
    "firstname":"Xiu-Lian",
    "middlename":null,
    "lastname":"Tong",
    "phone":"734-525-1282",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 910",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34222826,
      "longitude":-83.39530591
    }
  },
  {
    "patient":"0089038488",
    "admission":"GLO-900040",
    "firstname":"Cai",
    "middlename":"Fang",
    "lastname":"Li Lin",
    "phone":"734-762-6587",
    "address":{
      "type":"Home",
      "address":"32585 Kathryn St",
      "city":"Garden City",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48135",
      "country": "United States",
      "latitude":42.3121131,
      "longitude":-83.36250197
    }
  },
  {
    "patient":"0089058300",
    "admission":"GLO-900012",
    "firstname":"Qi",
    "middlename":"Sheng",
    "lastname":"Tan",
    "phone":"248-252-7553",
    "address":{
      "type":"Home",
      "address":"32900 Grand River Ave Apt 521",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country": "United States",
      "latitude":42.4639925,
      "longitude":-83.37125289
    }
  },
  {
    "patient":"0089058506",
    "admission":"GLO-900078",
    "firstname":"Hongzhong",
    "middlename":null,
    "lastname":"Gao",
    "phone":"248-252-7553",
    "address":{
      "type":"Home",
      "address":"32900 Grand River Ave Apt 521",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country": "United States",
      "latitude":42.46431889,
      "longitude":-83.3712607
    }
  },
  {
    "patient":"0089069690",
    "admission":"GLO-900083",
    "firstname":"Hao",
    "middlename":"Guang",
    "lastname":"Li",
    "phone":"734-762-6587",
    "address":{
      "type":"Home",
      "address":"32585 Kathryn St",
      "city":"Garden City",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48135",
      "country": "United States",
      "latitude":42.31210665,
      "longitude":-83.36253885
    }
  },
  {
    "patient":"0089101401",
    "admission":"GLO-900067",
    "firstname":"Mohini",
    "middlename":null,
    "lastname":"Bhatia",
    "phone":"248-946-7927",
    "address":{
      "type":"Home",
      "address":"34462 W 9 Mile Rd",
      "city":"Farmington Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48335",
      "country": "United States",
      "latitude":42.4558864,
      "longitude":-83.38646402
    }
  },
  {
    "patient":"0089146977",
    "admission":"GLO-900015",
    "firstname":"Yi",
    "middlename":"Sheng",
    "lastname":"Li",
    "phone":"734-778-5408",
    "address":{
      "type":"Home",
      "address":"2307 Sandlewood Cir Apt 212D",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30662775,
      "longitude":-83.70865621
    }
  },
  {
    "patient":"0093984866",
    "admission":"GLO-900058",
    "firstname":"Xian Fang",
    "middlename":null,
    "lastname":"Xu",
    "phone":"734-773-9677",
    "address":{
      "type":"Home",
      "address":"2305 Sandalwood Cir Apt 309C",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30665029,
      "longitude":-83.7093888
    }
  },
  {
    "patient":"0096838422",
    "admission":"GLO-900039",
    "firstname":"Pamela",
    "middlename":"Marie",
    "lastname":"Voorhees",
    "phone":"248-722-0042",
    "address":{
      "type":"Home",
      "address":"2604 Ardmore",
      "city":"Royal Oak",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48073",
      "country": "United States",
      "latitude":42.51303062,
      "longitude":-83.13679611
    }
  },
  {
    "patient":"0098477571",
    "admission":"GLO-900109",
    "firstname":"Rhonee",
    "middlename":"M",
    "lastname":"Williams",
    "phone":"248-797-4456",
    "address":{
      "type":"Home",
      "address":"287 S Marshall St",
      "city":"Pontiac",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48342",
      "country": "United States",
      "latitude":42.63020686,
      "longitude":-83.2695997
    }
  },
  {
    "patient":"1006018004",
    "admission":"GLO-900070",
    "firstname":"Qihong",
    "middlename":null,
    "lastname":"Zheng",
    "phone":"248-494-2636",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 820",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34221825,
      "longitude":-83.39573473
    }
  },
  {
    "patient":"1010862639",
    "admission":"GLO-900110",
    "firstname":"Huiwen",
    "middlename":null,
    "lastname":"Hao",
    "phone":"248-385-6801",
    "address":{
      "type":"Home",
      "address":"500 E Irving Ave Apt 524",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country": "United States",
      "latitude":42.52225281,
      "longitude":-83.1026089
    }
  },
  {
    "patient":"1010864894",
    "admission":"GLO-900111",
    "firstname":"Yamei",
    "middlename":null,
    "lastname":"Hu",
    "phone":"248-385-6801",
    "address":{
      "type":"Home",
      "address":"500 E Irving Ave Apt 524",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country": "United States",
      "latitude":42.52222909,
      "longitude":-83.10255526
    }
  },
  {
    "patient":"1020534453",
    "admission":"GLO-900056",
    "firstname":"Anlin",
    "middlename":null,
    "lastname":"Ge",
    "phone":"734-674-8734",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 709",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34211714,
      "longitude":-83.39532704
    }
  },
  {
    "patient":"1021683609",
    "admission":"GLO-900114",
    "firstname":"Xiaozeng",
    "middlename":null,
    "lastname":"Chen",
    "phone":"734-846-1442",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 317",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34221178,
      "longitude":-83.39549763
    }
  },
  {
    "patient":"1021683734",
    "admission":"GLO-900113",
    "firstname":"Chunqin",
    "middlename":null,
    "lastname":"Liu",
    "phone":"734-846-1442",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 317",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34222169,
      "longitude":-83.3954122
    }
  },
  {
    "patient":"1024238697",
    "admission":"GLO-900024",
    "firstname":"Weiping",
    "middlename":null,
    "lastname":"Luan",
    "phone":"734-657-5206",
    "address":{
      "type":"Home",
      "address":"2305 Sandalwood Cir Apt 200C",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30682761,
      "longitude":-83.70943598
    }
  },
  {
    "patient":"1035513271",
    "admission":"GLO-900036",
    "firstname":"Chuwei",
    "middlename":null,
    "lastname":"Wu",
    "phone":"248-470-3581",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 1105",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34240664,
      "longitude":-83.3955875
    }
  },
  {
    "patient":"1035513567",
    "admission":"GLO-900042",
    "firstname":"Jinbao",
    "middlename":null,
    "lastname":"Qian",
    "phone":"248-470-3581",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 1105",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34222097,
      "longitude":-83.39531828
    }
  },
  {
    "patient":"1061932084",
    "admission":"GLO-900033",
    "firstname":"Lingda",
    "middlename":null,
    "lastname":"Kong",
    "phone":"734-582-3654",
    "address":{
      "type":"Home",
      "address":"2563 Sandalwood Cir Apt B",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30890336,
      "longitude":-83.7086206
    }
  },
  {
    "patient":"1061934777",
    "admission":"GLO-900014",
    "firstname":"Xinzhen",
    "middlename":null,
    "lastname":"Xie",
    "phone":"734-582-3654",
    "address":{
      "type":"Home",
      "address":"2563 Sandalwood Cir Apt B",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.3088501,
      "longitude":-83.70856927
    }
  },
  {
    "patient":"1062595686",
    "admission":"GLO-900013",
    "firstname":"Liubovi",
    "middlename":null,
    "lastname":"Pojidaeva",
    "phone":"248-305-0865",
    "address":{
      "type":"No Home",
      "address":"1035 Walled Lake Villa Dr Apt 524",
      "city":"Walled Lake",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48390",
      "country": "United States",
      "latitude":42.52663757,
      "longitude":-83.49335332
    }
  },
  {
    "patient":"1066139502",
    "admission":"GLO-900048",
    "firstname":"Xijing",
    "middlename":null,
    "lastname":"Guo",
    "phone":"734-306-7020",
    "address":{
      "type":"Home",
      "address":"2307 Sandalwood Cir Apt 210D",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.3066114,
      "longitude":-83.70851967
    }
  },
  {
    "patient":"1068222878",
    "admission":"GLO-900100",
    "firstname":"Shaoyan",
    "middlename":null,
    "lastname":"Xi",
    "phone":"248-229-8739",
    "address":{
      "type":"Home",
      "address":"2307 Sandalwood Cir Apt 204D",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30654543,
      "longitude":-83.70857657
    }
  },
  {
    "patient":"1072443015",
    "admission":"GLO-900107",
    "firstname":"Xirong",
    "middlename":null,
    "lastname":"Chen",
    "phone":"586-258-1056",
    "address":{
      "type":"Home",
      "address":"39828 Dorian Dr",
      "city":"Sterling Hts",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48310",
      "country": "United States",
      "latitude":42.58473039,
      "longitude":-83.08378124
    }
  },
  {
    "patient":"1075509086",
    "admission":"GLO-900032",
    "firstname":"Galina",
    "middlename":null,
    "lastname":"Shein",
    "phone":"630-730-1710",
    "address":{
      "type":"Home",
      "address":"44505 Ford Rd Apt 501",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48187",
      "country": "United States",
      "latitude":42.32113208,
      "longitude":-83.4796068
    }
  },
  {
    "patient":"1085533693",
    "admission":"GLO-900031",
    "firstname":"Jiazhen",
    "middlename":null,
    "lastname":"Li",
    "phone":"219-229-4597",
    "address":{
      "type":"Home",
      "address":"7600 Nankin Ct Apt 1002",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country": "United States",
      "latitude":42.34212712,
      "longitude":-83.39544516
    }
  },
  {
    "patient":"1104734402",
    "admission":"GLO-900105",
    "firstname":"Jingru",
    "middlename":null,
    "lastname":"Tao",
    "phone":"734-223-2370",
    "address":{
      "type":"Home",
      "address":"2301 Sandalwood Cir Apt 209A",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30675048,
      "longitude":-83.70859515
    }
  },
  {
    "patient":"1105634457",
    "admission":"GLO-900050",
    "firstname":"Vladimir",
    "middlename":"Matveevich",
    "lastname":"Zhitkov",
    "phone":"248-866-2468",
    "address":{
      "type":"No Home",
      "address":"1035 Walled Lake Villa Dr Apt 526",
      "city":"Walled Lake",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48390",
      "country": "United States",
      "latitude":42.52689481,
      "longitude":-83.49327555
    }
  },
  {
    "patient":"1105995118",
    "admission":"GLO-900055",
    "firstname":"Elvira",
    "middlename":"A",
    "lastname":"Mitroshina",
    "phone":"734-245-2040",
    "address":{
      "type":"Home",
      "address":"44833 Ann Arbor Rd Apt 310",
      "city":"Plymouth",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48170",
      "country": "United States",
      "latitude":42.35748826,
      "longitude":-83.48387972
    }
  },
  {
    "patient":"1106418528",
    "admission":"GLO-900059",
    "firstname":"Luan",
    "middlename":null,
    "lastname":"Qu",
    "phone":"248-345-4919",
    "address":{
      "type":"Home",
      "address":"2301 Sandalwood Cir Apt 211",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30658736,
      "longitude":-83.70838488
    }
  },
  {
    "patient":"1111684605",
    "admission":"GLO-900045",
    "firstname":"Zhaohui",
    "middlename":null,
    "lastname":"Liu",
    "phone":"248-342-8039",
    "address":{
      "type":"Home",
      "address":"2566 Walton Blvd Apt 227",
      "city":"Rochester Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48309",
      "country": "United States",
      "latitude":42.6819342,
      "longitude":-83.1840429
    }
  },
  {
    "patient":"1114156581",
    "admission":"GLO-900087",
    "firstname":"Guiqing",
    "middlename":null,
    "lastname":"Liang",
    "phone":"248-613-1398",
    "address":{
      "type":"Home",
      "address":"535 W Fairmount Ave",
      "city":"Pontiac",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48340",
      "country": "United States",
      "latitude":42.6692132,
      "longitude":-83.31581481
    }
  },
  {
    "patient":"1117537106",
    "admission":"GLO-900098",
    "firstname":"Jin Lan",
    "middlename":null,
    "lastname":"Li",
    "phone":"248-821-0108",
    "address":{
      "type":"Home",
      "address":"9780 David Ln",
      "city":"White Lake",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48386",
      "country": "United States",
      "latitude":42.66206836,
      "longitude":-83.48229502
    }
  },
  {
    "patient":"1138075845",
    "admission":"GLO-900061",
    "firstname":"Shanyao",
    "middlename":null,
    "lastname":"Zhao",
    "phone":"248-925-9398",
    "address":{
      "type":"Home",
      "address":"500 E Irving Ave Apt 217",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country": "United States",
      "latitude":42.52224172,
      "longitude":-83.10284635
    }
  },
  {
    "patient":"1146516846",
    "admission":"GLO-900108",
    "firstname":"Mariya",
    "middlename":null,
    "lastname":"Solomyanna",
    "phone":"248-787-0816",
    "address":{
      "type":"Home",
      "address":"4022 Hardwoods Dr",
      "city":"West Bloomfield",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48323",
      "country": "United States",
      "latitude":42.56967933,
      "longitude":-83.36282395
    }
  },
  {
    "patient":"1155023898",
    "admission":"GLO-900095",
    "firstname":"Yinghua",
    "middlename":null,
    "lastname":"Wang",
    "phone":"248-506-4966",
    "address":{
      "type":"Home",
      "address":"500 E Irving Ave Apt 425",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country": "United States",
      "latitude":42.52220834,
      "longitude":-83.10234407
    }
  },
  {
    "patient":"1155583365",
    "admission":"GLO-900043",
    "firstname":"Zhuqin",
    "middlename":null,
    "lastname":"Zhang",
    "phone":"248-925-9398",
    "address":{
      "type":"Home",
      "address":"500 E Irving Ave Apt 217",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country": "United States",
      "latitude":42.52225358,
      "longitude":-83.10207475
    }
  },
  {
    "patient":"1166947206",
    "admission":"GLO-900084",
    "firstname":"Changyue",
    "middlename":null,
    "lastname":"Ouyang",
    "phone":"734-658-3091",
    "address":{
      "type":"Home",
      "address":"2303 Sandalwood Cir Apt 315B",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.30730852,
      "longitude":-83.70899553
    }
  },
  {
    "patient":"1168007597",
    "admission":"GLO-900044",
    "firstname":"Leonid",
    "middlename":"V",
    "lastname":"Lyashenko",
    "phone":"586-303-5866",
    "address":{
      "type":"Home",
      "address":"19529 Bigelow St",
      "city":"Roseville",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48066",
      "country": "United States",
      "latitude":42.51527795,
      "longitude":-82.92049285
    }
  },
  {
    "patient":"1168007603",
    "admission":"GLO-900027",
    "firstname":"Evelina",
    "middlename":null,
    "lastname":"Lyashenko",
    "phone":"586-303-5866",
    "address":{
      "type":"Home",
      "address":"19529 Bigelow St",
      "city":"Roseville",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48066",
      "country": "United States",
      "latitude":42.51520872,
      "longitude":-82.92045732
    }
  },
  {
    "patient":"1186138149",
    "admission":"GLO-900035",
    "firstname":"Yuriy",
    "middlename":null,
    "lastname":"Konechnyy",
    "phone":"313-587-2534",
    "address":{
      "type":"Home",
      "address":"415 Lexington Blvd",
      "city":"Royal Oak",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48073",
      "country": "United States",
      "latitude":42.52183137,
      "longitude":-83.14966693
    }
  },
  {
    "patient":"1211135956",
    "admission":"GLO-900103",
    "firstname":"Yuqin",
    "middlename":null,
    "lastname":"Zhang",
    "phone":"734-740-3966",
    "address":{
      "type":"Home",
      "address":"47274 Mallard Dr",
      "city":"Shelby Township",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48315",
      "country": "United States",
      "latitude":42.64376527,
      "longitude":-82.978307
    }
  },
  {
    "patient":"1213559850",
    "admission":"GLO-900007",
    "firstname":"Slavka",
    "middlename":"Grigorova",
    "lastname":"Kodjebasheva",
    "phone":"626-375-9205",
    "address":{
      "type":"Home",
      "address":"11211 Stonybrook Dr",
      "city":"Grand Blanc",
      "county":"Genesee",
      "state":"MI",
      "zipcode":"48439",
      "country": "United States",
      "latitude":42.93571783,
      "longitude":-83.62404596
    }
  },
  {
    "patient":"1267106557",
    "admission":"GLO-900011",
    "firstname":"Theresa",
    "middlename":null,
    "lastname":"Rogers",
    "phone":"810-333-1197",
    "address":{
      "type":"Home",
      "address":"35140 W 8 Mile Rd Apt 6",
      "city":"Farmington Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48335",
      "country": "United States",
      "latitude":42.44122098,
      "longitude":-83.39170522
    }
  },
  {
    "patient":"1267541988",
    "admission":"GLO-900038",
    "firstname":"Donella",
    "middlename":null,
    "lastname":"Williamson",
    "phone":"313-402-4335",
    "address":{
      "type":"Home",
      "address":"19640 Sawyer St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48228",
      "country": "United States",
      "latitude":42.3469739,
      "longitude":-83.23395237
    }
  },
  {
    "patient":"1268352009",
    "admission":"GLO-900037",
    "firstname":"Yizhuang",
    "middlename":null,
    "lastname":"Lin",
    "phone":"248-525-9695",
    "address":{
      "type":"Home",
      "address":"35709 Indigo Dr",
      "city":"Sterling Heights",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48310",
      "country": "United States",
      "latitude":42.554934,
      "longitude":-83.07956894
    }
  },
  {
    "patient":"1280205882",
    "admission":"GLO-900029",
    "firstname":"Liudmila",
    "middlename":"Andreevna",
    "lastname":"Stepanova",
    "phone":"513-289-7450",
    "address":{
      "type":"Home",
      "address":"5000 Westminister Dr",
      "city":"Dundee",
      "county":"Monroe",
      "state":"MI",
      "zipcode":"48131",
      "country": "United States",
      "latitude":41.96508219,
      "longitude":-83.65500799
    }
  }
]