###
# group: Backup Recovery
# @name Add Bulk Accounts
POST {{maxmila.baseUrl}}/bulk/auths
Content-Type: application/json

[
  {
    "username": "lanawithballet@gmail.com",
    "password": "SvetlanaKowalczyk5038",
    "role": 0,
    "status": 1
  },
  {
    "username": "hectorsalpen@gmail.com",
    "password": "HectorSalinas6589",
    "role": 0,
    "status": 1
  },
  {
    "username": "mhomecare27@gmail.com",
    "password": "Salom12345",
    "role": 0,
    "status": 1
  },
  {
    "username": "olyachopik@gmail.com",
    "password": "OlhaChopyk2601",
    "role": 2,
    "status": 1
  },
  {
    "username": "andrei.buzatu@gmail.com",
    "password": "AndreiBuzatu7596",
    "role": 2,
    "status": 1
  },
  {
    "username": "zhikuiling@yahoo.com",
    "password": "ZhiKuiLing5455",
    "role": 2,
    "status": 1
  },
  {
    "username": "Yuyao1205@yahoo.com",
    "password": "YuYao1786",
    "role": 2,
    "status": 1
  },
  {
    "username": "huiipersonal@gmail.com",
    "password": "YuemingYang1825",
    "role": 2,
    "status": 1
  },
  {
    "username": "khaitmaria8@gmail.com",
    "password": "MariyaSheuchyk7874",
    "role": 2,
    "status": 1
  },
  {
    "username": "ramishka8184@gmail.com",
    "password": "RamiliaSultanova6675",
    "role": 2,
    "status": 1
  },
  {
    "username": "shuoyang@yahoo.com",
    "password": "ShuoYang8096",
    "role": 2,
    "status": 1
  },
  {
    "username": "jlutes2017@yahoo.com",
    "password": "ElenaLutes4606",
    "role": 2,
    "status": 1
  },
  {
    "username": "zahwa120@icloud.com",
    "password": "ZahwaShehadeh0442",
    "role": 2,
    "status": 1
  },
  {
    "username": "beet917@gmail.com",
    "password": "XinLin3259",
    "role": 2,
    "status": 1
  },
  {
    "username": "lianchangqiao@gmail.com",
    "password": "LianchangQiao8241",
    "role": 2,
    "status": 1
  },
  {
    "username": "sshao21@yahoo.com",
    "password": "EdwardWang3655",
    "role": 2,
    "status": 1
  },
  {
    "username": "karimovanoza@icloud.com",
    "password": "SarvinozKarimova0075",
    "role": 2,
    "status": 1
  },
  {
    "username": "sshao321@yahoo.com",
    "password": "SophieShao0428",
    "role": 2,
    "status": 1
  },
  {
    "username": "trinketronix@gmail.com",
    "password": "TrinketronixLLC6589",
    "role": 0,
    "status": 1
  },
  {
    "username": "42963418@qq.com",
    "password": "LiquChen8109",
    "role": 2,
    "status": 1
  },
  {
    "username": "ricardoestes@comcast.net",
    "password": "RicardoEstes0985",
    "role": 2,
    "status": 1
  },
  {
    "username": "mariyavarshavska9@gmail.com",
    "password": "MariyaVarshavska7229",
    "role": 2,
    "status": 1
  },
  {
    "username": "yxwenster@gmail.com",
    "password": "YuelinLi6792",
    "role": 2,
    "status": 1
  },
  {
    "username": "henrynina48083@hotmial.com",
    "password": "HongjunZhao4229",
    "role": 2,
    "status": 1
  },
  {
    "username": "jieminggao@yahoo.com",
    "password": "QingGao2406",
    "role": 2,
    "status": 1
  },
  {
    "username": "gyezersky82@gmail.com",
    "password": "GeoffreyYezersky6834",
    "role": 2,
    "status": 1
  },
  {
    "username": "evan.p.chang@gmail.com",
    "password": "EvanChang9708",
    "role": 2,
    "status": 1
  },
  {
    "username": "lili4945@gmail.com",
    "password": "LiLi8729",
    "role": 2,
    "status": 1
  },
  {
    "username": "angielin99@yahoo.com",
    "password": "AngieLin2730",
    "role": 2,
    "status": 1
  },
  {
    "username": "yl19802004@gmail.com",
    "password": "YangyangLi9401",
    "role": 2,
    "status": 1
  },
  {
    "username": "lyezersky7@gmail.com",
    "password": "LarisaYezersky5144",
    "role": 2,
    "status": 1
  },
  {
    "username": "jinpanw@gmail.com",
    "password": "JinPan0208",
    "role": 2,
    "status": 1
  },
  {
    "username": "aimeedaisyy@gmail.com",
    "password": "AimeeLaLonde6024",
    "role": 2,
    "status": 1
  },
  {
    "username": "yongchentian@gmail.com",
    "password": "YuTian8717",
    "role": 2,
    "status": 1
  },
  {
    "username": "tampim2@gmail.com",
    "password": "GalinaLyashenko3906",
    "role": 2,
    "status": 1
  },
  {
    "username": "yulikowalczyk@gmail.com",
    "password": "YuliannaKowalczyk4358",
    "role": 2,
    "status": 1
  },
  {
    "username": "abirfadlallah6@gmail.com",
    "password": "AbirFadlallah3811",
    "role": 2,
    "status": 1
  },
  {
    "username": "annechenzhu1965@gmail.com",
    "password": "AnnaZhu0168",
    "role": 2,
    "status": 1
  },
  {
    "username": "ngmike33@gmail.com",
    "password": "MichaelNg0652",
    "role": 2,
    "status": 1
  },
  {
    "username": "ammakki9@gmail.com",
    "password": "AmalMakki7626",
    "role": 2,
    "status": 1
  },
  {
    "username": "grannykathy08@gmail.com",
    "password": "KathrynRogers3935",
    "role": 2,
    "status": 1
  },
  {
    "username": "olga.baruk@gmail.com",
    "password": "OlgaBaruk9380",
    "role": 2,
    "status": 1
  },
  {
    "username": "ahine2019@icloud.com",
    "password": "CharlotteAdjei4805",
    "role": 2,
    "status": 1
  },
  {
    "username": "sandravanderbilt6@gmail.com",
    "password": "SandraVanderbilt0412",
    "role": 2,
    "status": 1
  },
  {
    "username": "annaxue0925@gmail.com",
    "password": "AnnaXue1263",
    "role": 2,
    "status": 1
  },
  {
    "username": "dbdumitrescu@outlook.com",
    "password": "DevoraDumitrescu2881",
    "role": 2,
    "status": 1
  },
  {
    "username": "maxzhitkov@gmail.com",
    "password": "MaksimZhitkov3131",
    "role": 2,
    "status": 1
  },
  {
    "username": "makenzyherman711@gmail.com",
    "password": "MakenzyHerman4607",
    "role": 2,
    "status": 1
  },
  {
    "username": "PamVavoom1@gmail.com",
    "password": "JamesBlunden7596",
    "role": 2,
    "status": 1
  },
  {
    "username": "lqi78865@gmail.com",
    "password": "LiqunQiu5955",
    "role": 2,
    "status": 1
  },
  {
    "username": "conniepospeshil@yahoo.com",
    "password": "ConniePospeshil7524",
    "role": 2,
    "status": 1
  },
  {
    "username": "langeyue@gmail.com",
    "password": "LanGe1842",
    "role": 2,
    "status": 1
  },
  {
    "username": "annaligc1973@gmail.com",
    "password": "AnnaLi2932",
    "role": 2,
    "status": 1
  },
  {
    "username": "Lina.khanafer@live.com",
    "password": "LinaChehadeh6583",
    "role": 2,
    "status": 1
  },
  {
    "username": "hchen33@gmail.com",
    "password": "HuaChen2641",
    "role": 2,
    "status": 1
  },
  {
    "username": "zhlillian@yahoo.com",
    "password": "LingZhong4436",
    "role": 2,
    "status": 1
  },
  {
    "username": "xing.xy@gmail.com",
    "password": "XianyingXing9617",
    "role": 2,
    "status": 1
  },
  {
    "username": "msblackelk@yahoo.com",
    "password": "LeahBlackElk7618",
    "role": 2,
    "status": 1
  },
  {
    "username": "lidongdi1962@gmail.com",
    "password": "DongdiLi5708",
    "role": 2,
    "status": 1
  },
  {
    "username": "mxue2014@gmail.com",
    "password": "MeiXue2844",
    "role": 2,
    "status": 1
  },
  {
    "username": "hanleiwang.hlw@gmail.com",
    "password": "HanleiWang4066",
    "role": 2,
    "status": 1
  },
  {
    "username": "williamsw19631963@gmail.com",
    "password": "WillieWilliams8446",
    "role": 2,
    "status": 1
  },
  {
    "username": "weizhao101@hotmail.com",
    "password": "WeiZhao7101",
    "role": 2,
    "status": 1
  },
  {
    "username": "weix0014@hotmail.com",
    "password": "QiangWei6708",
    "role": 2,
    "status": 1
  },
  {
    "username": "hzhang996@gmail.com",
    "password": "HongZhang7150",
    "role": 2,
    "status": 1
  },
  {
    "username": "irizarryjose433@gmail.com",
    "password": "joseIrizarry7220",
    "role": 2,
    "status": 1
  },
  {
    "username": "princessalize2010@gmail.com",
    "password": "JuselineSainz1831",
    "role": 2,
    "status": 1
  },
  {
    "username": "459634669@qq.com",
    "password": "YongmeiLiang8409",
    "role": 2,
    "status": 1
  },
  {
    "username": "taksunchung66@gmail.com",
    "password": "TakSunChung1262",
    "role": 2,
    "status": 1
  },
  {
    "username": "zjj48071@gmail.com",
    "password": "JuanJuanzhu7846",
    "role": 2,
    "status": 1
  },
  {
    "username": "gergana@umich.edu",
    "password": "GerganaKodjebacheva7882",
    "role": 2,
    "status": 1
  },
  {
    "username": "xchen168138@gmail.com",
    "password": "XiaoXiaChen3383",
    "role": 2,
    "status": 1
  },
  {
    "username": "liupingliang83@gmail.com",
    "password": "LupingLiang5547",
    "role": 2,
    "status": 1
  },
  {
    "username": "david800803@gmail.com",
    "password": "ZhiweiYan3067",
    "role": 2,
    "status": 1
  },
  {
    "username": "1906442418@qq.com",
    "password": "YuanquChen5717",
    "role": 2,
    "status": 1
  },
  {
    "username": "irina.vasiuk@gmail.com",
    "password": "IrynaVasiuk9369",
    "role": 2,
    "status": 1
  },
  {
    "username": "rawanlakis@icloud.com",
    "password": "MonaAwada4413",
    "role": 2,
    "status": 1
  },
  {
    "username": "kemanli2014@gmail.com",
    "password": "KemanLi6932",
    "role": 2,
    "status": 1
  },
  {
    "username": "innaukr@gmail.com",
    "password": "InnaTikan1130",
    "role": 2,
    "status": 1
  },
  {
    "username": "vladimiswitas305@gmail.com",
    "password": "SvitlanaNakonechna3421",
    "role": 2,
    "status": 1
  },
  {
    "username": "yaqun17@gmail.com",
    "password": "YaqunZhu8063",
    "role": 2,
    "status": 1
  },
  {
    "username": "bolykalla@ukr.net",
    "password": "AllaBoliukh3215",
    "role": 2,
    "status": 1
  },
  {
    "username": "edmundo.chavez@gmail.com",
    "password": "EdmundoChavez6589",
    "role": 0,
    "status": 1
  },
  {
    "username": "xzhang7@wccnet.edu",
    "password": "XiaZhang2398",
    "role": 2,
    "status": 1
  },
  {
    "username": "rj107521186@gmail.com",
    "password": "JunRuan7248",
    "role": 2,
    "status": 1
  },
  {
    "username": "yangqingbo5@gmail.com",
    "password": "QingboYang5177",
    "role": 2,
    "status": 1
  },
  {
    "username": "191023092@qq.com",
    "password": "HongHu2891",
    "role": 2,
    "status": 1
  },
  {
    "username": "jcchen0518@gmail.com",
    "password": "JiangchenChen3215",
    "role": 2,
    "status": 1
  },
  {
    "username": "toddsalpen@gmail.com",
    "password": "ToddSalpen6589",
    "role": 1,
    "status": 1
  }
]

###
# group: Backup Recovery
# @name Update Bulk Users
PUT {{maxmila.baseUrl}}/bulk/users
Content-Type: application/json

[
  {
    "id":1,
    "firstname":"Svetlana",
    "lastname":"Kowalczyk",
    "code":"GLO-1001",
    "birthdate":"1968-10-22",
    "ssn":"309-15-5038",
    "phone":"734-560-1630",
    "email":"lanawithballet@gmail.com",
    "languages":"English, Spanish, Russian",
    "address":{
      "type":"Apartment",
      "address":"34500 Grandon Street",
      "city":"Livonia",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48150",
      "country":"United States"
    }
  },
  {
    "id":2,
    "firstname":"Hector",
    "lastname":"Salinas",
    "code":"GLO-1048",
    "birthdate":"1976-12-16",
    "ssn":"791-83-6589",
    "phone":"248-679-2601",
    "email":"hectorsalpen@gmail.com",
    "languages":"English, Spanish, Italian, Portugese, Mayan, Nahuatl",
    "address":{
      "type":"Apartment",
      "address":"7677 Maple Dr",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":3,
    "firstname":"Dildora",
    "lastname":"Damischa",
    "phone":"248-679-2601",
    "email":"mhomecare27@gmail.com",
    "languages":"English",
    "address":{
      "type":"Apartment",
      "address":"32969 Hamilton Ct",
      "city":"Farmington Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48334",
      "country":"United States"
    }
  },
  {
    "id":4,
    "firstname":"Olha",
    "lastname":"Chopyk",
    "code":"GLO-1059",
    "birthdate":"1989-10-11",
    "ssn":"001-67-2601",
    "phone":"313-804-2691",
    "email":"olyachopik@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"31278 Shorecrest Dr Apt.23207",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48377",
      "country":"United States"
    }
  },
  {
    "id":5,
    "firstname":"Andrei",
    "lastname":"Buzatu",
    "code":"GLO-1007",
    "birthdate":"1984-12-07",
    "ssn":"003-26-7596",
    "phone":"734-358-8860",
    "email":"andrei.buzatu@gmail.com",
    "languages":"English, Spanish, Romanian",
    "address":{
      "type":"Apartment",
      "address":"29348 Decuindre Rd #103",
      "city":"Warren",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48092",
      "country":"United States"
    }
  },
  {
    "id":6,
    "firstname":"Zhi-Kui",
    "lastname":"Ling",
    "code":"GLO-1012",
    "birthdate":"1961-10-18",
    "ssn":"016-62-5455",
    "phone":"248-974-5933",
    "email":"zhikuiling@yahoo.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"45211 Bartlett Drive",
      "city":"Novi",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48377",
      "country":"United States"
    }
  },
  {
    "id":7,
    "firstname":"Yu",
    "lastname":"Yao",
    "code":"GLO-1038",
    "birthdate":"1977-11-02",
    "ssn":"021-99-1786",
    "phone":"734-276-0011",
    "email":"Yuyao1205@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1058 Greenhills Dr.",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":8,
    "firstname":"Yueming",
    "lastname":"Yang",
    "code":"GLO-1029",
    "birthdate":"1963-11-19",
    "ssn":"087-86-1825",
    "phone":"734-502-1598",
    "email":"huiipersonal@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"35594 Dove Trail",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":9,
    "firstname":"Mariya",
    "lastname":"Sheuchyk",
    "code":"GLO-1071",
    "birthdate":"1987-01-18",
    "ssn":"099-81-7874",
    "phone":"810-493-1183",
    "email":"khaitmaria8@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"3725 Delaware Ave",
      "city":"Flint",
      "county":"Genesee",
      "state":"MI",
      "zipcode":"48506",
      "country":"United States"
    }
  },
  {
    "id":10,
    "firstname":"Ramilia",
    "lastname":"Sultanova",
    "code":"GLO-1013",
    "birthdate":"1981-10-19",
    "ssn":"156-73-6675",
    "phone":"903-505-4523",
    "email":"ramishka8184@gmail.com",
    "languages":"English, Spanish, Russian, Uzbek, Kyrgyz",
    "address":{
      "type":"Apartment",
      "address":"31155 Portside Dr. Apt.#7207",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48377",
      "country":"United States"
    }
  },
  {
    "id":11,
    "firstname":"Shuo",
    "lastname":"Yang",
    "code":"GLO-1003",
    "birthdate":"1960-06-07",
    "ssn":"215-29-8096",
    "phone":"248-880-7585",
    "email":"shuoyang@yahoo.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"33790 Norfolk",
      "city":"Livonia",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48152",
      "country":"United States"
    }
  },
  {
    "id":12,
    "firstname":"Elena",
    "lastname":"Lutes",
    "birthdate":"1979-02-06",
    "ssn":"277-15-4606",
    "phone":"513-289-7450",
    "email":"jlutes2017@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":13,
    "firstname":"Zahwa",
    "lastname":"Shehadeh",
    "birthdate":"1972-12-24",
    "ssn":"282-90-0442",
    "phone":"313-960-0048",
    "email":"zahwa120@icloud.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":14,
    "firstname":"Xin",
    "lastname":"Lin",
    "birthdate":"1984-01-28",
    "ssn":"283-08-3259",
    "phone":"248-525-9695",
    "email":"beet917@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":15,
    "firstname":"Lianchang",
    "lastname":"Qiao",
    "code":"GLO-1039",
    "birthdate":"1954-09-04",
    "ssn":"284-65-8241",
    "phone":"734-800-9504",
    "email":"lianchangqiao@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2864 Elmwood Avenue",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48104",
      "country":"United States"
    }
  },
  {
    "id":16,
    "firstname":"Edward",
    "lastname":"Wang",
    "code":"GLO-1056",
    "birthdate":"1965-07-14",
    "ssn":"287-90-3655",
    "phone":"248-202-7771",
    "email":"sshao21@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"256 Shore Brook Ln",
      "city":"Walled Lake",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48390",
      "country":"United States"
    }
  },
  {
    "id":17,
    "firstname":"Sarvinoz",
    "lastname":"Karimova",
    "code":"GLO-1040",
    "birthdate":"1995-06-05",
    "ssn":"290-83-0075",
    "phone":"248-513-5858",
    "email":"karimovanoza@icloud.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"24712 Independence Dr. Apt. 2302",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48335",
      "country":"United States"
    }
  },
  {
    "id":18,
    "firstname":"Sophie",
    "lastname":"Shao",
    "code":"GLO-1041",
    "birthdate":"1967-06-22",
    "ssn":"301-90-0428",
    "phone":"248-494-2636",
    "email":"sshao321@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"356 Shore Brook Ln",
      "city":"Walled Lake",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48390",
      "country":"United States"
    }
  },
  {
    "id":19,
    "firstname":"Trinketronix",
    "lastname":"LLC",
    "birthdate":"2022-08-04",
    "phone":"248-679-2601",
    "email":"trinketronix@gmail.com",
    "email2":"robotcitolab@gmail.com",
    "languages":"English",
    "address":{
      "type":"Apartment",
      "address":"7677 Maple Dr",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":20,
    "firstname":"Liqu",
    "lastname":"Chen",
    "code":"GLO-1010",
    "birthdate":"1962-07-02",
    "ssn":"315-97-8109",
    "phone":"734-680-6688",
    "email":"42963418@qq.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"2448 Nixon Rd",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":21,
    "firstname":"Ricardo",
    "lastname":"Estes",
    "birthdate":"1968-01-20",
    "ssn":"330-56-0985",
    "phone":"734-545-3052",
    "email":"ricardoestes@comcast.net",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":22,
    "firstname":"Mariya",
    "lastname":"Varshavska",
    "code":"GLO-1034",
    "birthdate":"1969-10-11",
    "ssn":"348-59-7229",
    "phone":"734-730-2751",
    "email":"mariyavarshavska9@gmail.com",
    "email2":"algard1977@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2246 Yemans St",
      "city":"Hamtramck",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48212",
      "country":"United States"
    }
  },
  {
    "id":23,
    "firstname":"Yuelin",
    "lastname":"Li",
    "code":"GLO-1031",
    "birthdate":"1953-11-22",
    "ssn":"357-15-6792",
    "phone":"248-251-9350",
    "email":"yxwenster@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1578 Caliper Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48084",
      "country":"United States"
    }
  },
  {
    "id":24,
    "firstname":"Hongjun",
    "lastname":"Zhao",
    "code":"GLO-1015",
    "birthdate":"1976-09-18",
    "ssn":"360-96-4229",
    "phone":"248-925-9398",
    "email":"henrynina48083@hotmial.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"286 Miracle Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48084",
      "country":"United States"
    }
  },
  {
    "id":25,
    "firstname":"Qing",
    "lastname":"Gao",
    "code":"GLO-1050",
    "birthdate":"1964-06-19",
    "ssn":"362-23-2406",
    "phone":"248-403-1465",
    "email":"jieminggao@yahoo.com",
    "languages":"English, Spanish, Chinese",
    "address":{
      "type":"Apartment",
      "address":"20939 Meadowlark St",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48336",
      "country":"United States"
    }
  },
  {
    "id":26,
    "firstname":"Geoffrey",
    "lastname":"Yezersky",
    "code":"GLO-1073",
    "birthdate":"1999-10-07",
    "ssn":"363-25-6834",
    "phone":"248-553-5429",
    "email":"gyezersky82@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"35987 Charter Crest Road",
      "city":"Farmington",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48335",
      "country":"United States"
    }
  },
  {
    "id":27,
    "firstname":"Evan",
    "lastname":"Chang",
    "code":"GLO-1008",
    "birthdate":"2001-05-03",
    "ssn":"364-27-9708",
    "phone":"810-893-1778",
    "email":"evan.p.chang@gmail.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"3807 Woodmonte Dr ",
      "city":"Rochester",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48306",
      "country":"United States"
    }
  },
  {
    "id":28,
    "firstname":"Li",
    "lastname":"Li",
    "code":"GLO-1055",
    "birthdate":"1971-05-13",
    "ssn":"366-29-8729",
    "phone":"248-795-0385",
    "email":"lili4945@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"4945 Moonglow Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48098",
      "country":"United States"
    }
  },
  {
    "id":29,
    "firstname":"Angie",
    "lastname":"Lin",
    "code":"GLO-1044",
    "birthdate":"1977-12-04",
    "ssn":"366-33-2730",
    "phone":"248-342-8039",
    "email":"angielin99@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"117 Manor Way",
      "city":"Rochester",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48309",
      "country":"United States"
    }
  },
  {
    "id":30,
    "firstname":"Yangyang",
    "lastname":"Li",
    "birthdate":"1980-02-14",
    "ssn":"366-33-9401",
    "phone":"248-881-0209",
    "email":"yl19802004@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":31,
    "firstname":"Larisa",
    "lastname":"Yezersky",
    "code":"GLO-1018",
    "birthdate":"1971-08-24",
    "ssn":"367-19-5144",
    "phone":"248-660-3570",
    "email":"lyezersky7@gmail.com",
    "languages":"English, Spanish, Russian",
    "address":{
      "type":"Apartment",
      "address":"35987 Charter Crest Farmington",
      "city":"Farmington Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48335",
      "country":"United States"
    }
  },
  {
    "id":32,
    "firstname":"Jin",
    "lastname":"Pan",
    "code":"GLO-1019",
    "birthdate":"1962-08-24",
    "ssn":"367-25-0208",
    "phone":"734-673-4276",
    "email":"jinpanw@gmail.com",
    "languages":"English, Spanish, Chinese",
    "address":{
      "type":"Apartment",
      "address":"48125 Gladstone Rd",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48188",
      "country":"United States"
    }
  },
  {
    "id":33,
    "firstname":"Aimee",
    "lastname":"LaLonde",
    "code":"GLO-1014",
    "birthdate":"1971-10-12",
    "ssn":"367-74-6024",
    "phone":"734-556-7335",
    "email":"aimeedaisyy@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1376 Northwood",
      "city":"Inkster",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48141",
      "country":"United States"
    }
  },
  {
    "id":34,
    "firstname":"Yu",
    "lastname":"Tian",
    "code":"GLO-1026",
    "birthdate":"1970-04-28",
    "ssn":"370-19-8717",
    "phone":"248-759-1633",
    "email":"yongchentian@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"44000 Settlers Creek",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48375",
      "country":"United States"
    }
  },
  {
    "id":35,
    "firstname":"Galina",
    "lastname":"Lyashenko",
    "code":"GLO-1024",
    "birthdate":"1962-02-22",
    "ssn":"371-25-3906",
    "phone":"586-303-5866",
    "email":"tampim2@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"17719 Roseville Blvd",
      "city":"Roseville",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48066",
      "country":"United States"
    }
  },
  {
    "id":36,
    "firstname":"Yulianna",
    "lastname":"Kowalczyk",
    "code":"GLO-1051",
    "birthdate":"2006-06-12",
    "ssn":"371-33-4358",
    "phone":"734-620-9384",
    "email":"yulikowalczyk@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"34500 Grandon Street",
      "city":"Livonia",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48150",
      "country":"United States"
    }
  },
  {
    "id":37,
    "firstname":"Abir",
    "lastname":"Fadlallah",
    "code":"GLO-1021",
    "birthdate":"1972-03-06",
    "ssn":"371-96-3811",
    "phone":"313-729-4444",
    "email":"abirfadlallah6@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"27105 Terrel Street",
      "city":"Dearborn Heights",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48127",
      "country":"United States"
    }
  },
  {
    "id":38,
    "firstname":"Anna",
    "lastname":"Zhu",
    "code":"GLO-1028",
    "birthdate":"1965-11-07",
    "ssn":"372-06-0168",
    "phone":"734-882-5444",
    "email":"annechenzhu1965@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"42063 Trent Drive",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48188",
      "country":"United States"
    }
  },
  {
    "id":39,
    "firstname":"Michael",
    "middlename":"G",
    "lastname":"Ng",
    "code":"GLO-1017",
    "birthdate":"1980-09-29",
    "ssn":"372-88-0652",
    "phone":"248-854-6210",
    "email":"ngmike33@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"4712 Marian Ave",
      "city":"Warren",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48092",
      "country":"United States"
    }
  },
  {
    "id":40,
    "firstname":"Amal",
    "middlename":"F",
    "lastname":"Makki",
    "code":"GLO-1020",
    "birthdate":"1961-08-10",
    "ssn":"372-94-7626",
    "phone":"248-396-3801",
    "email":"ammakki9@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"21260 Woodland Glen Dr Apt 202",
      "city":"Northville",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48167",
      "country":"United States"
    }
  },
  {
    "id":41,
    "firstname":"Kathryn",
    "lastname":"Rogers",
    "birthdate":"1954-08-20",
    "ssn":"373-66-3935",
    "phone":"248-987-4640",
    "email":"grannykathy08@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":42,
    "firstname":"Olga",
    "lastname":"Baruk",
    "code":"GLO-1005",
    "birthdate":"1970-08-09",
    "ssn":"375-21-9380",
    "phone":"734-788-5714",
    "email":"olga.baruk@gmail.com",
    "languages":"English, Spanish, Russian",
    "address":{
      "type":"Apartment",
      "address":"41899 Warren Rd",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48187",
      "country":"United States"
    }
  },
  {
    "id":43,
    "firstname":"Charlotte",
    "lastname":"Adjei",
    "code":"GLO-1004",
    "birthdate":"1967-08-13",
    "ssn":"376-25-4805",
    "phone":"313-221-3434",
    "email":"ahine2019@icloud.com",
    "languages":"English, Spanish, Ghana",
    "address":{
      "type":"Apartment",
      "address":"7261 Wilderness Park Drive #201",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":44,
    "firstname":"Sandra",
    "lastname":"Vanderbilt",
    "birthdate":"1961-02-13",
    "ssn":"376-66-0412",
    "phone":"734-680-0342",
    "email":"sandravanderbilt6@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":45,
    "firstname":"Anna",
    "lastname":"Xue",
    "birthdate":"1963-09-25",
    "ssn":"377-29-1263",
    "phone":"248-613-1398",
    "email":"annaxue0925@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":46,
    "firstname":"Devora",
    "lastname":"Dumitrescu",
    "code":"GLO-1035",
    "birthdate":"1957-12-06",
    "ssn":"378-86-2881",
    "phone":"313-909-2665",
    "email":"dbdumitrescu@outlook.com",
    "email2":"vdumitrescu@outlook.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"10387 Overhill Dr",
      "city":"Brighton",
      "county":"Livingston",
      "state":"MI",
      "zipcode":"48114",
      "country":"United States"
    }
  },
  {
    "id":47,
    "firstname":"Maksim",
    "lastname":"Zhitkov",
    "code":"GLO-1037",
    "birthdate":"1970-12-27",
    "ssn":"381-15-3131",
    "phone":"248-935-7195",
    "email":"maxzhitkov@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"7119 Oakridge Ct",
      "city":"Clarkston",
      "county":"Clare",
      "state":"MI",
      "zipcode":"48346",
      "country":"United States"
    }
  },
  {
    "id":48,
    "firstname":"Makenzy",
    "lastname":"Herman",
    "code":"GLO-1065",
    "birthdate":"1999-05-10",
    "ssn":"381-23-4607",
    "phone":"248-495-9732",
    "email":"makenzyherman711@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"23360 Crossley Ave",
      "city":"Hazel Park",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48030",
      "country":"United States"
    }
  },
  {
    "id":49,
    "firstname":"James",
    "lastname":"Blunden",
    "code":"GLO-1006",
    "birthdate":"1927-01-01",
    "ssn":"381-26-7596",
    "phone":"248-390-0124",
    "email":"PamVavoom1@gmail.com",
    "email2":"jimblunden@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"552 E Annabelle Ave  ",
      "city":"Hazel Park",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48030",
      "country":"United States"
    }
  },
  {
    "id":50,
    "firstname":"Liqun",
    "lastname":"Qiu",
    "code":"GLO-1030",
    "birthdate":"1961-11-24",
    "ssn":"382-19-5955",
    "phone":"248-635-0887",
    "email":"lqi78865@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1015 Larchwood dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48083",
      "country":"United States"
    }
  },
  {
    "id":51,
    "firstname":"Connie",
    "lastname":"Pospeshil",
    "code":"GLO-1016",
    "birthdate":"1971-04-16",
    "ssn":"382-80-7524",
    "phone":"248-767-3061",
    "email":"conniepospeshil@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"21685 Chase Drive",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48375",
      "country":"United States"
    }
  },
  {
    "id":52,
    "firstname":"Lan",
    "lastname":"Ge",
    "birthdate":"1962-10-08",
    "ssn":"384-33-1842",
    "phone":"734-740-3906",
    "email":"langeyue@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":53,
    "firstname":"Anna",
    "lastname":"Li",
    "birthdate":"1973-03-14",
    "ssn":"385-13-2932",
    "phone":"734-679-3184",
    "email":"annaligc1973@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":54,
    "firstname":"Lina",
    "lastname":"Chehadeh",
    "code":"GLO-1009",
    "birthdate":"1975-01-27",
    "ssn":"385-15-6583",
    "phone":"313-717-1845",
    "email":"Lina.khanafer@live.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"6169 Inkster Rd",
      "city":"Garden City",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48135",
      "country":"United States"
    }
  },
  {
    "id":55,
    "firstname":"Hua",
    "lastname":"Chen",
    "code":"GLO-1052",
    "birthdate":"1970-09-26",
    "ssn":"385-21-2641",
    "phone":"734-637-3447",
    "email":"hchen33@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"46861 Wareham",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48187",
      "country":"United States"
    }
  },
  {
    "id":56,
    "firstname":"Ling",
    "lastname":"Zhong",
    "birthdate":"1955-11-09",
    "ssn":"386-08-4436",
    "phone":"248-320-1436",
    "email":"zhlillian@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":57,
    "firstname":"Xianying",
    "lastname":"Xing",
    "code":"GLO-1049",
    "birthdate":"1972-02-26",
    "ssn":"386-31-9617",
    "phone":"734-846-0807",
    "email":"xing.xy@gmail.com",
    "languages":"English, Spanish, Chinese",
    "address":{
      "type":"Apartment",
      "address":"1556 N Maple Rd",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48103",
      "country":"United States"
    }
  },
  {
    "id":58,
    "firstname":"Leah",
    "lastname":"Black-Elk",
    "code":"GLO-1068",
    "birthdate":"1981-05-16",
    "ssn":"386-88-7618",
    "phone":"248-954-5227",
    "email":"msblackelk@yahoo.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"5310 Wakefield Rd",
      "city":"Grand Blanc",
      "county":"Genesee",
      "state":"MI",
      "zipcode":"48439",
      "country":"United States"
    }
  },
  {
    "id":59,
    "firstname":"Dongdi",
    "lastname":"Li",
    "code":"GLO-1043",
    "birthdate":"1962-11-04",
    "ssn":"397-65-5708",
    "phone":"734-664-5669",
    "email":"lidongdi1962@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1921 Savannah Ln",
      "city":"Ypsilanti",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48198",
      "country":"United States"
    }
  },
  {
    "id":60,
    "firstname":"Mei",
    "lastname":"Xue",
    "code":"GLO-1023",
    "birthdate":"1968-02-19",
    "ssn":"401-45-2844",
    "phone":"248-767-8774",
    "email":"mxue2014@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"44489 Stone Rd",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48375",
      "country":"United States"
    }
  },
  {
    "id":61,
    "firstname":"Hanlei",
    "lastname":"Wang",
    "code":"GLO-1063",
    "birthdate":"2001-02-16",
    "ssn":"403-65-4066",
    "phone":"513-734-8551",
    "email":"hanleiwang.hlw@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"31690 Cowan Rd",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  },
  {
    "id":62,
    "firstname":"Willie",
    "lastname":"Williams",
    "code":"GLO-1025",
    "birthdate":"1963-02-09",
    "ssn":"432-29-8446",
    "phone":"810-588-0517",
    "email":"williamsw19631963@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2125 Glencoe Hills Dr. Apt.#11",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48108",
      "country":"United States"
    }
  },
  {
    "id":63,
    "firstname":"Wei",
    "lastname":"Zhao",
    "code":"GLO-1033",
    "birthdate":"1971-05-07",
    "ssn":"470-35-7101",
    "phone":"248-345-4919",
    "email":"weizhao101@hotmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"44863 Revere Drive",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48377",
      "country":"United States"
    }
  },
  {
    "id":64,
    "firstname":"Qiang",
    "lastname":"Wei",
    "code":"GLO-1045",
    "birthdate":"1968-05-19",
    "ssn":"531-35-6708",
    "phone":"248-345-4019",
    "email":"weix0014@hotmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"26551 Glenwood Dr",
      "city":"Novi",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48374",
      "country":"United States"
    }
  },
  {
    "id":65,
    "firstname":"Hong",
    "lastname":"Zhang",
    "code":"GLO-1047",
    "birthdate":"1959-07-14",
    "ssn":"578-11-7150",
    "phone":"248-606-9696",
    "email":"hzhang996@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"1819 Lexington Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48084",
      "country":"United States"
    }
  },
  {
    "id":66,
    "firstname":"jose",
    "lastname":"Irizarry",
    "code":"GLO-1046",
    "birthdate":"1998-08-10",
    "ssn":"583-47-7220",
    "phone":"313-888-1139",
    "email":"irizarryjose433@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"15351 Pembroke Avenue",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48235",
      "country":"United States"
    }
  },
  {
    "id":67,
    "firstname":"Juseline",
    "lastname":"Sainz",
    "code":"GLO-1032",
    "birthdate":"1979-10-04",
    "ssn":"583-85-1831",
    "phone":"313-800-2049",
    "email":"princessalize2010@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"15351 Pembroke Avenue",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48235",
      "country":"United States"
    }
  },
  {
    "id":68,
    "firstname":"Yongmei",
    "lastname":"Liang",
    "code":"GLO-1058",
    "birthdate":"1971-04-08",
    "ssn":"598-39-8409",
    "phone":"248-825-0652",
    "email":"459634669@qq.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"3019 Longview Ave",
      "city":"Rochester",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48307",
      "country":"United States"
    }
  },
  {
    "id":69,
    "firstname":"Tak Sun",
    "lastname":"Chung",
    "code":"GLO-1011",
    "birthdate":"1964-09-30",
    "ssn":"602-30-1262",
    "phone":"248-376-9223",
    "phone2":"248-250-1942",
    "email":"taksunchung66@gmail.com",
    "languages":"English, Spanish, Mandarin",
    "address":{
      "type":"Apartment",
      "address":"66 Stalwart Dr",
      "city":"Troy",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48098",
      "country":"United States"
    }
  },
  {
    "id":70,
    "firstname":"JuanJuan",
    "lastname":"zhu",
    "code":"GLO-1042",
    "birthdate":"1960-01-02",
    "ssn":"613-35-7846",
    "email":"zjj48071@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"26640 Couzens Avenu",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country":"United States"
    }
  },
  {
    "id":71,
    "firstname":"Gergana",
    "lastname":"Kodjebacheva",
    "birthdate":"1969-07-06",
    "ssn":"618-06-7882",
    "phone":"626-375-9205",
    "email":"gergana@umich.edu",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48213",
      "country":"United States"
    }
  },
  {
    "id":72,
    "firstname":"Xiao Xia",
    "lastname":"Chen",
    "code":"GLO-1066",
    "birthdate":"1984-06-22",
    "ssn":"641-54-3383",
    "phone":"586-663-6620",
    "email":"xchen168138@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"39816 Dorian Dr",
      "city":"Sterling Heights",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48310",
      "country":"United States"
    }
  },
  {
    "id":73,
    "firstname":"Luping",
    "lastname":"Liang",
    "birthdate":"1962-11-06",
    "ssn":"655-79-5547",
    "phone":"248-804-3227",
    "email":"liupingliang83@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2024 Hubbard St",
      "city":"Detroit",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48204",
      "country":"United States"
    }
  },
  {
    "id":74,
    "firstname":"Zhiwei",
    "lastname":"Yan",
    "code":"GLO-1064",
    "birthdate":"1980-08-03",
    "ssn":"683-53-3067",
    "phone":"734-678-7008",
    "email":"david800803@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"31610 Eagle Ct",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":75,
    "firstname":"Yuanqu",
    "lastname":"Chen",
    "code":"GLO-1054",
    "birthdate":"1964-01-10",
    "ssn":"696-45-5717",
    "phone":"734-666-8088",
    "email":"1906442418@qq.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2448 Nixon Rd",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":76,
    "firstname":"Iryna",
    "lastname":"Vasiuk",
    "code":"GLO-1061",
    "birthdate":"1980-10-05",
    "ssn":"718-63-9369",
    "phone":"248-949-6006",
    "email":"irina.vasiuk@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"11729 Spicer Dr",
      "city":"Plymouth",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48170",
      "country":"United States"
    }
  },
  {
    "id":77,
    "firstname":"Mona",
    "lastname":"Awada",
    "code":"GLO-1069",
    "birthdate":"1966-08-15",
    "ssn":"729-16-4413",
    "phone":"313-717-2484",
    "email":"rawanlakis@icloud.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"25839 Midway sreet",
      "city":"Dearborn Heights",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48127",
      "country":"United States"
    }
  },
  {
    "id":78,
    "firstname":"Keman",
    "lastname":"Li",
    "code":"GLO-1074",
    "birthdate":"1977-12-04",
    "ssn":"739-03-6932",
    "phone":"734-447-6049",
    "email":"kemanli2014@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"387 Robyn",
      "city":"Canton",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48187",
      "country":"United States"
    }
  },
  {
    "id":79,
    "firstname":"Inna",
    "lastname":"Tikan",
    "code":"GLO-1036",
    "birthdate":"1970-09-30",
    "ssn":"741-43-1130",
    "phone":"248-425-3970",
    "email":"innaukr@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"4294 15 mile road",
      "city":"Sterling Heights",
      "county":"Macomb",
      "state":"MI",
      "zipcode":"48310",
      "country":"United States"
    }
  },
  {
    "id":80,
    "firstname":"Svitlana",
    "lastname":"Nakonechna",
    "code":"GLO-1053",
    "birthdate":"1991-04-13",
    "ssn":"748-22-3421",
    "phone":"248-678-2299",
    "email":"vladimiswitas305@gmail.com",
    "languages":"English, Spanish, Russian",
    "address":{
      "type":"Apartment",
      "address":"30070 W. 12 Mile Rd #128",
      "city":"Farmington Hills",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48334",
      "country":"United States"
    }
  },
  {
    "id":81,
    "firstname":"Yaqun",
    "lastname":"Zhu",
    "code":"GLO-1022",
    "birthdate":"1960-09-17",
    "ssn":"762-18-8063",
    "phone":"313-478-2566",
    "email":"yaqun17@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"255 S Vernon St",
      "city":"Dearborn",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48124",
      "country":"United States"
    }
  },
  {
    "id":82,
    "firstname":"Alla",
    "lastname":"Boliukh",
    "code":"GLO-1067",
    "birthdate":"1980-04-19",
    "ssn":"791-43-3215",
    "phone":"517-302-7053",
    "email":"bolykalla@ukr.net",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"11092 N Beck Rd",
      "city":"Plymouth",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48170",
      "country":"United States"
    }
  },
  {
    "id":83,
    "firstname":"Edmundo",
    "lastname":"Chavez",
    "birthdate":"1976-12-12",
    "email":"edmundo.chavez@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"204 Alfonso Caso",
      "city":"Tampico",
      "county":"Madero",
      "state":"TS",
      "zipcode":"89109",
      "country":"Mexico"
    }
  },
  {
    "id":84,
    "firstname":"Xia",
    "lastname":"Zhang",
    "code":"GLO-1062",
    "birthdate":"1965-07-16",
    "ssn":"817-14-2398",
    "phone":"734-546-4566",
    "email":"xzhang7@wccnet.edu",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2747 Barklay Way",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":85,
    "firstname":"Jun",
    "lastname":"Ruan",
    "code":"GLO-1057",
    "birthdate":"1976-01-21",
    "ssn":"842-28-7248",
    "phone":"586-344-4259",
    "email":"rj107521186@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"29252 Tessmer Ct",
      "city":"Madison Heights",
      "county":"Oakland",
      "state":"MI",
      "zipcode":"48071",
      "country":"United States"
    }
  },
  {
    "id":86,
    "firstname":"Qingbo",
    "lastname":"Yang",
    "code":"GLO-1027",
    "birthdate":"1966-02-11",
    "ssn":"856-45-5177",
    "phone":"313-806-3612",
    "email":"yangqingbo5@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"255 S Vernon",
      "city":"Dearborn",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48124",
      "country":"United States"
    }
  },
  {
    "id":87,
    "firstname":"Hong",
    "lastname":"Hu",
    "code":"GLO-1070",
    "birthdate":"1967-05-19",
    "ssn":"878-33-2891",
    "phone":"734-800-6188",
    "email":"191023092@qq.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2660 S Knightsbridge Cir",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":88,
    "firstname":"Jiangchen",
    "lastname":"Chen",
    "code":"GLO-1060",
    "birthdate":"1970-05-18",
    "ssn":"897-02-3215",
    "phone":"734-666-8382",
    "email":"jcchen0518@gmail.com",
    "languages":"English, Spanish",
    "address":{
      "type":"Apartment",
      "address":"2448 Nixon Rd",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country":"United States"
    }
  },
  {
    "id":89,
    "firstname":"Todd",
    "lastname":"Salpen",
    "birthdate":"1976-12-16",
    "phone":"248-679-2601",
    "email":"toddsalpen@gmail.com",
    "languages":"English, Spanish, Italian, Portugese, Mayan, Nahuatl",
    "address":{
      "type":"Apartment",
      "address":"7677 Maple Dr",
      "city":"Westland",
      "county":"Wayne",
      "state":"MI",
      "zipcode":"48185",
      "country":"United States"
    }
  }
]

###
# group: Backup Recovery
# @name Add Bulk Patients
POST {{maxmila.baseUrl}}/bulk/patients
Content-Type: application/json

[
  {
    "patient":"1190167218",
    "admission":"GLO-900128",
    "firstname":"Shichong",
    "middlename":null,
    "lastname":"Guo",
    "phone":"734-623-3087",
    "address":{
      "type":"Home",
      "address":"2385 Sandalwood Cir",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.3074874,
      "longitude":-83.7129055
    }
  },
  {
    "patient":"1190167085",
    "admission":"GLO-900129",
    "firstname":"Keren",
    "middlename":null,
    "lastname":"Liu",
    "phone":"734-623-3087",
    "address":{
      "type":"Home",
      "address":"2385 Sandalwood Cir",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.3074874,
      "longitude":-83.7129055
    }
  }
]