###
# group: Backup Recovery
# @name Add Bulk Accounts
POST {{maxmila.baseUrl}}/bulk/auths
Content-Type: application/json

[
  {"username":"system@maxmilahomecare.com","password":"Metsys2026"},
  {"username":"icarehomecare2017@gmail.com","password":"Svetlana2026"},
  {"username":"mhomecare27@gmail.com","password":"Dildora2026"},
  {"username":"lanawithballet@gmail.com","password":"Svetlana2026"},
  {"username":"shuoyang@yahoo.com","password":"Shuo2026"},
  {"username":"ahine2019@icloud.com","password":"Charlotte2026"},
  {"username":"olga.baruk@gmail.com","password":"Olga2026"},
  {"username":"jimblunden@yahoo.com","password":"James2026"},
  {"username":"andrei.buzatu@gmail.com","password":"Andrei2026"},
  {"username":"evan.p.chang@gmail.com","password":"Evan2026"},
  {"username":"lina.khanafer@live.com","password":"Lina2026"},
  {"username":"42963418@qq.com","password":"Liqu2026"},
  {"username":"taksunchung66@gmail.com","password":"Tak2026"},
  {"username":"zhikuiling@yahoo.com","password":"Zhi2026"},
  {"username":"ramishka8184@gmail.com","password":"Ramilia2026"},
  {"username":"aimeedaisyy@gmail.com","password":"Aimee2026"},
  {"username":"henrynina48083@hotmail.com","password":"Hongjun2026"},
  {"username":"conniepospeshil@yahoo.com","password":"Connie2026"},
  {"username":"ngmike33@gmail.com","password":"Michael2026"},
  {"username":"lyezersky7@gmail.com","password":"Larisa2026"},
  {"username":"jinpanw@gmail.com","password":"Jin2026"},
  {"username":"ammakki9@gmail.com","password":"Amal2026"},
  {"username":"abirfadlallah6@gmail.com","password":"Abir2026"},
  {"username":"yaqun17@gmail.com","password":"Yaqun2026"},
  {"username":"mxue2014@gmail.com","password":"Mei2026"},
  {"username":"tampim2@gmail.com","password":"Galina2026"},
  {"username":"williamsw19631963@gmail.com","password":"Willie2026"},
  {"username":"yonghentian@gmail.com","password":"Yu2026"},
  {"username":"yangqingbo5@gmail.com","password":"Qingbo2026"},
  {"username":"annechenzhu1965@gmail.com","password":"Anna2026"},
  {"username":"huiipersonal@gmail.com","password":"Yueming2026"},
  {"username":"lqi78865@gmail.com","password":"Liqun2026"},
  {"username":"yxwenster@gmail.com","password":"Yuelin2026"},
  {"username":"alizesainz79@icloud.com","password":"Juseline2026"},
  {"username":"weizhao101@hotmail.com","password":"Wei2026"},
  {"username":"mariyavarshavska9@gmail.com","password":"Mariya2026"},
  {"username":"vdumitrescu@outlook.com","password":"Devora2026"},
  {"username":"innaukr@gmail.com","password":"Inna2026"},
  {"username":"maxzhitkov@gmail.com","password":"Maksim2026"},
  {"username":"yuyao1205@yahoo.com","password":"Yu2026"},
  {"username":"lianchangqiao@gmail.com","password":"Lianchang2026"},
  {"username":"karimovanoza@icloud.com","password":"Sarvinoz2026"},
  {"username":"sshao321@yahoo.com","password":"Sophie2026"},
  {"username":"zjj48071@gmail.com","password":"JuanJuan2026"},
  {"username":"lidongdi1962@gmail.com","password":"Dongdi2026"},
  {"username":"angielin99@yahoo.com","password":"Angie2026"},
  {"username":"weix0014@hotmail.com","password":"Qiang2026"},
  {"username":"joseirizarry@maxmilahomecare.com","password":"Jose2026"},
  {"username":"hzhang996@gmail.com","password":"Hong2026"},
  {"username":"hectorsalpen@gmail.com","password":"Hector2026"},
  {"username":"xing.xy@gmail.com","password":"Xianying2026"},
  {"username":"jieminggao@yahoo.com","password":"Qing2026"},
  {"username":"yulikowalczyk@gmail.com","password":"Yulianna2026"},
  {"username":"hchen33@gmail.com","password":"Hua2026"},
  {"username":"vladimiswitas305@gmail.com","password":"Svitlana2026"},
  {"username":"1906442418@qq.com","password":"Yuanqu2026"},
  {"username":"lili4945@gmail.com","password":"Li2026"},
  {"username":"sshao21@yahoo.com","password":"Edward2026"},
  {"username":"rj107521186@gmail.com","password":"Jun2026"},
  {"username":"lyongmei1971@gmail.com","password":"Yongmei2026"},
  {"username":"olyachopik@gmail.com","password":"Olha2026"},
  {"username":"jcchen0518@gmail.com","password":"Jiangchen2026"},
  {"username":"irina.vasiuk@gmail.com","password":"Iryna2026"},
  {"username":"luzhang200@163.com","password":"Xia2026"},
  {"username":"hanleiwang.hlw@gmail.com","password":"Hanlei2026"},
  {"username":"david800803@gmail.com","password":"Zhiwei2026"},
  {"username":"makenzyherman711@gmail.com","password":"Makenzy2026"},
  {"username":"xchen168138@gmail.com","password":"Xiao2026"},
  {"username":"bolykalla@ukr.net","password":"Alla2026"},
  {"username":"msblackelk@yahoo.com","password":"Leah2026"},
  {"username":"rawanlakis@icloud.com","password":"Mona2026"},
  {"username":"191023092@qq.com","password":"Hong2026"},
  {"username":"khaitmaria8@gmail.com","password":"Mariya2026"},
  {"username":"gyezersky82@gmail.com","password":"Geoffrey2026"},
  {"username":"kemanli2014@gmail.com","password":"Keman2026"},
  {"username":"1040403123@qq.com","password":"Huoling2026"},
  {"username":"fuyuanai599@gmail.com","password":"Qinhua2026"},
  {"username":"gutsul0418@gmail.com","password":"Lyubov2026"},
  {"username":"kodao86@gmail.com","password":"Olena2026"},
  {"username":"jeanyinmi@gmail.com","password":"Jing2026"},
  {"username":"mekhri306@gmail.com","password":"Mekhriniso2026"},
  {"username":"langeyue@gmail.com","password":"Lan2026"},
  {"username":"shatil8049@gmail.com","password":"Alena2026"},
  {"username":"qicideng@gmail.com","password":"Qici2026"},
  {"username":"yanfang.liu650227@hotmail.com","password":"Yanfang2026"},
  {"username":"gnedik.ira2@gmail.com","password":"Iryna2026"},
  {"username":"paulinehan@yahoo.com","password":"Yan2026"},
  {"username":"183393364@qq.com","password":"Feng2026"},
  {"username":"lucydingxy@gmail.com","password":"Xueying2026"},
  {"username":"xiej5800@gmail.com","password":"Huaying2026"},
  {"username":"yinggao342@gmail.com","password":"Ying2026"},
  {"username":"jasony1215@gmail.com","password":"Jiazisong2026"},
  {"username":"j.sosonki@yahoo.com","password":"Yevgeniya2026"},
  {"username":"maydelosh@icloud.com","password":"Hongmei2026"},
  {"username":"junxi1970@gmail.com","password":"Jin2026"},
  {"username":"yl19802004@gmail.com","password":"Yangyang2026"},
  {"username":"qiaoxren@gmail.com","password":"Qiaoxia2026"},
  {"username":"grannykathy08@gmail.com","password":"Kathryn2026"},
  {"username":"annaxue0925@gmail.com","password":"Anna2026"},
  {"username":"ricardoestes@comcast.net","password":"Ricardo2026"},
  {"username":"xiahuagreen@gmail.com","password":"Xiaobao2026"},
  {"username":"kaihho91@gmail.com","password":"Kai2026"},
  {"username":"zhlillian@yahoo.com","password":"Ling2026"},
  {"username":"chaoy3@hotmail.com","password":"Yang2026"},
  {"username":"sandravanderbilt6@gmail.com","password":"Sandra2026"},
  {"username":"jsong1902@gmail.com","password":"Zhifeng2026"},
  {"username":"liupingliang83@gmail.com","password":"Liuping2026"},
  {"username":"lanangreg@sbcglobal.net","password":"Joanne2026"},
  {"username":"zebonazarova88@gmail.com","password":"Zebo2026"},
  {"username":"kudratovalola11@gmail.com","password":"Lola2026"},
  {"username":"zahwa120@icloud.com","password":"Zahwa2026"}
]

###
# group: Backup Recovery
# @name Update Bulk Users
POST {{maxmila.baseUrl}}/bulk/users
Content-Type: application/json

[
  {
    "id": 1,
    "firstname": "System",
    "lastname": "Administrator",
    "phone": "734-560-1630",
    "phone2": "248-679-2601",
    "email": "system@maxmilahomecare.com",
    "email2": "support@maxmilahomecare.com",
    "languages": "English"
  },
  {
    "id": 2,
    "firstname": "Svetlana",
    "lastname": "Administrator",
    "phone": "734-560-1630",
    "email": "icarehomecare2017@gmail.com"
  },
  {
    "id": 3,
    "firstname": "Dildora",
    "lastname": "Administrator",
    "phone": "734-560-1630",
    "email": "mhomecare27@gmail.com"
  },
  {
    "id": 4,
    "firstname": "Svetlana",
    "lastname": "Kowalczyk",
    "code": "GLO-1001",
    "birthdate": "1968-10-22",
    "ssn": "309-15-5038",
    "phone": "734-560-1630",
    "email": "lanawithballet@gmail.com",
    "languages": "English, Russian",
    "address": {
      "type": "Home",
      "address": "34500 Grandon St",
      "city": "Livonia",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48150",
      "country": "United States",
      "latitude": 42.3577793,
      "longitude": -83.3833575
    }
  },
  {
    "id": 5,
    "firstname": "Shuo",
    "lastname": "Yang",
    "code": "GLO-1003",
    "birthdate": "1960-06-07",
    "ssn": "215-29-8096",
    "phone": "248-880-7585",
    "email": "shuoyang@yahoo.com",
    "languages": "Mandarin, English",
    "address": {
      "type": "Home",
      "address": "33790 Norfolk",
      "city": "Livonia",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48152",
      "country": "United States",
      "latitude": 42.4369809,
      "longitude": -83.3787929
    }
  },
  {
    "id": 6,
    "firstname": "Charlotte",
    "lastname": "Adjei",
    "code": "GLO-1004",
    "birthdate": "1967-08-13",
    "ssn": "376-25-4805",
    "phone": "313-221-3434",
    "email": "ahine2019@icloud.com",
    "languages": "Ghana, English",
    "address": {
      "type": "Apartment",
      "address": "7261 Wilderness Park Dr, Apt 201",
      "city": "Westland",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48185",
      "country": "United States",
      "latitude": 42.3380955,
      "longitude": -83.4037126
    }
  },
  {
    "id": 7,
    "firstname": "Olga",
    "lastname": "Baruk",
    "code": "GLO-1005",
    "birthdate": "1970-08-09",
    "ssn": "375-21-9380",
    "phone": "734-788-5714",
    "email": "olga.baruk@gmail.com",
    "languages": "English, Russian",
    "address": {
      "type": "Home",
      "address": "41899 Warren Rd",
      "city": "Canton",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48087",
      "country": "United States",
      "latitude": 42.3369666,
      "longitude": -83.4541571
    }
  },
  {
    "id": 8,
    "firstname": "James",
    "lastname": "Blunden",
    "code": "GLO-1006",
    "birthdate": "1927-01-01",
    "ssn": "381-26-7596",
    "phone": "248-390-0124",
    "email": "jimblunden@yahoo.com",
    "email2": "pamvavoom1@gmail.com",
    "languages": "English",
    "address": {
      "type": "Home",
      "address": "552 E Annabelle Ave",
      "city": "Hazel Park",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48030",
      "country": "United States",
      "latitude": 42.4694854,
      "longitude": -83.1000116
    }
  },
  {
    "id": 9,
    "firstname": "Andrei",
    "lastname": "Buzatu",
    "code": "GLO-1007",
    "birthdate": "1984-12-07",
    "ssn": "003-26-7596",
    "phone": "734-358-8860",
    "phone2": "734-892-6884",
    "email": "andrei.buzatu@gmail.com",
    "languages": "Romanian, English",
    "address": {
      "type": "Apartment",
      "address": "29348 Decuindre Rd, Apt 103",
      "city": "Warren",
      "county": "Macomb",
      "state": "MI",
      "zipcode": "48092",
      "country": "United States",
      "latitude": 42.5083886,
      "longitude": -83.084058
    }
  },
  {
    "id": 10,
    "firstname": "Evan",
    "lastname": "Chang",
    "code": "GLO-1008",
    "birthdate": "2001-05-03",
    "ssn": "364-27-9708",
    "phone": "810-893-1778",
    "email": "evan.p.chang@gmail.com",
    "languages": "English, Mandarin",
    "address": {
      "type": "Home",
      "address": "3807 Woodmonte Dr",
      "city": "Rochester",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48306",
      "country": "United States",
      "latitude": 42.7189985,
      "longitude": -83.2110608
    }
  },
  {
    "id": 11,
    "firstname": "Lina",
    "lastname": "Chehadeh",
    "code": "GLO-1009",
    "birthdate": "1975-01-27",
    "ssn": "385-15-6583",
    "phone": "313-717-1845",
    "email": "lina.khanafer@live.com",
    "languages": "English",
    "address": {
      "type": "Home",
      "address": "6169 Inkster Rd",
      "city": "Garden City",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48135",
      "country": "United States",
      "latitude": 42.3310616,
      "longitude": -83.3121204
    }
  },
  {
    "id": 12,
    "firstname": "Liqu",
    "lastname": "Chen",
    "code": "GLO-1010",
    "birthdate": "1962-07-02",
    "ssn": "315-97-8109",
    "phone": "734-680-6688",
    "email": "42963418@qq.com",
    "languages": "Mandarin",
    "address": {
      "type": "Home",
      "address": "2448 Nixon Rd",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.3093418,
      "longitude": -83.7071462
    }
  },
  {
    "id": 13,
    "firstname": "Tak",
    "middlename": "Sun",
    "lastname": "Chung",
    "code": "GLO-1011",
    "birthdate": "1964-09-30",
    "ssn": "602-30-1262",
    "phone": "248-376-9223",
    "phone2": "248-250-1942",
    "email": "taksunchung66@gmail.com",
    "languages": "Mandarin",
    "address": {
      "type": "Home",
      "address": "66 Stalwart Dr",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48098",
      "country": "United States",
      "latitude": 42.5964235,
      "longitude": -83.1506406
    }
  },
  {
    "id": 14,
    "firstname": "Zhi",
    "middlename": "Kui",
    "lastname": "Ling",
    "code": "GLO-1012",
    "birthdate": "1961-10-18",
    "ssn": "016-62-5455",
    "phone": "248-974-5933",
    "email": "zhikuiling@yahoo.com",
    "languages": "English, Mandarin",
    "address": {
      "type": "Home",
      "address": "45211 Bartlett Dr",
      "city": "Novi",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48377",
      "country": "United States",
      "latitude": 42.4983393,
      "longitude": -83.4955212
    }
  },
  {
    "id": 15,
    "firstname": "Ramilia",
    "lastname": "Sultanova",
    "code": "GLO-1013",
    "birthdate": "1981-10-19",
    "ssn": "156-73-6675",
    "phone": "903-505-4523",
    "email": "ramishka8184@gmail.com",
    "languages": "Russian, Uzbek, Kyrgyz, English",
    "address": {
      "type": "Apartment",
      "address": "31155 Portside Dr, Apt 7207",
      "city": "Novi",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48377",
      "country": "United States",
      "latitude": 42.5224134,
      "longitude": -83.5072901
    }
  },
  {
    "id": 16,
    "firstname": "Aimee",
    "lastname": "LaLonde",
    "code": "GLO-1014",
    "birthdate": "1971-10-12",
    "ssn": "367-74-6024",
    "phone": "734-767-3982",
    "email": "aimeedaisyy@gmail.com",
    "languages": "English",
    "address": {
      "type": "Home",
      "address": "1376 Northwood",
      "city": "Inkster",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48141",
      "country": "United States",
      "latitude": 42.3015487,
      "longitude": -83.3121977
    }
  },
  {
    "id": 17,
    "firstname": "Hongjun",
    "lastname": "Zhao",
    "code": "GLO-1015",
    "birthdate": "1976-09-18",
    "ssn": "360-96-4229",
    "phone": "248-925-9398",
    "email": "henrynina48083@hotmail.com",
    "languages": "Mandarin, English",
    "address": {
      "type": "Home",
      "address": "286 Miracle Dr",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48084",
      "country": "United States",
      "latitude": 42.5767541,
      "longitude": -83.1543261
    }
  },
  {
    "id": 18,
    "firstname": "Connie",
    "lastname": "Pospeshil",
    "code": "GLO-1016",
    "birthdate": "1971-04-16",
    "ssn": "382-80-7524",
    "phone": "248-767-3061",
    "email": "conniepospeshil@yahoo.com",
    "languages": "English",
    "address": {
      "type": "Home",
      "address": "21685 Chase Dr",
      "city": "Novi",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48375",
      "country": "United States",
      "latitude": 42.4470571,
      "longitude": -83.4616131
    }
  },
  {
    "id": 19,
    "firstname": "Michael",
    "middlename": "G",
    "lastname": "Ng",
    "code": "GLO-1017",
    "birthdate": "1980-09-29",
    "ssn": "372-88-0652",
    "phone": "248-854-6210",
    "email": "ngmike33@gmail.com ",
    "address": {
      "type": "Home",
      "address": "4712 Marian Ave",
      "city": "Warren",
      "county": "Macomb",
      "state": "MI",
      "zipcode": "48092",
      "country": "United States",
      "latitude": 42.5037845,
      "longitude": -83.0602472
    }
  },
  {
    "id": 20,
    "firstname": "Larisa",
    "lastname": "Yezersky",
    "code": "GLO-1018",
    "birthdate": "1971-08-24",
    "ssn": "367-19-5144",
    "phone": "248-660-3570",
    "email": "lyezersky7@gmail.com",
    "languages": "English, Russian",
    "address": {
      "type": "Home",
      "address": "35987 Charter Crest",
      "city": "Farmington Hills",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48335",
      "country": "United States",
      "latitude": 42.4772389,
      "longitude": -83.4041647
    }
  },
  {
    "id": 21,
    "firstname": "Jin",
    "lastname": "Pan",
    "code": "GLO-1019",
    "birthdate": "1962-08-24",
    "ssn": "367-25-0208",
    "phone": "734-306-7020",
    "phone2": "734-673-4276",
    "email": "jinpanw@gmail.com",
    "languages": "English, Chinese",
    "address": {
      "type": "Home",
      "address": "48125 Gladstone Rd",
      "city": "Canton",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48188",
      "country": "United States",
      "latitude": 42.3056622,
      "longitude": -83.5129761
    }
  },
  {
    "id": 22,
    "firstname": "Amal",
    "middlename": "F",
    "lastname": "Makki",
    "code": "GLO-1020",
    "birthdate": "1961-08-10",
    "ssn": "372-94-7626",
    "phone": "248-396-3801",
    "email": "ammakki9@gmail.com",
    "languages": "English",
    "address": {
      "type": "Apartment",
      "address": "21260 Woodland Glen Dr, Apt 202",
      "city": "Northville",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48167",
      "country": "United States",
      "latitude": 42.4426042,
      "longitude": -83.4628722
    }
  },
  {
    "id": 23,
    "firstname": "Abir",
    "lastname": "Fadlallah",
    "code": "GLO-1021",
    "birthdate": "1972-03-06",
    "ssn": "371-96-3811",
    "phone": "313-729-4444",
    "email": "abirfadlallah6@gmail.com",
    "languages": "English",
    "address": {
      "type": "Home",
      "address": "27105 Terrel St",
      "city": "Dearborn Heights",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48127",
      "country": "United States",
      "latitude": 42.3268833,
      "longitude": -83.3071672
    }
  },
  {
    "id": 24,
    "firstname": "Yaqun",
    "lastname": "Zhu",
    "code": "GLO-1022",
    "birthdate": "1960-09-17",
    "ssn": "762-18-8063",
    "phone": "313-478-2566",
    "email": "yaqun17@gmail.com",
    "address": {
      "type": "Home",
      "address": "255 S Vernon St",
      "city": "Dearborn",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48124",
      "country": "United States",
      "latitude": 42.310688,
      "longitude": -83.2753638
    }
  },
  {
    "id": 25,
    "firstname": "Mei",
    "lastname": "Xue",
    "code": "GLO-1023",
    "birthdate": "1968-02-19",
    "ssn": "401-45-2844",
    "phone": "248-767-8774",
    "email": "mxue2014@gmail.com ",
    "address": {
      "type": "Home",
      "address": "44489 Stone Rd",
      "city": "Novi",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48375",
      "country": "United States",
      "latitude": 42.4749091,
      "longitude": -83.4865692
    }
  },
  {
    "id": 26,
    "firstname": "Galina",
    "lastname": "Lyashenko",
    "code": "GLO-1024",
    "birthdate": "1962-02-22",
    "ssn": "371-25-3906",
    "phone": "586-303-5866",
    "email": "tampim2@gmail.com",
    "address": {
      "type": "Home",
      "address": "17719 Roseville Blvd",
      "city": "Roseville",
      "county": "Macomb",
      "state": "MI",
      "zipcode": "48066",
      "country": "United States",
      "latitude": 42.4994659,
      "longitude": -82.9379479
    }
  },
  {
    "id": 27,
    "firstname": "Willie",
    "lastname": "Williams",
    "code": "GLO-1025",
    "birthdate": "1963-02-09",
    "ssn": "432-29-8446",
    "phone": "810-588-0517",
    "email": "williamsw19631963@gmail.com",
    "address": {
      "type": "Apartment",
      "address": "2125 Glencoe Hills Dr, Apt 11",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48108",
      "country": "United States",
      "latitude": 42.2574541,
      "longitude": -83.6716237
    }
  },
  {
    "id": 28,
    "firstname": "Yu",
    "lastname": "Tian",
    "code": "GLO-1026",
    "birthdate": "1970-04-28",
    "ssn": "370-19-8717",
    "phone": "248-759-1633",
    "email": "yonghentian@gmail.com",
    "address": {
      "type": "Home",
      "address": "44000 Settlers Crk",
      "city": "Novi",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48375",
      "country": "United States",
      "latitude": 42.4742883,
      "longitude": -83.4812859
    }
  },
  {
    "id": 29,
    "firstname": "Qingbo",
    "lastname": "Yang",
    "code": "GLO-1027",
    "birthdate": "1966-02-11",
    "ssn": "856-45-5177",
    "phone": "313-806-3612",
    "email": "yangqingbo5@gmail.com",
    "address": {
      "type": "Home",
      "address": "255 S Vernon",
      "city": "Dearborn",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48124",
      "country": "United States",
      "latitude": 42.310688,
      "longitude": -83.2753638
    }
  },
  {
    "id": 30,
    "firstname": "Anna",
    "lastname": "Zhu",
    "code": "GLO-1028",
    "birthdate": "1965-11-07",
    "ssn": "372-06-0168",
    "phone": "734-882-5444",
    "email": "annechenzhu1965@gmail.com",
    "address": {
      "type": "Home",
      "address": "42063 Trent Dr",
      "city": "Canton",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48188",
      "country": "United States",
      "latitude": 42.2986198,
      "longitude": -83.4534784
    }
  },
  {
    "id": 31,
    "firstname": "Yueming",
    "lastname": "Yang",
    "code": "GLO-1029",
    "birthdate": "1963-11-19",
    "ssn": "087-86-1825",
    "phone": "734-502-1598",
    "email": "huiipersonal@gmail.com ",
    "address": {
      "type": "Home",
      "address": "35594 Dove Trl",
      "city": "Westland",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48185",
      "country": "United States",
      "latitude": 42.331226,
      "longitude": -83.391288
    }
  },
  {
    "id": 32,
    "firstname": "Liqun",
    "lastname": "Qiu",
    "code": "GLO-1030",
    "birthdate": "1961-11-24",
    "ssn": "382-19-5955",
    "phone": "248-315-0256",
    "email": "lqi78865@gmail.com ",
    "address": {
      "type": "Home",
      "address": "1015 Larchwood Dr",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48083",
      "country": "United States",
      "latitude": 42.5536633,
      "longitude": -83.1302132
    }
  },
  {
    "id": 33,
    "firstname": "Yuelin",
    "lastname": "Li",
    "code": "GLO-1031",
    "birthdate": "1953-11-22",
    "ssn": "357-15-6792",
    "phone": "248-251-9350",
    "email": "yxwenster@gmail.com",
    "address": {
      "type": "Home",
      "address": "1578 Caliper Dr",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48084",
      "country": "United States",
      "latitude": 42.5760331,
      "longitude": -83.1787276
    }
  },
  {
    "id": 34,
    "firstname": "Juseline",
    "lastname": "Sainz",
    "code": "GLO-1032",
    "birthdate": "1979-10-04",
    "ssn": "583-85-1831",
    "phone": "313-800-2049",
    "email": "alizesainz79@icloud.com",
    "address": {
      "type": "Home",
      "address": "15351 Pembroke Ave",
      "city": "Detroit",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48235",
      "country": "United States",
      "latitude": 42.4374278,
      "longitude": -83.1987153
    }
  },
  {
    "id": 35,
    "firstname": "Wei",
    "lastname": "Zhao",
    "code": "GLO-1033",
    "birthdate": "1971-05-07",
    "ssn": "470-35-7101",
    "phone": "248-345-4919",
    "email": "weizhao101@hotmail.com ",
    "address": {
      "type": "Home",
      "address": "44863 Revere Dr",
      "city": "Novi",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48377",
      "country": "United States",
      "latitude": 42.4972519,
      "longitude": -83.4918366
    }
  },
  {
    "id": 36,
    "firstname": "Mariya",
    "lastname": "Varshavska",
    "code": "GLO-1034",
    "birthdate": "1969-10-11",
    "ssn": "348-59-7229",
    "phone": "734-730-2751",
    "email": "mariyavarshavska9@gmail.com",
    "email2": "algard1977@gmail.com",
    "address": {
      "type": "Home",
      "address": "2246 Yemans St",
      "city": "Hamtramck",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48212",
      "country": "United States",
      "latitude": 42.3957735,
      "longitude": -83.0634669
    }
  },
  {
    "id": 37,
    "firstname": "Devora",
    "lastname": "Dumitrescu",
    "code": "GLO-1035",
    "birthdate": "1957-12-06",
    "ssn": "378-86-2881",
    "phone": "313-909-2665",
    "email": "vdumitrescu@outlook.com",
    "address": {
      "type": "Home",
      "address": "10387 Overhill Dr",
      "city": "Brighton",
      "county": "Livingston",
      "state": "MI",
      "zipcode": "48114",
      "country": "United States",
      "latitude": 42.5269681,
      "longitude": -83.7482109
    }
  },
  {
    "id": 38,
    "firstname": "Inna",
    "lastname": "Tikan",
    "code": "GLO-1036",
    "birthdate": "1970-09-30",
    "ssn": "741-43-1130",
    "phone": "248-425-3970",
    "email": "innaukr@gmail.com",
    "email2": "innatikan051@gmail.com",
    "address": {
      "type": "Home",
      "address": "4294 15 Mile Rd",
      "city": "Sterling Heights",
      "county": "Macomb",
      "state": "MI",
      "zipcode": "48310",
      "country": "United States",
      "latitude": 42.5485193,
      "longitude": -83.0649154
    }
  },
  {
    "id": 39,
    "firstname": "Maksim",
    "lastname": "Zhitkov",
    "code": "GLO-1037",
    "birthdate": "1970-12-27",
    "ssn": "381-15-3131",
    "phone": "248-935-7195",
    "email": "maxzhitkov@gmail.com ",
    "address": {
      "type": "Home",
      "address": "7119 Oakridge Ct",
      "city": "Clarkston",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48346",
      "country": "United States",
      "latitude": 42.7229128,
      "longitude": -83.4387212
    }
  },
  {
    "id": 40,
    "firstname": "Yu",
    "lastname": "Yao",
    "code": "GLO-1038",
    "birthdate": "1977-11-02",
    "ssn": "021-99-1786",
    "phone": "734-276-0011",
    "email": "yuyao1205@yahoo.com",
    "address": {
      "type": "Home",
      "address": "1058 Greenhills Dr",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.28788,
      "longitude": -83.680915
    }
  },
  {
    "id": 41,
    "firstname": "Lianchang",
    "lastname": "Qiao",
    "code": "GLO-1039",
    "birthdate": "1954-09-04",
    "ssn": "284-65-8241",
    "phone": "734-800-9504",
    "email": "lianchangqiao@gmail.com",
    "address": {
      "type": "Home",
      "address": "2864 Elmwood Ave",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48104",
      "country": "United States",
      "latitude": 42.2463621,
      "longitude": -83.6991534
    }
  },
  {
    "id": 42,
    "firstname": "Sarvinoz",
    "lastname": "Karimova",
    "code": "GLO-1040",
    "birthdate": "1995-06-05",
    "ssn": "290-83-0075",
    "phone": "248-513-5858",
    "email": "karimovanoza@icloud.com",
    "address": {
      "type": "Apartment",
      "address": "24712 Independence Dr, Apt 2302",
      "city": "Farmington",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48335",
      "country": "United States",
      "latitude": 42.4754938,
      "longitude": -83.4152523
    }
  },
  {
    "id": 43,
    "firstname": "Sophie",
    "lastname": "Shao",
    "code": "GLO-1041",
    "birthdate": "1967-06-22",
    "ssn": "301-90-0428",
    "phone": "248-494-2636",
    "email": "sshao321@yahoo.com ",
    "address": {
      "type": "Home",
      "address": "356 Shore Brook Ln",
      "city": "Walled Lake",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48390",
      "country": "United States",
      "latitude": 42.5304649,
      "longitude": -83.4566593
    }
  },
  {
    "id": 44,
    "firstname": "JuanJuan",
    "lastname": "Zhu",
    "code": "GLO-1042",
    "birthdate": "1960-01-02",
    "ssn": "613-35-7846",
    "email": "zjj48071@gmail.com ",
    "address": {
      "type": "Home",
      "address": "26640 Couzens Ave",
      "city": "Madison Heights",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48071",
      "country": "United States",
      "latitude": 42.4893171,
      "longitude": -83.0947927
    }
  },
  {
    "id": 45,
    "firstname": "Dongdi",
    "lastname": "Li",
    "code": "GLO-1043",
    "birthdate": "1962-11-04",
    "ssn": "397-65-5708",
    "phone": "734-664-5669",
    "email": "lidongdi1962@gmail.com ",
    "address": {
      "type": "Home",
      "address": "1921 Savannah Ln",
      "city": "Ypsilanti",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48198",
      "country": "United States",
      "latitude": 42.2721753,
      "longitude": -83.5919691
    }
  },
  {
    "id": 46,
    "firstname": "Angie",
    "lastname": "Lin",
    "code": "GLO-1044",
    "birthdate": "1977-12-04",
    "ssn": "366-33-2730",
    "phone": "248-342-8039",
    "email": "angielin99@yahoo.com ",
    "address": {
      "type": "Home",
      "address": "117 Manor Wy",
      "city": "Rochester",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48309",
      "country": "United States",
      "latitude": 42.6509755,
      "longitude": -83.1756188
    }
  },
  {
    "id": 47,
    "firstname": "Qiang",
    "lastname": "Wei",
    "code": "GLO-1045",
    "birthdate": "1968-05-19",
    "ssn": "531-35-6708",
    "phone": "248-345-4019",
    "email": "weix0014@hotmail.com ",
    "address": {
      "type": "Home",
      "address": "26551 Glenwood Dr",
      "city": "Novi",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48374",
      "country": "United States",
      "latitude": 42.4847605,
      "longitude": -83.5383197
    }
  },
  {
    "id": 48,
    "firstname": "Jose",
    "lastname": "Irizarry",
    "code": "GLO-1046",
    "birthdate": "1998-08-10",
    "ssn": "583-47-7220",
    "phone": "313-800-2049",
    "email": "joseirizarry@maxmilahomecare.com ",
    "address": {
      "type": "Home",
      "address": "15351 Pembroke Ave",
      "city": "Detroit",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48235",
      "country": "United States",
      "latitude": 42.4374278,
      "longitude": -83.1987153
    }
  },
  {
    "id": 49,
    "firstname": "Hong",
    "lastname": "Zhang",
    "code": "GLO-1047",
    "birthdate": "1959-07-14",
    "ssn": "578-11-7150",
    "phone": "248-606-9696",
    "email": "hzhang996@gmail.com",
    "address": {
      "type": "Home",
      "address": "1819 Lexington Dr",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48084",
      "country": "United States",
      "latitude": 42.5669391,
      "longitude": -83.183713
    }
  },
  {
    "id": 50,
    "firstname": "Hector",
    "lastname": "Salinas",
    "code": "GLO-1048",
    "birthdate": "1976-12-16",
    "ssn": "791-83-6589",
    "phone": "248-679-2601",
    "email": "hectorsalpen@gmail.com ",
    "address": {
      "type": "Home",
      "address": "7677 Maple Dr",
      "city": "Westland",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48185",
      "country": "United States",
      "latitude": 42.3429722,
      "longitude": -83.4167703
    }
  },
  {
    "id": 51,
    "firstname": "Xianying",
    "lastname": "Xing",
    "code": "GLO-1049",
    "birthdate": "1972-02-26",
    "ssn": "386-31-9617",
    "phone": "734-846-0807",
    "email": "xing.xy@gmail.com",
    "languages": "Chinese",
    "address": {
      "type": "Home",
      "address": "1556 N Maple Rd",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48103",
      "country": "United States",
      "latitude": 42.2958081,
      "longitude": -83.7809873
    }
  },
  {
    "id": 52,
    "firstname": "Qing",
    "lastname": "Gao",
    "code": "GLO-1050",
    "birthdate": "1964-06-19",
    "ssn": "362-23-2406",
    "phone": "248-403-1465",
    "email": "jieminggao@yahoo.com",
    "languages": "Chinese",
    "address": {
      "type": "Home",
      "address": "20939 Meadowlark St",
      "city": "Farmington",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48336",
      "country": "United States",
      "latitude": 42.4437667,
      "longitude": -83.3688164
    }
  },
  {
    "id": 53,
    "firstname": "Yulianna",
    "lastname": "Kowalczyk",
    "code": "GLO-1051",
    "birthdate": "2006-06-12",
    "ssn": "371-33-4358",
    "phone": "734-620-9384",
    "email": "yulikowalczyk@gmail.com",
    "address": {
      "type": "Home",
      "address": "34500 Grandon St",
      "city": "Livonia",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48150",
      "country": "United States",
      "latitude": 42.3577793,
      "longitude": -83.3833575
    }
  },
  {
    "id": 54,
    "firstname": "Hua",
    "lastname": "Chen",
    "code": "GLO-1052",
    "birthdate": "1970-09-26",
    "ssn": "385-21-2641",
    "phone": "734-637-3447",
    "email": "hchen33@gmail.com",
    "address": {
      "type": "Home",
      "address": "46861 Wareham",
      "city": "Canton",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48187",
      "country": "United States",
      "latitude": 42.3183167,
      "longitude": -83.5017556
    }
  },
  {
    "id": 55,
    "firstname": "Svitlana",
    "lastname": "Nakonechna",
    "code": "GLO-1053",
    "birthdate": "1991-04-13",
    "ssn": "748-22-3421",
    "phone": "248-678-2299",
    "email": "vladimiswitas305@gmail.com",
    "languages": "Russian",
    "address": {
      "type": "Apartment",
      "address": "30070 W 12 Mile Rd, Apt 128",
      "city": "Farmington Hills",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48334",
      "country": "United States",
      "latitude": 42.5004351,
      "longitude": -83.3487219
    }
  },
  {
    "id": 56,
    "firstname": "Yuanqu",
    "lastname": "Chen",
    "code": "GLO-1054",
    "birthdate": "1964-01-10",
    "ssn": "696-45-5717",
    "phone": "734-666-8088",
    "email": "1906442418@qq.com",
    "address": {
      "type": "Home",
      "address": "2448 Nixon Rd",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.3093418,
      "longitude": -83.7071462
    }
  },
  {
    "id": 57,
    "firstname": "Li",
    "lastname": "Li",
    "code": "GLO-1055",
    "birthdate": "1971-05-13",
    "ssn": "366-29-8729",
    "phone": "248-795-0385",
    "email": "lili4945@gmail.com ",
    "address": {
      "type": "Home",
      "address": "4945 Moonglow Dr",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48098",
      "country": "United States",
      "latitude": 42.590009,
      "longitude": -83.1966619
    }
  },
  {
    "id": 58,
    "firstname": "Edward",
    "lastname": "Wang",
    "code": "GLO-1056",
    "birthdate": "1965-07-14",
    "ssn": "287-90-3655",
    "phone": "248-202-7771",
    "email": "sshao21@yahoo.com",
    "address": {
      "type": "Home",
      "address": "256 Shore Brook Ln",
      "city": "Walled Lake",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48390",
      "country": "United States",
      "latitude": 42.529143,
      "longitude": -83.4549571
    }
  },
  {
    "id": 59,
    "firstname": "Jun",
    "lastname": "Ruan",
    "code": "GLO-1057",
    "birthdate": "1976-01-21",
    "ssn": "842-28-7248",
    "phone": "586-344-4259",
    "email": "rj107521186@gmail.com",
    "address": {
      "type": "Home",
      "address": "29252 Tessmer Ct",
      "city": "Madison Heights",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48071",
      "country": "United States",
      "latitude": 42.5062955,
      "longitude": -83.0874886
    }
  },
  {
    "id": 60,
    "firstname": "Yongmei",
    "lastname": "Liang",
    "code": "GLO-1058",
    "birthdate": "1971-04-08",
    "ssn": "598-39-8409",
    "phone": "248-825-0652",
    "email": "lyongmei1971@gmail.com ",
    "address": {
      "type": "Home",
      "address": "3019 Longview Ave",
      "city": "Rochester",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48307",
      "country": "United States",
      "latitude": 42.6358032,
      "longitude": -83.0990684
    }
  },
  {
    "id": 61,
    "firstname": "Olha",
    "lastname": "Chopyk",
    "code": "GLO-1059",
    "birthdate": "1989-10-11",
    "ssn": "001-67-2601",
    "phone": "313-804-2691",
    "email": "olyachopik@gmail.com ",
    "address": {
      "type": "Apartment",
      "address": "31278 Shorecrest Dr, Apt 23207",
      "city": "Novi",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48377",
      "country": "United States",
      "latitude": 42.524451,
      "longitude": -83.499185
    }
  },
  {
    "id": 62,
    "firstname": "Jiangchen",
    "lastname": "Chen",
    "code": "GLO-1060",
    "birthdate": "1970-05-18",
    "ssn": "897-02-3215",
    "phone": "734-666-8382",
    "email": "jcchen0518@gmail.com ",
    "address": {
      "type": "Home",
      "address": "2448 Nixon Rd",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.3093418,
      "longitude": -83.7071462
    }
  },
  {
    "id": 63,
    "firstname": "Iryna",
    "lastname": "Vasiuk",
    "code": "GLO-1061",
    "birthdate": "1980-10-05",
    "ssn": "718-63-9369",
    "phone": "248-949-6006",
    "email": "irina.vasiuk@gmail.com ",
    "address": {
      "type": "Home",
      "address": "11729 Spicer Dr",
      "city": "Plymouth",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48170",
      "country": "United States",
      "latitude": 42.367624,
      "longitude": -83.4548365
    }
  },
  {
    "id": 64,
    "firstname": "Xia",
    "lastname": "Zhang",
    "code": "GLO-1062",
    "birthdate": "1965-07-16",
    "ssn": "817-14-2398",
    "phone": "734-546-4566",
    "email": "luzhang200@163.com ",
    "address": {
      "type": "Home",
      "address": "2747 Barklay Wy",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.3201593,
      "longitude": -83.7067826
    }
  },
  {
    "id": 65,
    "firstname": "Hanlei",
    "lastname": "Wang",
    "code": "GLO-1063",
    "birthdate": "2001-02-16",
    "ssn": "403-65-4066",
    "phone": "513-734-8551",
    "email": "hanleiwang.hlw@gmail.com ",
    "address": {
      "type": "Home",
      "address": "31690 Cowan Rd",
      "city": "Westland",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48185",
      "country": "United States",
      "latitude": 42.3416274,
      "longitude": -83.3539329
    }
  },
  {
    "id": 66,
    "firstname": "Zhiwei",
    "lastname": "Yan",
    "code": "GLO-1064",
    "birthdate": "1980-08-03",
    "ssn": "683-53-3067",
    "phone": "734-678-7008",
    "email": "david800803@gmail.com",
    "address": {
      "type": "Home",
      "address": "31610 Eagle Ct",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.3217079,
      "longitude": -83.7154563
    }
  },
  {
    "id": 67,
    "firstname": "Makenzy",
    "lastname": "Herman",
    "code": "GLO-1065",
    "birthdate": "1999-05-10",
    "ssn": "381-23-4607",
    "phone": "248-495-9732",
    "email": "makenzyherman711@gmail.com ",
    "address": {
      "type": "Home",
      "address": "23360 Crossley Ave",
      "city": "Hazel Park",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48030",
      "country": "United States",
      "latitude": 42.465071,
      "longitude": -83.0883308
    }
  },
  {
    "id": 68,
    "firstname": "Xiao",
    "middlename": "Xia",
    "lastname": "Chen",
    "code": "GLO-1066",
    "birthdate": "1984-06-22",
    "ssn": "641-54-3383",
    "phone": "586-663-6620",
    "email": "xchen168138@gmail.com",
    "address": {
      "type": "Home",
      "address": "39816 Dorian Dr",
      "city": "Sterling Heights",
      "county": "Macomb",
      "state": "MI",
      "zipcode": "48310",
      "country": "United States",
      "latitude": 42.5845432,
      "longitude": -83.0837694
    }
  },
  {
    "id": 69,
    "firstname": "Alla",
    "lastname": "Boliukh",
    "code": "GLO-1067",
    "birthdate": "1980-04-19",
    "ssn": "791-43-3215",
    "phone": "517-302-7053",
    "email": "bolykalla@ukr.net",
    "address": {
      "type": "Home",
      "address": "11092 N Beck Rd",
      "city": "Plymouth",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48170",
      "country": "United States",
      "latitude": 42.3616913,
      "longitude": -83.5081616
    }
  },
  {
    "id": 70,
    "firstname": "Leah",
    "lastname": "Black-Elk",
    "code": "GLO-1068",
    "birthdate": "1981-05-16",
    "ssn": "386-88-7618",
    "phone": "248-954-5227",
    "email": "msblackelk@yahoo.com ",
    "address": {
      "type": "Home",
      "address": "5310 Wakefield Rd",
      "city": "Grand Blanc",
      "county": "Genesee",
      "state": "MI",
      "zipcode": "48439",
      "country": "United States",
      "latitude": 42.9525968,
      "longitude": -83.5838152
    }
  },
  {
    "id": 71,
    "firstname": "Mona",
    "lastname": "Awada",
    "code": "GLO-1069",
    "birthdate": "1966-08-15",
    "ssn": "729-16-4413",
    "phone": "313-717-2484",
    "email": "rawanlakis@icloud.com",
    "address": {
      "type": "Home",
      "address": "25839 Midway St",
      "city": "Dearborn Heights",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48127",
      "country": "United States",
      "latitude": 42.3304114,
      "longitude": -83.2929536
    }
  },
  {
    "id": 72,
    "firstname": "Hong",
    "lastname": "Hu",
    "code": "GLO-1070",
    "birthdate": "1967-05-19",
    "ssn": "878-33-2891",
    "phone": "734-800-6188",
    "email": "191023092@qq.com ",
    "address": {
      "type": "Home",
      "address": "2660 S Knightsbridge Cir",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.314296,
      "longitude": -83.73299
    }
  },
  {
    "id": 73,
    "firstname": "Mariya",
    "lastname": "Sheuchyk",
    "code": "GLO-1071",
    "birthdate": "1987-01-18",
    "ssn": "099-81-7874",
    "phone": "810-493-1183",
    "email": "khaitmaria8@gmail.com",
    "address": {
      "type": "Home",
      "address": "3725 Delaware Ave",
      "city": "Flint",
      "county": "Genesee",
      "state": "MI",
      "zipcode": "48506",
      "country": "United States",
      "latitude": 43.0401557,
      "longitude": -83.6392529
    }
  },
  {
    "id": 74,
    "firstname": "Geoffrey",
    "lastname": "Yezersky",
    "code": "GLO-1073",
    "birthdate": "1999-10-07",
    "ssn": "363-25-6834",
    "phone": "248-553-5429",
    "email": "gyezersky82@gmail.com",
    "address": {
      "type": "Home",
      "address": "35987 Charter Crest Rd",
      "city": "Farmington",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48335",
      "country": "United States",
      "latitude": 42.4772389,
      "longitude": -83.4041647
    }
  },
  {
    "id": 75,
    "firstname": "Keman",
    "lastname": "Li",
    "code": "GLO-1074",
    "birthdate": "1977-12-04",
    "ssn": "739-03-6932",
    "phone": "734-447-6049",
    "email": "kemanli2014@gmail.com",
    "address": {
      "type": "Home",
      "address": "387 Robyn",
      "city": "Canton",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48187",
      "country": "United States",
      "latitude": 42.3093707,
      "longitude": -83.4564075
    }
  },
  {
    "id": 76,
    "firstname": "Huoling",
    "lastname": "Deng",
    "code": "GLO-1075",
    "birthdate": "1962-04-15",
    "ssn": "386-37-5308",
    "phone": "248-525-4493",
    "email": "1040403123@qq.com",
    "address": {
      "type": "Condominium",
      "address": "2346 London Bridge Dr, Unit 63",
      "city": "Rochester Hills",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48307",
      "country": "United States",
      "latitude": 42.6483312,
      "longitude": -83.1159359
    }
  },
  {
    "id": 77,
    "firstname": "Qinhua",
    "lastname": "Ruan",
    "code": "GLO-1076",
    "birthdate": "1996-05-05",
    "ssn": "660-43-0790",
    "phone": "248-346-5302",
    "email": "fuyuanai599@gmail.com",
    "address": {
      "type": "Home",
      "address": "6775 Berry Pointe Dr",
      "city": "Clarkston",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48348",
      "country": "United States",
      "latitude": 42.7557285,
      "longitude": -83.4183854
    }
  },
  {
    "id": 78,
    "firstname": "Lyubov",
    "lastname": "Gutsul",
    "code": "GLO-1077",
    "birthdate": "1959-03-21",
    "ssn": "795-69-8337",
    "phone": "248-795-0432",
    "email": "gutsul0418@gmail.com ",
    "address": {
      "type": "Home",
      "address": "15458 Park Village Blvd",
      "city": "Taylor",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48180",
      "country": "United States",
      "latitude": 42.192444,
      "longitude": -83.2976847
    }
  },
  {
    "id": 79,
    "firstname": "Olena",
    "lastname": "Koda",
    "code": "GLO-1078",
    "birthdate": "1986-09-10",
    "ssn": "674-84-9339",
    "phone": "248-222-7225",
    "email": "kodao86@gmail.com",
    "address": {
      "type": "Home",
      "address": "28202 Chesapeake Cir",
      "city": "Walled Lake",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48390",
      "country": "United States",
      "latitude": 42.5358189,
      "longitude": -83.5107371
    }
  },
  {
    "id": 80,
    "firstname": "Jing",
    "lastname": "Huang",
    "code": "GLO-1079",
    "birthdate": "1967-08-08",
    "ssn": "371-27-9210",
    "phone": "248-273-1986",
    "email": "jeanyinmi@gmail.com",
    "address": {
      "type": "Home",
      "address": "3588 Oriole Dr",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48084",
      "country": "United States",
      "latitude": 42.5705004,
      "longitude": -83.1617325
    }
  },
  {
    "id": 81,
    "firstname": "Mekhriniso",
    "lastname": "Shadieva",
    "code": "GLO-1080",
    "birthdate": "1963-08-21",
    "ssn": "845-10-9380",
    "phone": "734-219-8163",
    "email": "mekhri306@gmail.com",
    "address": {
      "type": "Home",
      "address": "859 Groveland Cir",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48108",
      "country": "United States",
      "latitude": 42.2020613,
      "longitude": -83.7401654
    }
  },
  {
    "id": 82,
    "firstname": "Lan",
    "lastname": "Ge",
    "code": "GLO-1081",
    "birthdate": "1962-10-08",
    "ssn": "384-33-1842",
    "phone": "734-740-3966",
    "email": "langeyue@gmail.com ",
    "address": {
      "type": "Home",
      "address": "47274 Mallard Dr",
      "city": "Utica",
      "county": "Macomb",
      "state": "MI",
      "zipcode": "48315",
      "country": "United States",
      "latitude": 42.643714,
      "longitude": -82.9782956
    }
  },
  {
    "id": 83,
    "firstname": "Alena",
    "lastname": "Herter",
    "code": "GLO-1082",
    "birthdate": "1968-05-11",
    "ssn": "865-70-5532",
    "phone": "517-745-3079",
    "email": "shatil8049@gmail.com ",
    "address": {
      "type": "Home",
      "address": "3623 Heeney Rd",
      "city": "Stockbridge",
      "county": "Ingham",
      "state": "MI",
      "zipcode": "49285",
      "country": "United States",
      "latitude": 42.4469019,
      "longitude": -84.2146766
    }
  },
  {
    "id": 84,
    "firstname": "Qici",
    "lastname": "Deng",
    "code": "GLO-1083",
    "birthdate": "1971-08-26",
    "ssn": "371-23-2466",
    "phone": "248-635-4918",
    "email": "qicideng@gmail.com ",
    "address": {
      "type": "Home",
      "address": "35668 Saxony Dr.",
      "city": "Sterling Heights",
      "county": "Macomb",
      "state": "MI",
      "zipcode": "48310",
      "country": "United States",
      "latitude": 42.5556979,
      "longitude": -83.0548038
    }
  },
  {
    "id": 85,
    "firstname": "Yanfang",
    "lastname": "Liu",
    "code": "GLO-1084",
    "birthdate": "1965-02-27",
    "ssn": "010-55-2554",
    "phone": "734-834-0858",
    "email": "yanfang.liu650227@hotmail.com",
    "languages": "Chinese, English",
    "address": {
      "type": "Home",
      "address": "2864 Elmwood Ave",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48104",
      "country": "United States",
      "latitude": 42.2463621,
      "longitude": -83.6991534
    }
  },
  {
    "id": 86,
    "firstname": "Iryna",
    "lastname": "Hnedyk",
    "code": "GLO-1085",
    "birthdate": "1970-08-13",
    "ssn": "648-25-2717",
    "phone": "248-787-6473",
    "email": "gnedik.ira2@gmail.com",
    "address": {
      "type": "Apartment",
      "address": "31264 Spinglake Blvd, Apt 2307",
      "city": "Novi",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48377",
      "country": "United States",
      "latitude": 42.5240255,
      "longitude": -83.5016948
    }
  },
  {
    "id": 87,
    "firstname": "Yan",
    "lastname": "Han",
    "code": "GLO-1086",
    "birthdate": "1971-07-03",
    "ssn": "375-27-8061",
    "phone": "734-272-1794",
    "email": "paulinehan@yahoo.com ",
    "address": {
      "type": "Home",
      "address": "3213 Aldwych Circle",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.3207036,
      "longitude": -83.6946685
    }
  },
  {
    "id": 88,
    "firstname": "Feng",
    "lastname": "Lin",
    "code": "GLO-1087",
    "birthdate": "1987-01-27",
    "ssn": "716-45-8917",
    "phone": "248-525-5449",
    "email": "183393364@qq.com ",
    "address": {
      "type": "Condominium",
      "address": "2346 London Bridge Dr, Unit 63",
      "city": "Rochester Hills",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48307",
      "country": "United States",
      "latitude": 42.6483312,
      "longitude": -83.1159359
    }
  },
  {
    "id": 89,
    "firstname": "Xueying",
    "lastname": "Ding",
    "code": "GLO-1088",
    "birthdate": "1977-12-01",
    "ssn": "762-96-0284",
    "phone": "818-747-6152",
    "email": "lucydingxy@gmail.com",
    "languages": "Chinese, English",
    "address": {
      "type": "Home",
      "address": "3027 Forest Creek Ct",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48108",
      "country": "United States",
      "latitude": 42.239884,
      "longitude": -83.7189338
    }
  },
  {
    "id": 90,
    "firstname": "Huaying",
    "lastname": "Xie",
    "code": "GLO-1089",
    "birthdate": "1972-11-12",
    "ssn": "198-35-8398",
    "phone": "626-215-7436",
    "email": "xiej5800@gmail.com",
    "languages": "Mandarin",
    "address": {
      "type": "Home",
      "address": "3027 Forest Creek Ct",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48108",
      "country": "United States",
      "latitude": 42.239884,
      "longitude": -83.7189338
    }
  },
  {
    "id": 91,
    "firstname": "Ying",
    "lastname": "Gao",
    "code": "GLO-1090",
    "birthdate": "1973-10-12",
    "ssn": "480-73-1470",
    "phone": "734-355-6220",
    "email": "yinggao342@gmail.com",
    "languages": "Chinese, English",
    "address": {
      "type": "Home",
      "address": "342 Bedford Dr",
      "city": "Ypsilanti",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48198",
      "country": "United States",
      "latitude": 42.2593556,
      "longitude": -83.6153025
    }
  },
  {
    "id": 92,
    "firstname": "Jiazisong",
    "lastname": "Yan",
    "code": "GLO-1091",
    "birthdate": "2005-12-15",
    "ssn": "682-57-8699",
    "phone": "734-882-1413",
    "email": "jasony1215@gmail.com",
    "languages": "Chinese, English",
    "address": {
      "type": "Home",
      "address": "3161 Eagle Ct",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.3211052,
      "longitude": -83.7157316
    }
  },
  {
    "id": 93,
    "firstname": "Yevgeniya",
    "lastname": "Sosonkina",
    "code": "GLO-1092",
    "birthdate": "1965-06-19",
    "ssn": "021-74-0575",
    "phone": "248-510-8473",
    "email": "j.sosonki@yahoo.com",
    "address": {
      "type": "Home",
      "address": "1303 Stanley Blvd",
      "city": "Birmingham",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48009",
      "country": "United States",
      "latitude": 42.5373794,
      "longitude": -83.2190086
    }
  },
  {
    "id": 94,
    "firstname": "Hongmei",
    "lastname": "DeLosh",
    "code": "GLO-1093",
    "birthdate": "1964-06-20",
    "ssn": "383-31-3073",
    "phone": "734-780-1529",
    "email": "maydelosh@icloud.com ",
    "address": {
      "type": "Home",
      "address": "2359 Gale Island St",
      "city": "White Lake",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48386",
      "country": "United States",
      "latitude": 42.6700115,
      "longitude": -83.4542888
    }
  },
  {
    "id": 95,
    "firstname": "Jin",
    "lastname": "Xi",
    "code": "GLO-1094",
    "birthdate": "1970-09-30",
    "ssn": "500-65-3877",
    "phone": "734-864-6868",
    "email": "junxi1970@gmail.com",
    "address": {
      "type": "Apartment",
      "address": "2305 Sandalwood Cir, Apt 316C",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.3067138,
      "longitude": -83.7096141
    }
  },
  {
    "id": 96,
    "firstname": "Yangyang",
    "lastname": "Li",
    "code": "GLO-1095",
    "birthdate": "1980-02-14",
    "ssn": "366-33-9401",
    "phone": "248-881-0209",
    "email": "yl19802004@gmail.com ",
    "address": {
      "type": "Home",
      "address": "2552 Bonito Dr",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48085",
      "country": "United States",
      "latitude": 42.6059602,
      "longitude": -83.0992324
    }
  },
  {
    "id": 97,
    "firstname": "Qiaoxia",
    "lastname": "Ren",
    "code": "GLO-1096",
    "birthdate": "1990-10-28",
    "ssn": "211-77-7400",
    "phone": "917-892-4635",
    "email": "qiaoxren@gmail.com",
    "languages": "Chinese",
    "address": {
      "type": "Home",
      "address": "714 Barclay Dr",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48085",
      "country": "United States",
      "latitude": 42.5801931,
      "longitude": -83.1340214
    }
  },
  {
    "id": 98,
    "firstname": "Kathryn",
    "lastname": "Rogers",
    "code": "GLO-1097",
    "birthdate": "1958-05-24",
    "ssn": "373-66-3935",
    "phone": "248-497-0536",
    "email": "grannykathy08@gmail.com",
    "address": {
      "type": "Home",
      "address": "22228 N Brandon St",
      "city": "Farmington",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48336",
      "country": "United States",
      "latitude": 42.455254,
      "longitude": -83.3230948
    }
  },
  {
    "id": 99,
    "firstname": "Anna",
    "lastname": "Xue",
    "code": "GLO-1098",
    "birthdate": "1963-09-25",
    "ssn": "377-29-1263",
    "phone": "248-613-1398",
    "email": "annaxue0925@gmail.com",
    "address": {
      "type": "Home",
      "address": "2598 Driftwood Dr",
      "city": "Redford",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48239",
      "country": "United States",
      "latitude": 42.3792122,
      "longitude": -83.2880591
    }
  },
  {
    "id": 100,
    "firstname": "Ricardo",
    "lastname": "Estes",
    "code": "GLO-1099",
    "birthdate": "1958-01-25",
    "ssn": "330-56-0985",
    "phone": "734-545-3052",
    "email": "ricardoestes@comcast.net ",
    "address": {
      "type": "Home",
      "address": "2864 Elmwood",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48104",
      "country": "United States",
      "latitude": 42.2463621,
      "longitude": -83.6991534
    }
  },
  {
    "id": 101,
    "firstname": "Xiaobao",
    "lastname": "Huang",
    "code": "GLO-1100",
    "birthdate": "1959-11-25",
    "ssn": "434-63-1307",
    "phone": "586-441-8657",
    "email": "xiahuagreen@gmail.com",
    "languages": "Chinese, English",
    "address": {
      "type": "Home",
      "address": "3759 Kossuth Rd",
      "city": "Lake Orion",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48360",
      "country": "United States",
      "latitude": 42.7285216,
      "longitude": -83.2329719
    }
  },
  {
    "id": 102,
    "firstname": "Kai",
    "lastname": "Ho",
    "code": "GLO-1101",
    "birthdate": "1991-11-11",
    "ssn": "375-15-9863",
    "phone": "734-787-9452",
    "email": "kaihho91@gmail.com ",
    "address": {
      "type": "Home",
      "address": "19615 Ingram St",
      "city": "Westland",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48185",
      "country": "United States",
      "latitude": 42.3685578,
      "longitude": -83.3587045
    }
  },
  {
    "id": 103,
    "firstname": "Ling",
    "lastname": "Zhong",
    "code": "GLO-1102",
    "birthdate": "1955-11-08",
    "ssn": "386-08-4436",
    "phone": "248-320-1436",
    "email": "zhlillian@yahoo.com",
    "address": {
      "type": "Home",
      "address": "22293 Acadia Wy",
      "city": "Northville",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48167",
      "country": "United States",
      "latitude": 42.4509468,
      "longitude": -83.422313
    }
  },
  {
    "id": 104,
    "firstname": "Yang",
    "lastname": "Jiang",
    "code": "GLO-1103",
    "birthdate": "1961-07-31",
    "ssn": "367-13-0590",
    "phone": "313-686-8159",
    "email": "chaoy3@hotmail.com ",
    "address": {
      "type": "Home",
      "address": "33790 Norfolk St",
      "city": "Livonia",
      "county": "Wayne",
      "state": "MI",
      "zipcode": "48152",
      "country": "United States",
      "latitude": 42.4369809,
      "longitude": -83.3787929
    }
  },
  {
    "id": 105,
    "firstname": "Sandra",
    "lastname": "Vanderbuilt",
    "code": "GLO-1104",
    "birthdate": "1961-02-13",
    "ssn": "376-66-0412",
    "phone": "734-680-0342",
    "email": "sandravanderbilt6@gmail.com",
    "address": {
      "type": "Home",
      "address": "2970 Easy St",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48104",
      "country": "United States",
      "latitude": 42.245374,
      "longitude": -83.7086252
    }
  },
  {
    "id": 106,
    "firstname": "Zhifeng",
    "lastname": "Song",
    "code": "GLO-1105",
    "birthdate": "1973-02-27",
    "ssn": "851-25-5464",
    "phone": "248-525-9829",
    "email": "jsong1902@gmail.com",
    "address": {
      "type": "Home",
      "address": "1058 Greenhills Dr",
      "city": "Ann Arbor",
      "county": "Washtenaw",
      "state": "MI",
      "zipcode": "48105",
      "country": "United States",
      "latitude": 42.28788,
      "longitude": -83.680915
    }
  },
  {
    "id": 107,
    "firstname": "Liuping",
    "lastname": "Liang",
    "code": "GLO-1106",
    "birthdate": "1962-11-06",
    "ssn": "655-79-5547",
    "phone": "248-804-3227",
    "email": "liupingliang83@gmail.com ",
    "address": {
      "type": "Home",
      "address": "6129 Smithfield Rd",
      "city": "Troy",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48085",
      "country": "United States",
      "latitude": 42.6092062,
      "longitude": -83.1096319
    }
  },
  {
    "id": 108,
    "firstname": "Joanne",
    "lastname": "Ewart",
    "code": "GLO-1107",
    "birthdate": "1947-03-08",
    "ssn": "362-48-1388",
    "phone": "248-904-6711",
    "email": "lanangreg@sbcglobal.net",
    "address": {
      "type": "Home",
      "address": "606 S Williams St",
      "city": "Royal Oak",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48067",
      "country": "United States",
      "latitude": 42.4852773,
      "longitude": -83.1432019
    }
  },
  {
    "id": 109,
    "firstname": "Zebo",
    "lastname": "Nazarova",
    "code": "GLO-1108",
    "birthdate": "1988-05-07",
    "ssn": "683-96-5234",
    "phone": "248-383-3638",
    "email": "zebonazarova88@gmail.com ",
    "address": {
      "type": "Apartment",
      "address": "23981 Jamestown, Apt 302",
      "city": "Farmington",
      "county": "Oakland",
      "state": "MI",
      "zipcode": "48335",
      "country": "United States",
      "latitude": 42.4671433,
      "longitude": -83.4118444
    }
  },
  {
    "id": 110,
    "firstname": "Lola",
    "lastname": "Kudratova",
    "email": "kudratovalola11@gmail.com"
  },
  {
    "id": 111,
    "firstname": "Zahwa",
    "lastname": "Shehadeh",
    "phone": "313-960-0048",
    "email": "zahwa120@icloud.com"
  }
]

###
# group: Backup Recovery
# @name Add Bulk Patients
POST {{maxmila.baseUrl}}/bulk/patients
Content-Type: application/json

[
  {
    "patient":"1190167218",
    "admission":"GLO-900128",
    "firstname":"Shichong",
    "middlename":null,
    "lastname":"Guo",
    "phone":"734-623-3087",
    "address":{
      "type":"Home",
      "address":"2385 Sandalwood Cir",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.3074874,
      "longitude":-83.7129055
    }
  },
  {
    "patient":"1190167085",
    "admission":"GLO-900129",
    "firstname":"Keren",
    "middlename":null,
    "lastname":"Liu",
    "phone":"734-623-3087",
    "address":{
      "type":"Home",
      "address":"2385 Sandalwood Cir",
      "city":"Ann Arbor",
      "county":"Washtenaw",
      "state":"MI",
      "zipcode":"48105",
      "country": "United States",
      "latitude":42.3074874,
      "longitude":-83.7129055
    }
  }
]