### Get asigned patients by userid
GET {{maxmila.baseUrl}}/assigned/patients/2
Authorization: {{maxmila.administrator.token}}


### Get unasigned patients by userid
GET {{maxmila.baseUrl}}/unassigned/patients/2
Authorization: {{maxmila.administrator.token}}