### User assigng many patientsto user
POST {{maxmila.baseUrl}}/assign/patients
Authorization: {{maxmila.manager.token}}
Content-Type: application/json

{
  "user_id": 4,
  "patient_ids": [
    1,
    2,
    3,
    4,
    5,
    6,
    7
  ]
}


### User assigng many patientsto user
POST {{maxmila.baseUrl}}/unassign/patients
Authorization: {{maxmila.administrator.token}}
Content-Type: application/json

{
  "user_id": 77,
  "patient_ids": [
    49,
    52
  ]
}

### Get asigned patients by userid
GET {{maxmila.baseUrl}}/assigned/patients/4
Authorization: {{maxmila.manager.token}}



### Get unasigned patients by userid
GET {{maxmila.baseUrl}}/unassigned/patients/77
Authorization: {{maxmila.manager.token}}


### Get asigned patients by userid old version
GET {{maxmila.baseUrl}}/user/36/patients
Authorization: {{maxmila.administrator.token}}
