### User endpoints

###
# @name Update My Profile (self) - photo is NOT updatable here, use the upload endpoints
PUT {{maxmila.baseUrl}}/user/{{maxmila.caregiver.id}}
Content-Type: application/json
Authorization: {{maxmila.caregiver.token}}

{
  "firstname": "Test",
  "lastname": "Caregiver",
  "middlename": "Q",
  "birthdate": "1990-05-15",
  "phone": "734-555-0100",
  "email2": "caregiver.alt@testing.net",
  "languages": "English, Spanish",
  "description": "Updated from user.http",
  "ssn": "123-45-6789"
}

###
# @name Update Another User (manager/admin)
PUT {{maxmila.baseUrl}}/user/77
Content-Type: application/json
Authorization: {{maxmila.manager.token}}

{
  "code": "GLO-0000",
  "phone2": "734-555-0101"
}

###
# @name Update Another User as caregiver - expect 403
PUT {{maxmila.baseUrl}}/user/1
Content-Type: application/json
Authorization: {{maxmila.caregiver.token}}

{
  "firstname": "Nope"
}

###
# @name Update with invalid SSN - expect 400
PUT {{maxmila.baseUrl}}/user/{{maxmila.caregiver.id}}
Content-Type: application/json
Authorization: {{maxmila.caregiver.token}}

{
  "ssn": "123-4"
}

###
# @name Get My Photo path
GET {{maxmila.baseUrl}}/user/photo
Authorization: {{maxmila.caregiver.token}}

###
# @name Get Another User's Photo path (manager/admin)
GET {{maxmila.baseUrl}}/user/photo/77
Authorization: {{maxmila.manager.token}}
