name: Deploy Maxmila Homecare Rest API (Test)
on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'test'
    name: Deploy Test
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest source code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Sync files for Testing
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_MAXMILA_SERVER_TEST }}
          username: ${{ secrets.FTP_MAXMILA_USERNAME_TEST }}
          password: ${{ secrets.FTP_MAXMILA_PASSWORD_TEST }}
          protocol: ftps
          timeout: 90000          # Increased timeout to 90s
          max-retries: 3          # Add retry attempts
          log-level: verbose      # More detailed logging
          dangerous-clean-slate: false  # Prevent full directory cleanup
          exclude: |              # Exclude unnecessary files
            **/.git*
            **/.git*/**
            **/.env*
            **/tests/**
            **/database/**
            tests/**
            database/**
            .gitignore
            http-client.env.json
            LICENSE
            README.md
            secrets.txt
          state-name: .ftp-deploy-sync-state.json    # Keep track of sync state
          server-dir: /          # Specify your root directory if needed