name: Deploy Maxmila Homecare Rest API (Production)
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment'
        required: true
        default: 'Hotfix deployment'
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest source code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Display deployment information
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Manual deployment triggered"
          echo "Reason: ${{ github.event.inputs.reason }}"
          echo "Environment: ${{ github.event.inputs.environment }}"

      - name: Sync files for Production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_MAX_SERVER }}
          username: ${{ secrets.FTP_API_USERNAME_PROD }}
          password: ${{ secrets.FTP_API_PASSWORD_PROD }}
          protocol: ftps
          timeout: 90000          # Increased timeout to 60s
          max-retries: 3          # Add retry attempts
          log-level: verbose      # More detailed logging
          dangerous-clean-slate: false  # Prevent full directory cleanup
          exclude: |              # Exclude unnecessary files
            **/.git*
            **/.git*/**
            **/.env*
            **/tests/**
            **/database/**
            tests/**
            database/**
            .gitignore
            http-client.env.json
            LICENSE
            README.md
            secrets.txt
          state-name: .ftp-deploy-sync-state.json    # Keep track of sync state
          server-dir: /          # Specify your root directory if needed
