name: Deploy api for testing
on:
  pull_request:
    types: [closed]

permissions:
  contents: read

concurrency:
  group: deploy-test
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Test
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main'

    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_MAX_SERVER }}
          username: ${{ secrets.FTP_API_USERNAME_TEST }}
          password: ${{ secrets.FTP_API_PASSWORD_TEST }}
          protocol: ftps
          server-dir: /
          timeout: 90000
          max-retries: 2
          log-level: verbose
          dangerous-clean-slate: false
          state-name: .ftp-deploy-sync-state.json
          exclude: |
            **/.git*
            **/.github/**
            **/.env*
            **/tests/**
            **/database/**
            **/node_modules/**
            **/vendor/**
            .gitignore
            README.md
            LICENSE
            http-client.env.json
            secrets.txt